Blacs.hpp
void Cblacs_get(int context, int request, int *value)
Referenced by sisi4s::BlacsWorld::BlacsWorld.
int Cblacs_gridinit(int *context, char const *order, int np_row, int np_col)
Referenced by sisi4s::BlacsWorld::BlacsWorld.
void Cblacs_gridinfo(int context, int *np_row, int *np_col, int *my_row, int *my_col)
Referenced by sisi4s::BlacsWorld::BlacsWorld.
void Cblacs_gridexit(int ictxt)
Referenced by sisi4s::BlacsWorld::~BlacsWorld.
void Cblacs_barrier(int ictxt, char const *order)
Referenced by sisi4s::BlacsWorld::barrier.