sisi4s::CoulombIntegralsFromVertex
sisi4s::AlgorithmRegistrar< CoulombIntegralsFromVertex > CoulombIntegralsFromVertex::registrar_
Tensor<complex>* sisi4s::CoulombIntegralsFromVertex::GammaGai
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryRun, run.
Tensor<complex>* sisi4s::CoulombIntegralsFromVertex::GammaGia
Referenced by calculateComplexIntegrals, dryRun, run.
Tensor<complex>* sisi4s::CoulombIntegralsFromVertex::GammaGab
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryRun, run.
Tensor<complex>* sisi4s::CoulombIntegralsFromVertex::GammaGij
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::syms
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::vvvv
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::vovo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::vvoo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::voov
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::oovv
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::oooo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::ooov
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::vooo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateComplexIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::vvvo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, dryCalculateRealIntegrals, dryRun, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::ovoo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::ovov
Referenced by calculateComplexIntegrals, calculateRealIntegrals, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::ovvv
Referenced by calculateComplexIntegrals, calculateRealIntegrals, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::vvov
Referenced by calculateComplexIntegrals, calculateRealIntegrals, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::ovvo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::oovo
Referenced by calculateComplexIntegrals, calculateRealIntegrals, run.
std::array<int, 4> sisi4s::CoulombIntegralsFromVertex::vovv
Referenced by calculateComplexIntegrals, calculateRealIntegrals, run.
virtual std::string sisi4s::CoulombIntegralsFromVertex::getName()
CoulombIntegralsFromVertex::CoulombIntegralsFromVertex(std::vector< Argument > const &argumentList)
CoulombIntegralsFromVertex::~CoulombIntegralsFromVertex()
void CoulombIntegralsFromVertex::run()
Calculates Coulomb integrals Vabcd,Vabij,Vaibj,Vabci,Vijka,Vijkl from GammaGai,GammaGab,GammaGij Coulomb Vertices. Arguments can be any combination of the sort PPPP, PHPH, PPHH, HHHH, HHHP, PPPHCoulombIntegrals.
References calculateComplexIntegrals, calculateRealIntegrals, EMIT, GammaGab, GammaGai, GammaGia, GammaGij, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::isArgumentGiven, LOG, oooo, ooov, oovo, oovv, ovoo, ovov, ovvo, ovvv, syms, vooo, voov, vovo, vovv, vvoo, vvov, vvvo, vvvv.
void CoulombIntegralsFromVertex::dryRun()
Dry run for calculating Coulomb integrals Vabcd,Vabij,Vaibj,Vabci,Vijka Vijkl from GammaGai,GammaGab,GammaGij Coulomb Vertices. Arguments can be any combination of the sort PPPP, PHPH, PPHH, HHHH, HHHP, PPPHCoulombIntegrals.
References dryCalculateComplexIntegrals, dryCalculateRealIntegrals, GammaGab, GammaGai, GammaGia, GammaGij, sisi4s::DryTensor< F >::get_name, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getTensorArgument, sisi4s::DryTensor< F >::lens, LOG, oooo, ooov, oovv, syms, vooo, voov, vovo, vvoo, vvvo, vvvv.
void CoulombIntegralsFromVertex::calculateRealIntegrals()
References sisi4s::Algorithm::allocatedTensorArgument, sisi4s::fromComplexTensor, GammaGab, GammaGai, GammaGij, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::isArgumentGiven, LOG, oooo, ooov, oovo, oovv, ovoo, ovov, ovvo, ovvv, syms, vooo, voov, vovo, vovv, vvoo, vvov, vvvo, vvvv, sisi4s::Sisi4s::world.
Referenced by run.
void CoulombIntegralsFromVertex::calculateComplexIntegrals()
References GammaGab, GammaGai, GammaGia, GammaGij, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::isArgumentGiven, LOG, oooo, ooov, oovo, oovv, ovoo, ovov, ovvo, ovvv, syms, vooo, voov, vovo, vovv, vvoo, vvov, vvvo, vvvv, sisi4s::Sisi4s::world.
Referenced by run.
void CoulombIntegralsFromVertex::dryCalculateRealIntegrals()
References sisi4s::Algorithm::allocatedTensorArgument, sisi4s::Algorithm::isArgumentGiven, oooo, ooov, oovv, syms, vooo, voov, vovo, vvoo, vvvo, vvvv.
Referenced by dryRun.
void CoulombIntegralsFromVertex::dryCalculateComplexIntegrals()
References sisi4s::Algorithm::isArgumentGiven, oooo, ooov, oovv, syms, vooo, voov, vovo, vvoo.
Referenced by dryRun.