sisi4s::RangeParser
const std::string sisi4s::RangeParser::rawRange
Referenced by parse.
std::vector<int> sisi4s::RangeParser::parsedRange
Referenced by getRange, parse.
sisi4s::RangeParser::RangeParser(const std::string &rawRange_)
Constructor from a string, it will parse the string automatically.
References parse.
std::vector< int > sisi4s::RangeParser::getRange() const
Get the range in the form of a vector of integers.
References parsedRange.
Referenced by sisi4s::operator<<, sisi4s::CcsdEquationOfMotionDavidson::run.
std::vector< int > sisi4s::RangeParser::atomicRangeToRange(const std::string &atomicRange)
Parse individual range atoms. For example this method will map "2" into std::vector<int>{2} and "2-3" into std::vector<int>{2,3}.
References LOG.
Referenced by parse.
void sisi4s::RangeParser::parse()
Main parser method, it will parse a comma separated string of range delimiters.
E.g. it will turn "2 ,3 , 4, 8-10" into {2,3,4,8,9,10}. Note that it is supposed to be whitespace safe.
References atomicRangeToRange, parsedRange, rawRange, pars::space.
Referenced by RangeParser.