CLI::FileError
CLI::FileError::FileError(std::string ename, std::string msg, int exit_code)
Referenced by Missing.
CLI::FileError::FileError(std::string ename, std::string msg, ExitCodes exit_code)
CLI::FileError::FileError(std::string msg, ExitCodes exit_code)
CLI::FileError::FileError(std::string msg, int exit_code)
CLI::FileError::FileError(std::string msg)
static FileError CLI::FileError::Missing(std::string name)
References FileError.
Referenced by CLI::App::_process_config_file, CLI::Config::from_file.