sisi4s::SimilarityTransformedHamiltonian
Dressing
typedef SimilarityTransformedHamiltonian sisi4s::SimilarityTransformedHamiltonian< F >::STH
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Tai
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Tabij
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Tabcijk
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Tabcdijkl
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Fij
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Fab
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Fia
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vabcd
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Viajb
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vijab
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vijkl
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vijka
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Viabc
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Viajk
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vabic
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vaibc
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vaibj
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Viabj
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vijak
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vaijb
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vabci
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::Vabij
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::VVaijb
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::VViabc
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::VVijka
Tensor<F>* sisi4s::SimilarityTransformedHamiltonian< F >::VVijab
Tensor<sisi4s::complex>* sisi4s::SimilarityTransformedHamiltonian< F >::GammaGqr
bool sisi4s::SimilarityTransformedHamiltonian< F >::_with_right_apply_intermediates
bool sisi4s::SimilarityTransformedHamiltonian< F >::_withStantonIntermediatesUCCSD
bool sisi4s::SimilarityTransformedHamiltonian< F >::_withRingCCSDT
bool sisi4s::SimilarityTransformedHamiltonian< F >::_withCISD
bool sisi4s::SimilarityTransformedHamiltonian< F >::_withCIS
std::shared_ptr< StantonIntermediatesUCCSD<F> > sisi4s::SimilarityTransformedHamiltonian< F >::stantonIntermediatesUccsd
int sisi4s::SimilarityTransformedHamiltonian< F >::No
int sisi4s::SimilarityTransformedHamiltonian< F >::Nv
Dressing sisi4s::SimilarityTransformedHamiltonian< F >::dressing
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wij
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wab
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wia
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wai
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wabij
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wijab
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wabcd
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wabci
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Waibc
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wiabj
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wiajk
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wijka
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wijkl
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Wabcijk
std::shared_ptr< Tensor<F> > sisi4s::SimilarityTransformedHamiltonian< F >::Tau_abij
sisi4s::SimilarityTransformedHamiltonian< F >::SimilarityTransformedHamiltonian(int No_, int Nv_)
sisi4s::SimilarityTransformedHamiltonian< F >::~SimilarityTransformedHamiltonian()
SFockVector< F > SimilarityTransformedHamiltonian::right_apply_hirata_RPA(SFockVector< F > &v)
References sisi4s::FockVector< F >::get, NEW, PTR, ST_DEBUG, sisi4s::Sisi4s::world.
Referenced by sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run.
FockVector< F > SimilarityTransformedHamiltonian::right_apply_CISD(FockVector< F > &R)
References sisi4s::FockVector< F >::get, PTR.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_Intermediates(SDFockVector< F > &v)
References sisi4s::FockVector< F >::get, PTR.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_hirata(SDFockVector< F > &v)
References sisi4s::FockVector< F >::get, PTR, ST_DEBUG.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply(SDFockVector< F > &v)
SDFockVector< F > SimilarityTransformedHamiltonian::leftApply_hirata(SDFockVector< F > &v)
References sisi4s::FockVector< F >::get, PTR.
SDFockVector< F > SimilarityTransformedHamiltonian::leftApplyIntermediates(SDFockVector< F > &v)
References sisi4s::FockVector< F >::get, PTR.
SDFockVector< F > sisi4s::SimilarityTransformedHamiltonian< F >::leftApply(SDFockVector< F > &v)
SDTFockVector< F > SimilarityTransformedHamiltonian::right_apply_hirata(SDTFockVector< F > &v)
References sisi4s::FockVector< F >::get, PTR, ST_DEBUG.
SDTFockVector< F > SimilarityTransformedHamiltonian::right_apply(SDTFockVector< F > &v)
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_CCSD_IP(SDFockVector< F > &)
Referenced by sisi4s::UCcsdIPEquationOfMotionDavidson::run.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_hirata_CCSD_IP(SDFockVector< F > &)
References sisi4s::FockVector< F >::get, PTR.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_Intermediates_CCSD_IP(SDFockVector< F > &)
References sisi4s::FockVector< F >::get, PTR.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_CCSD_EA(SDFockVector< F > &)
Referenced by sisi4s::UCcsdEAEquationOfMotionDavidson::run.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_hirata_CCSD_EA(SDFockVector< F > &)
References sisi4s::FockVector< F >::get, PTR.
SDFockVector< F > SimilarityTransformedHamiltonian::right_apply_Intermediates_CCSD_EA(SDFockVector< F > &)
References sisi4s::FockVector< F >::get, PTR.
SimilarityTransformedHamiltonian< F >::StructureFactor SimilarityTransformedHamiltonian::structureFactor(SDFockVector< F > &t, const StructureFactorSettings &s={ .onlySingles=false,.onlyDoubles=false,.hartreeInOneBody=false,.fockInOneBody=false})
References sisi4s::conjugate, DEFINE_AND_CAST, sisi4s::SimilarityTransformedHamiltonian< F >::StructureFactorSettings::fockInOneBody, sisi4s::FockVector< F >::get, sisi4s::SimilarityTransformedHamiltonian< F >::StructureFactorSettings::hartreeInOneBody, NEW, sisi4s::SimilarityTransformedHamiltonian< F >::StructureFactorSettings::onlyDoubles, sisi4s::SimilarityTransformedHamiltonian< F >::StructureFactorSettings::onlySingles, PTR, ST_DEBUG, sisi4s::Sisi4s::world.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getIJ()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getAB()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getAI()
References LOG, NEW, sisi4s::Sisi4s::world.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getAI_RPA()
References LOG, NEW, ST_DEBUG, sisi4s::Sisi4s::world.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getIA()
References LOG, NEW, sisi4s::Sisi4s::world.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getABIJ()
References LOG, NEW, ST_DEBUG, sisi4s::Sisi4s::world.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getABIJ_RPA()
References LOG, NEW, sisi4s::Sisi4s::world.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getIJAB()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getABCD()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getABCI()
References LOG, NEW, ST_DEBUG.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getAIBC()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getIABJ()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getIAJK()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getIJKA()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getIJKL()
References LOG, NEW.
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getABCIJK()
References LOG, NEW, ST_DEBUG, sisi4s::Sisi4s::world.
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setTai(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setTabij(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setTabcijk(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setTabcdijkl(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setFij(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setFab(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setFia(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVabcd(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setViajb(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVijab(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVijkl(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVijka(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setViabc(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setViajk(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVabic(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVaibc(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVaibj(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setViabj(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVijak(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVaijb(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVabci(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVabij(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVVaijb(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVViabc(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVVijka(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setVVijab(Tensor< F > *t)
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::setGammaGqr(Tensor< sisi4s::complex > *t)
STH & sisi4s::SimilarityTransformedHamiltonian< F >::setDressing(Dressing d)
std::shared_ptr< Tensor< F > > SimilarityTransformedHamiltonian::getTauABIJ()
References LOG, NEW.
std::string sisi4s::SimilarityTransformedHamiltonian< F >::getAbbreviation() const
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::with_right_apply_intermediates(bool const &v)
bool & sisi4s::SimilarityTransformedHamiltonian< F >::with_right_apply_intermediates()
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::withStantonIntermediatesUCCSD(bool const &v)
bool & sisi4s::SimilarityTransformedHamiltonian< F >::withStantonIntermediatesUCCSD()
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::withRingCCSDT(bool const &v)
bool & sisi4s::SimilarityTransformedHamiltonian< F >::withRingCCSDT()
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::withCISD(bool const &v)
bool & sisi4s::SimilarityTransformedHamiltonian< F >::withCISD()
SimilarityTransformedHamiltonian & sisi4s::SimilarityTransformedHamiltonian< F >::withCIS(bool const &v)
bool & sisi4s::SimilarityTransformedHamiltonian< F >::withCIS()
std::shared_ptr< StantonIntermediatesUCCSD< F > > SimilarityTransformedHamiltonian::getStantonIntermediatesUCCSD()