sisi4s::MpiCommunicator
int sisi4s::MpiCommunicator::rank
Referenced by gather, getRank.
int sisi4s::MpiCommunicator::processes
Referenced by gather, getProcesses.
MPI_Comm sisi4s::MpiCommunicator::comm
Referenced by allReduce, barrier, gather, reduce.
sisi4s::MpiCommunicator::MpiCommunicator(int rank_, int processes_, MPI_Comm comm_=MPI_COMM_WORLD)
sisi4s::MpiCommunicator::MpiCommunicator(const CTF::World &world)
sisi4s::MpiCommunicator::~MpiCommunicator()
void sisi4s::MpiCommunicator::barrier()
References comm.
Referenced by sisi4s::FiniteSizeCorrection::interpolation3D.
void sisi4s::MpiCommunicator::reduce(const F &src, F &dst, int rootRank=0)
References comm.
Referenced by sisi4s::Sisi4s::printStatistics.
void sisi4s::MpiCommunicator::allReduce(const F &src, F &dst)
References comm.
Referenced by sisi4s::FiniteSizeCorrection::interpolation3D.
void sisi4s::MpiCommunicator::gather(const std::vector< F > &src, std::vector< F > &dst, int rootRank=0)
\Brief Gathers the src vectors of all ranks together to the dst vector at the given root rank, by default rank 0.
References comm, processes, rank.
Referenced by sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::IPCcsdPreconditioner< F >::getInitialBasis, sisi4s::EACcsdPreconditioner< F >::getInitialBasis.
int sisi4s::MpiCommunicator::getRank() const
References rank.
Referenced by sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::IPCcsdPreconditioner< F >::getInitialBasis, sisi4s::EACcsdPreconditioner< F >::getInitialBasis.
int sisi4s::MpiCommunicator::getProcesses() const
References processes.