sisi4s::Time
constexpr int64_t sisi4s::Time::FRACTIONS
Referenced by getFractionalSeconds, sisi4s::operator*, operator+=, operator-=, sisi4s::LogStream::prepare.
constexpr int sisi4s::Time::FRACTION_DIGITS
Referenced by sisi4s::operator<<.
sisi4s::Time::Time()
sisi4s::Time::Time(int64_t seconds, int64_t nanoSeconds)
sisi4s::Time::Time(Time const &t)
int64_t sisi4s::Time::getSeconds() const
Referenced by sisi4s::operator<<, sisi4s::LogStream::prepare.
int64_t sisi4s::Time::getFractions() const
Referenced by sisi4s::operator<<, sisi4s::LogStream::prepare.
double sisi4s::Time::getFractionalSeconds() const
References FRACTIONS.
Referenced by sisi4s::operator*, sisi4s::ParenthesisTriples::run, sisi4s::Sisi4s::run.
Time & sisi4s::Time::operator+=(Time const &t)
References FRACTIONS.
Time & sisi4s::Time::operator-=(Time const &t)
References FRACTIONS.
static Time sisi4s::Time::getCurrentRealTime()
Referenced by sisi4s::Timer::~Timer, sisi4s::LogStream::prepare, sisi4s::CcsdPerturbativeTriples::run.