ghc::filesystem::directory_entry
friend class directory_iterator
filesystem::path ghc::filesystem::directory_entry::_path
file_status ghc::filesystem::directory_entry::_status
file_status ghc::filesystem::directory_entry::_symlink_status
uintmax_t ghc::filesystem::directory_entry::_file_size
uintmax_t ghc::filesystem::directory_entry::_hard_link_count
time_t ghc::filesystem::directory_entry::_last_write_time
ghc::filesystem::directory_entry::directory_entry() noexcept=default
ghc::filesystem::directory_entry::directory_entry(const directory_entry &)=default
ghc::filesystem::directory_entry::directory_entry(directory_entry &&) noexcept=default
ghc::filesystem::directory_entry::directory_entry(const path &p, std::error_code &ec)
References refresh.
ghc::filesystem::directory_entry::~directory_entry()
directory_entry & ghc::filesystem::directory_entry::operator=(const directory_entry &)=default
directory_entry & ghc::filesystem::directory_entry::operator=(directory_entry &&) noexcept=default
References ghc::filesystem::exists, ghc::filesystem::file_size, ghc::filesystem::hard_link_count, ghc::filesystem::is_block_file, ghc::filesystem::is_character_file, ghc::filesystem::is_directory, ghc::filesystem::is_fifo, ghc::filesystem::is_other, ghc::filesystem::is_regular_file, ghc::filesystem::is_socket, ghc::filesystem::is_symlink, ghc::filesystem::last_write_time, ghc::filesystem::operator!=, ghc::filesystem::operator<, ghc::filesystem::operator<=, ghc::filesystem::operator==, ghc::filesystem::operator>, ghc::filesystem::operator>=, ghc::filesystem::status, ghc::filesystem::symlink_status.
void ghc::filesystem::directory_entry::assign(const path &p, std::error_code &ec)
References refresh.
void ghc::filesystem::directory_entry::replace_filename(const path &p, std::error_code &ec)
References refresh.
void ghc::filesystem::directory_entry::refresh(std::error_code &ec) noexcept
References ghc::filesystem::detail::status_ex.
Referenced by directory_entry, assign, replace_filename.
const filesystem::path & ghc::filesystem::directory_entry::path() const noexcept
ghc::filesystem::directory_entry::operator const filesystem::path &() const noexcept
bool ghc::filesystem::directory_entry::exists(std::error_code &ec) const noexcept
References ghc::filesystem::not_found.
bool ghc::filesystem::directory_entry::is_block_file(std::error_code &ec) const noexcept
References ghc::filesystem::block.
bool ghc::filesystem::directory_entry::is_character_file(std::error_code &ec) const noexcept
References ghc::filesystem::character.
bool ghc::filesystem::directory_entry::is_directory(std::error_code &ec) const noexcept
References ghc::filesystem::directory.
bool ghc::filesystem::directory_entry::is_fifo(std::error_code &ec) const noexcept
References ghc::filesystem::fifo.
bool ghc::filesystem::directory_entry::is_other(std::error_code &ec) const noexcept
References ghc::filesystem::directory, ghc::filesystem::is_symlink, ghc::filesystem::none, ghc::filesystem::not_found, ghc::filesystem::regular.
bool ghc::filesystem::directory_entry::is_regular_file(std::error_code &ec) const noexcept
References ghc::filesystem::regular.
bool ghc::filesystem::directory_entry::is_socket(std::error_code &ec) const noexcept
References ghc::filesystem::socket.
bool ghc::filesystem::directory_entry::is_symlink(std::error_code &ec) const noexcept
References ghc::filesystem::is_symlink, ghc::filesystem::none, ghc::filesystem::symlink, ghc::filesystem::symlink_status.
Referenced by ghc::filesystem::recursive_directory_iterator::increment.
uintmax_t ghc::filesystem::directory_entry::file_size(std::error_code &ec) const noexcept
References ghc::filesystem::file_size.
file_time_type ghc::filesystem::directory_entry::last_write_time(std::error_code &ec) const noexcept
References ghc::filesystem::last_write_time.
file_status ghc::filesystem::directory_entry::status(std::error_code &ec) const noexcept
References ghc::filesystem::none, ghc::filesystem::status, ghc::filesystem::unknown.
file_status ghc::filesystem::directory_entry::symlink_status(std::error_code &ec) const noexcept
References ghc::filesystem::none, ghc::filesystem::symlink_status, ghc::filesystem::unknown.
uintmax_t ghc::filesystem::directory_entry::hard_link_count(std::error_code &ec) const noexcept
References ghc::filesystem::hard_link_count.
bool ghc::filesystem::directory_entry::operator<(const directory_entry &rhs) const noexcept
bool ghc::filesystem::directory_entry::operator==(const directory_entry &rhs) const noexcept
bool ghc::filesystem::directory_entry::operator!=(const directory_entry &rhs) const noexcept
bool ghc::filesystem::directory_entry::operator<=(const directory_entry &rhs) const noexcept
bool ghc::filesystem::directory_entry::operator>(const directory_entry &rhs) const noexcept
bool ghc::filesystem::directory_entry::operator>=(const directory_entry &rhs) const noexcept
file_type ghc::filesystem::directory_entry::status_file_type(std::error_code &ec) const noexcept