sisi4s::Inter1D
int sisi4s::Inter1D< F >::N
Referenced by sisi4s::Inter1D< F >::Inter1D, sisi4s::Inter1D< F >::cubicSpline, sisi4s::Inter1D< F >::getValue.
F* sisi4s::Inter1D< F >::xv
Referenced by sisi4s::Inter1D< F >::Inter1D, sisi4s::Inter1D< F >::cubicSpline, sisi4s::Inter1D< F >::getValue.
F * sisi4s::Inter1D< F >::yv
Referenced by sisi4s::Inter1D< F >::Inter1D, sisi4s::Inter1D< F >::cubicSpline, sisi4s::Inter1D< F >::getValue.
F * sisi4s::Inter1D< F >::y2d
Referenced by sisi4s::Inter1D< F >::Inter1D, sisi4s::Inter1D< F >::cubicSpline, sisi4s::Inter1D< F >::getValue.
sisi4s::Inter1D< F >::Inter1D(const int size, F *x, F *y)
References am::F, sisi4s::Inter1D< F >::N, sisi4s::Inter1D< F >::xv, sisi4s::Inter1D< F >::y2d, sisi4s::Inter1D< F >::yv.
void sisi4s::Inter1D< F >::cubicSpline(F y1d0=0., F y1dn=0., const std::string boundaryCondition="M")
References LOG, sisi4s::Inter1D< F >::N, sisi4s::Inter1D< F >::xv, sisi4s::Inter1D< F >::y2d, sisi4s::Inter1D< F >::yv.
Referenced by sisi4s::FiniteSizeCorrection::calculateFiniteSizeCorrection.
F sisi4s::Inter1D< F >::getValue(F xinterp)
References sisi4s::abs, LOG, sisi4s::Inter1D< F >::N, sisi4s::Inter1D< F >::xv, sisi4s::Inter1D< F >::y2d, sisi4s::Inter1D< F >::yv.
Referenced by sisi4s::FiniteSizeCorrection::calculateFiniteSizeCorrection, sisi4s::FiniteSizeCorrection::SGxVG.