sisi4s::ClusterSinglesDoublesAlgorithm
int constexpr sisi4s::ClusterSinglesDoublesAlgorithm::DEFAULT_MAX_ITERATIONS
Defines the default number of iterations (16).
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run.
double constexpr sisi4s::ClusterSinglesDoublesAlgorithm::DEFAULT_ENERGY_CONVERGENCE
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run.
double constexpr sisi4s::ClusterSinglesDoublesAlgorithm::DEFAULT_AMPLITUDES_CONVERGENCE
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run.
double constexpr sisi4s::ClusterSinglesDoublesAlgorithm::DEFAULT_LEVEL_SHIFT
Referenced by estimateAmplitudesFromResiduum.
ClusterSinglesDoublesAlgorithm::ClusterSinglesDoublesAlgorithm(std::vector< Argument > const &argumentList)
ClusterSinglesDoublesAlgorithm::~ClusterSinglesDoublesAlgorithm()
void ClusterSinglesDoublesAlgorithm::run()
Calculates the energy of a ClusterSinglesDoubles algorithm.
References sisi4s::Algorithm::getArgumentData, getDataName, sisi4s::Algorithm::setRealArgument.
Referenced by sisi4s::UccsdAmplitudesFromCoulombIntegrals::run.
virtual std::string sisi4s::ClusterSinglesDoublesAlgorithm::getAbbreviation()=0
Returns the abbreviation of the concrete algorithm, e.g. "Ccd", "Dcd".
Referenced by getCapitalizedAbbreviation, getDataName.
F ClusterSinglesDoublesAlgorithm::run()
References DEFAULT_AMPLITUDES_CONVERGENCE, DEFAULT_ENERGY_CONVERGENCE, DEFAULT_MAX_ITERATIONS, EMIT, estimateAmplitudesFromResiduum, EXCEPTION, getCapitalizedAbbreviation, getEnergy, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, getResiduum, sisi4s::Algorithm::getTextArgument, sisi4s::Algorithm::isArgumentGiven, LOG, NEW, PTR, storeAmplitudes.
virtual std::shared_ptr< FockVector< double > > sisi4s::ClusterSinglesDoublesAlgorithm::getResiduum(const int iteration, const std::shared_ptr< const FockVector< double > > &amplitudes)=0
Computes and returns the residuum of the given amplitudes.
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run.
virtual std::shared_ptr< FockVector< complex > > sisi4s::ClusterSinglesDoublesAlgorithm::getResiduum(const int iteration, const std::shared_ptr< const FockVector< complex > > &amplitudes)=0
Computes and returns the residuum of the given amplitudes.
F ClusterSinglesDoublesAlgorithm::getEnergy(const std::shared_ptr< const FockVector< F > > &amplitdues)
Computes and returns the energy of the given amplitudes.
References EMIT, sisi4s::FockVector< F >::get, getCapitalizedAbbreviation, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::isArgumentGiven, LOG, NEW, PTR, sisi4s::Sisi4s::world.
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run.
template void ClusterSinglesDoublesAlgorithm::estimateAmplitudesFromResiduum(const std::shared_ptr< FockVector< F > > &residuum, const std::shared_ptr< const FockVector< F > > &amplitudes)
Calculates an improved estimate of the amplitudes provided the given the residuum. $T_{ij\ldots}^{ab\ldots} = \frac{R_{ij\ldots}^{a\ldots}} {-\Delta_{ij\ldots}^{ab\ldots}}$ with $\Delta_{ij\ldots}^{ab\ldots} = \varepsilon_i+\ldots-\varepsilon_a-\ldots$.
residuum Fock vector, overwritten with new amplitudes. amplitudes Fock vector, previous amplitudes
References calculateExcitationEnergies, sisi4s::FockVector< F >::component_tensors, DEFAULT_LEVEL_SHIFT, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_indices, sisi4s::Algorithm::getRealArgument.
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run.
template void ClusterSinglesDoublesAlgorithm::calculateExcitationEnergies(Tensor< F > &D, const std::string &indices)
Calculates eps_a+eps_b+...-eps_i-eps_j-... into D^ab..._ij...
References sisi4s::toComplexTensor.
Referenced by estimateAmplitudesFromResiduum.
template void ClusterSinglesDoublesAlgorithm::dryAmplitudesFromResiduum(sisi4s::DryTensor< F > &R)
Dry run for amplitudesFromResiduum.
R residuum tensor.
References SOURCE_LOCATION.
template std::shared_ptr< FockVector< sisi4s::Complex64 > > ClusterSinglesDoublesAlgorithm::createAmplitudes(std::vector< std::string > amplitudeNames, std::vector< std::vector< TensorIndex > > amplitudeLens, std::vector< std::string > amplitudeIndices)
References EMIT, sisi4s::Algorithm::isArgumentGiven, NEW, PTR, sisi4s::Sisi4s::world.
void ClusterSinglesDoublesAlgorithm::storeAmplitudes(const std::shared_ptr< const FockVector< F > > &amplitudes, std::vector< std::string > names)
References sisi4s::FockVector< F >::get, getDataName, sisi4s::Algorithm::isArgumentGiven.
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run.
Tensor< double > * ClusterSinglesDoublesAlgorithm::sliceCoupledCoulombIntegrals(const std::shared_ptr< const FockVector< double > > &amplitudes, int a, int b, int integralsSliceSize)
Calculates and returns one slice Xxycd of the Coulomb integrals $V_{cd}^{ab}$ coupled to the singles amplitudes. The indices x and y are restricted to the range {No+a, ..., No+a+No-1} and {No+b, ..., No+b+No-1}, respectively. The caller is responsible for deleting the dynamically allocated result tensor.
a 1st sliced dimension (x). b 2nd sliced dimension (y). integralsSliceSize slicing rank. Xxycd sliced coupled Coulomb integrals Xabcd
References sisi4s::fromComplexTensor, sisi4s::FockVector< F >::get, sisi4s::toComplexTensor.
Tensor< complex > * sisi4s::ClusterSinglesDoublesAlgorithm::sliceCoupledCoulombIntegrals(const std::shared_ptr< const FockVector< complex > > &amplitudes, int a, int b, int integralsSliceSize)
Tensor< double > * ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors(const std::shared_ptr< const FockVector< double > > &amplitudes, int a, int b, int factorsSliceSize)
Calculates and returns one slice Fabij of the residuum from the dressed Coulomb factors. The slice is computed from Rx and Ry and are restricted to the range {a, ..., factorsSliceSize+a-1} and {b, ..., factorsSliceSize+b-1}, respectively. The caller is responsible for deleting the dynamically allocated result tensor.
a 1st sliced dimension (Rx). b 2nd sliced dimension (Ry). factorsSliceSize slicing rank of NR. Fabij sliced Residuum
References sisi4s::fromComplexTensor, sisi4s::FockVector< F >::get, sisi4s::Algorithm::getTensorArgument, sisi4s::toComplexTensor.
Referenced by sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum.
Tensor< sisi4s::complex > * ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors(const std::shared_ptr< const FockVector< complex > > &amplitudes, int a, int b, int factorsSliceSize)
References sisi4s::FockVector< F >::get, sisi4s::Algorithm::getTensorArgument.
template void ClusterSinglesDoublesAlgorithm::sliceIntoResiduum(Tensor< F > &Rxyij, int a0, int b0, Tensor< F > &Rabij)
Adds the given slice of the residuum tensor Rxyij to the entire residuum tensor Rabij at the respective index range.
a0 1st sliced dimension (x). b0 2nd sliced dimension (y). Rxyij sliced residuum Rabij entire residuum.
Referenced by sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum.
std::string ClusterSinglesDoublesAlgorithm::getCapitalizedAbbreviation()
The abbreviation of the algorithm in capital letters.
References getAbbreviation.
Referenced by getEnergy, sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum, sisi4s::CcsdEnergyFromCoulombIntegralsReference::getResiduum, sisi4s::DrccdEnergyFromCoulombIntegrals::getResiduum, sisi4s::CcsdtEnergyFromCoulombIntegrals::getResiduumTemplate, run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run.
std::string ClusterSinglesDoublesAlgorithm::getDataName(const std::string &type, const std::string &data)
References getAbbreviation.
Referenced by run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run, storeAmplitudes.