sisi4s::AlgorithmFactory
using sisi4s::AlgorithmFactory::AlgorithmMap = std::map<std::string, std::function<Algorithm *(std::vector<Argument> const &)> >
AlgorithmFactory::AlgorithmMap * AlgorithmFactory::algorithmMap
Referenced by getAlgorithmMap, getAlgorithmNames.
static Algorithm * sisi4s::AlgorithmFactory::create(std::string const &name, std::vector< Argument > const &arguments)
Creates an algorithm object of the algorithm type specified by the given name. The given arguments are passed to the algorithm constructor. The instantiated algorithm must be registered using the AlgorithmRegistrar class.
References getAlgorithmMap.
static std::vector< std::string > sisi4s::AlgorithmFactory::getAlgorithmNames()
References algorithmMap.
Referenced by main.
static AlgorithmMap * sisi4s::AlgorithmFactory::getAlgorithmMap()
References algorithmMap.
Referenced by sisi4s::AlgorithmRegistrar< AlgorithmType >::AlgorithmRegistrar, create.