sisi4s::CoulombVertexReader
sisi4s::AlgorithmRegistrar< CoulombVertexReader > CoulombVertexReader::registrar_
virtual std::string sisi4s::CoulombVertexReader::getName()
CoulombVertexReader::CoulombVertexReader(std::vector< Argument > const &argumentList)
CoulombVertexReader::~CoulombVertexReader()
void CoulombVertexReader::run()
Reads the Full Coulomb Vertex $\Gamma_{pG}^q$ and the occupied and virtual orbital energies $\varepsilon_i, \varepsilon_a$ from binary data file, and stores them in the CTF Tensors GammaGqr, epsi, epsa.
References sisi4s::Algorithm::allocatedTensorArgument, sisi4s::CoulombVertexReader::Chunk::EPSILONS_MAGIC, EXCEPTION, sisi4s::Algorithm::getTextArgument, handleUnrestricted, sisi4s::CoulombVertexReader::Chunk::IMAGS_MAGIC, LOG, sisi4s::CoulombVertexReader::Header::magic, sisi4s::CoulombVertexReader::Header::MAGIC, sisi4s::CoulombVertexReader::Chunk::magic, sisi4s::CoulombVertexReader::Header::NG, sisi4s::CoulombVertexReader::Header::No, sisi4s::CoulombVertexReader::Header::Nv, sisi4s::CoulombVertexReader::Chunk::REALS_MAGIC, sisi4s::CoulombVertexReader::Chunk::size, sisi4s::toComplexTensor, sisi4s::Sisi4s::world.
void CoulombVertexReader::dryRun()
Dry run for reading the Coulomb vertex from binary data file.
References sisi4s::Algorithm::allocatedTensorArgument, EXCEPTION, sisi4s::Algorithm::getTextArgument, LOG, sisi4s::CoulombVertexReader::Header::magic, sisi4s::CoulombVertexReader::Header::MAGIC, sisi4s::CoulombVertexReader::Header::NG, sisi4s::CoulombVertexReader::Header::No, sisi4s::CoulombVertexReader::Header::Nv, SOURCE_LOCATION.
void CoulombVertexReader::handleUnrestricted()
References sisi4s::Algorithm::getIntegerArgument, unrestrictEigenEnergies, unrestrictVertex.
Referenced by run.
void CoulombVertexReader::unrestrictVertex()
References sisi4s::Sisi4s::world.
Referenced by handleUnrestricted.
void CoulombVertexReader::unrestrictEigenEnergies(const std::string &name)
References sisi4s::Algorithm::getTensorArgument, sisi4s::Sisi4s::world.
Referenced by handleUnrestricted.