sisi4s::FiniteSizeCorrection
sisi4s::AlgorithmRegistrar< FiniteSizeCorrection > FiniteSizeCorrection::registrar_
int sisi4s::FiniteSizeCorrection::NG
Referenced by calculateComplexStructureFactor, calculateFiniteSizeCorrection, calculateRealStructureFactor, dryCalculateStructureFactor, interpolation3D, readFromFile.
std::vector<double> sisi4s::FiniteSizeCorrection::GLengths
Referenced by calculateFiniteSizeCorrection, interpolation3D.
std::vector<double> sisi4s::FiniteSizeCorrection::averageSGs
Referenced by calculateFiniteSizeCorrection, interpolation3D.
std::vector<double> sisi4s::FiniteSizeCorrection::meanErrorSG
Referenced by interpolation3D.
std::vector<double> sisi4s::FiniteSizeCorrection::structureFactors
Referenced by calculateComplexStructureFactor, calculateRealStructureFactor, interpolation3D, readFromFile.
std::vector<double> sisi4s::FiniteSizeCorrection::VofG
Referenced by calculateComplexStructureFactor, calculateRealStructureFactor, interpolation3D, readFromFile.
double sisi4s::FiniteSizeCorrection::GC
Referenced by calculateFiniteSizeCorrection, interpolation3D, SGxVG.
double sisi4s::FiniteSizeCorrection::inter3D
Referenced by calculateFiniteSizeCorrection, interpolation3D.
double sisi4s::FiniteSizeCorrection::sum3D
Referenced by calculateFiniteSizeCorrection, interpolation3D.
Momentum* sisi4s::FiniteSizeCorrection::fibonacciGrid
Referenced by constructFibonacciGrid, interpolation3D.
Momentum* sisi4s::FiniteSizeCorrection::cartesianGrid
Referenced by calculateFiniteSizeCorrection, interpolation3D.
constexpr int sisi4s::FiniteSizeCorrection::DEFAULT_NUM_FIBONACCI
Referenced by interpolation3D.
virtual std::string sisi4s::FiniteSizeCorrection::getName()
FiniteSizeCorrection::FiniteSizeCorrection(std::vector< Argument > const &argumentList)
FiniteSizeCorrection::~FiniteSizeCorrection()
void FiniteSizeCorrection::run()
Calculates the finite size correction.
References calculateComplexStructureFactor, calculateFiniteSizeCorrection, calculateRealStructureFactor, sisi4s::Algorithm::getArgumentData, sisi4s::Algorithm::getIntegerArgument, interpolation3D, LOG, readFromFile.
void FiniteSizeCorrection::dryRun()
Performs a Dry Run.
References dryCalculateFiniteSizeCorrection, dryCalculateStructureFactor, dryInterpolation3D, sisi4s::Algorithm::getIntegerArgument, LOG.
void FiniteSizeCorrection::readFromFile()
References LOG, NG, structureFactors, VofG.
Referenced by run.
void FiniteSizeCorrection::calculateRealStructureFactor()
References EXCEPTION, sisi4s::fromComplexTensor, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getTensorArgument, sisi4s::Algorithm::isArgumentGiven, LOG, NEW, NG, PTR, structureFactors, sisi4s::toComplexTensor, VofG, sisi4s::Sisi4s::world.
Referenced by run.
void FiniteSizeCorrection::calculateComplexStructureFactor()
References sisi4s::fromComplexTensor, sisi4s::Algorithm::isArgumentGiven, NG, structureFactors, sisi4s::toComplexTensor, VofG.
Referenced by run.
void FiniteSizeCorrection::constructFibonacciGrid(double R, int N)
References fibonacciGrid, sisi4s::FiniteSizeCorrection::Momentum::v.
Referenced by interpolation3D.
void FiniteSizeCorrection::interpolation3D()
References sisi4s::abs, sisi4s::MpiCommunicator::allReduce, averageSGs, sisi4s::MpiCommunicator::barrier, cartesianGrid, constructFibonacciGrid, sisi4s::Vector< F, D >::cross, DEFAULT_NUM_FIBONACCI, sisi4s::dot, sisi4s::Vector< F, D >::dot, fibonacciGrid, GC, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, GLengths, inter3D, sisi4s::Algorithm::isArgumentGiven, IsInSmallBZ, sisi4s::FiniteSizeCorrection::Momentum::l, sisi4s::Vector< F, D >::length, LOG, meanErrorSG, NG, sisi4s::FiniteSizeCorrection::Momentum::s, sisi4s::FiniteSizeCorrection::Momentum::sortByLength, structureFactors, sum3D, sisi4s::FiniteSizeCorrection::Momentum::v, VofG, sisi4s::Sisi4s::world.
Referenced by run.
bool FiniteSizeCorrection::IsInSmallBZ(Vector< double > point, double scale, std::vector< sisi4s::Vector< double > > smallBZ)
References sisi4s::abs, sisi4s::dot.
Referenced by interpolation3D.
double FiniteSizeCorrection::SGxVG(sisi4s::Inter1D< double > Int1d, double x)
References GC, sisi4s::Inter1D< F >::getValue.
Referenced by simpson.
double FiniteSizeCorrection::integrate(sisi4s::Inter1D< double > Int1d, double start, double end, int steps)
Referenced by calculateFiniteSizeCorrection.
double FiniteSizeCorrection::simpson(sisi4s::Inter1D< double > Int1d, double x, double h)
References SGxVG.
void FiniteSizeCorrection::calculateFiniteSizeCorrection()
References averageSGs, cartesianGrid, sisi4s::Inter1D< F >::cubicSpline, GC, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, sisi4s::Inter1D< F >::getValue, GLengths, integrate, inter3D, LOG, NG, sisi4s::FiniteSizeCorrection::Momentum::s, sisi4s::Algorithm::setRealArgument, sum3D, sisi4s::FiniteSizeCorrection::Momentum::vg.
Referenced by run.
void FiniteSizeCorrection::dryCalculateStructureFactor()
References sisi4s::Algorithm::allocatedTensorArgument, sisi4s::Algorithm::getTensorArgument, sisi4s::Algorithm::isArgumentGiven, sisi4s::DryTensor< F >::lens, NG, SOURCE_LOCATION.
Referenced by dryRun.
void FiniteSizeCorrection::dryInterpolation3D()
Referenced by dryRun.
void FiniteSizeCorrection::dryCalculateFiniteSizeCorrection()
References sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, sisi4s::Algorithm::setRealArgument.
Referenced by dryRun.
void sisi4s::FiniteSizeCorrection::extrapolation(double minG, double maxG, int basisSetExtrapolation)
double sisi4s::FiniteSizeCorrection::simplestWindow(double Gmin, double Gmax, double G)
double sisi4s::FiniteSizeCorrection::integrateSimplestWindow(double Gmin, double Gmax)
double sisi4s::FiniteSizeCorrection::leastSquareFit(std::vector< double > fitabsG, std::vector< double > fitSF)
void sisi4s::FiniteSizeCorrection::basisSetCompleteness()