sisi4s::CtfMachineTensor
typedef CtfMachineTensorFactory<F> sisi4s::CtfMachineTensor< F >::Factory
typedef Tensor<F> sisi4s::CtfMachineTensor< F >::Tensor
Tensor sisi4s::CtfMachineTensor< F >::tensor
The adapted CTF tensor.
Referenced by sisi4s::CtfMachineTensor< F >::contract, sisi4s::CtfMachineTensor< F >::contract, sisi4s::CtfMachineTensor< F >::getLens, sisi4s::CtfMachineTensor< F >::getName, sisi4s::CtfMachineTensor< F >::move, sisi4s::CtfMachineTensor< F >::move.
friend class CtfMachineTensorFactory< F >
sisi4s::CtfMachineTensor< F >::CtfMachineTensor(const std::vector< int > &lens, const std::string &name, CTF::World *world, const ProtectedToken &)
sisi4s::CtfMachineTensor< F >::CtfMachineTensor(const Tensor &T, const ProtectedToken &)
virtual sisi4s::CtfMachineTensor< F >::~CtfMachineTensor()
virtual void sisi4s::CtfMachineTensor< F >::move(F alpha, const std::shared_ptr< tcc::MachineTensor< F > > &A, const std::string &aIndices, F beta, const std::string &bIndices)
References EXCEPTION, sisi4s::CtfMachineTensor< F >::getName, LOG, sisi4s::CtfMachineTensor< F >::tensor.
void sisi4s::CtfMachineTensor< F >::move(F alpha, const std::shared_ptr< tcc::MachineTensor< F > > &A, const std::string &aIndices, F beta, const std::string &bIndices, const std::function< F(const F)> &f)
References EXCEPTION, sisi4s::CtfMachineTensor< F >::getName, LOG, sisi4s::CtfMachineTensor< F >::tensor.
void sisi4s::CtfMachineTensor< F >::contract(F alpha, const std::shared_ptr< tcc::MachineTensor< F > > &A, const std::string &aIndices, const std::shared_ptr< tcc::MachineTensor< F > > &B, const std::string &bIndices, F beta, const std::string &cIndices)
References EXCEPTION, sisi4s::CtfMachineTensor< F >::getName, LOG, sisi4s::CtfMachineTensor< F >::tensor.
void sisi4s::CtfMachineTensor< F >::contract(F alpha, const std::shared_ptr< tcc::MachineTensor< F > > &A, const std::string &aIndices, const std::shared_ptr< tcc::MachineTensor< F > > &B, const std::string &bIndices, F beta, const std::string &cIndices, const std::function< F(const F, const F)> &g)
References EXCEPTION, sisi4s::CtfMachineTensor< F >::getName, LOG, sisi4s::CtfMachineTensor< F >::tensor.
virtual std::vector< int > sisi4s::CtfMachineTensor< F >::getLens() const
References sisi4s::CtfMachineTensor< F >::tensor.
virtual std::string sisi4s::CtfMachineTensor< F >::getName() const
References sisi4s::CtfMachineTensor< F >::tensor.
Referenced by sisi4s::CtfMachineTensor< F >::contract, sisi4s::CtfMachineTensor< F >::contract, sisi4s::CtfMachineTensor< F >::move, sisi4s::CtfMachineTensor< F >::move.
static std::shared_ptr< CtfMachineTensor< F > > sisi4s::CtfMachineTensor< F >::create(const Tensor &T)