sisi4s::LapackMatrix
int sisi4s::LapackMatrix< F >::rows
Number of rows and columns.
Referenced by sisi4s::LapackMatrix< F >::LapackMatrix, sisi4s::LapackMatrix< F >::getRows, sisi4s::LapackMatrix< F >::operator(), sisi4s::LapackMatrix< F >::operator(), sisi4s::LapackMatrix< F >::operator=, sisi4s::LapackMatrix< F >::write.
int sisi4s::LapackMatrix< F >::columns
Referenced by sisi4s::LapackMatrix< F >::LapackMatrix, sisi4s::LapackMatrix< F >::getColumns, sisi4s::LapackMatrix< F >::operator=, sisi4s::LapackMatrix< F >::write.
std::vector<F> sisi4s::LapackMatrix< F >::values
The column major data.
Referenced by sisi4s::LapackMatrix< F >::LapackMatrix, sisi4s::LapackMatrix< F >::getValues, sisi4s::LapackMatrix< F >::getValues, sisi4s::LapackMatrix< F >::operator(), sisi4s::LapackMatrix< F >::operator(), sisi4s::LapackMatrix< F >::operator=, sisi4s::LapackMatrix< F >::write.
sisi4s::LapackMatrix< F >::LapackMatrix(const LapackMatrix< F > &A)
Copies the content of the Lapack matrix.
sisi4s::LapackMatrix< F >::LapackMatrix(const int rows_, const int columns_)
Construct a zero nxm Lapack matrix.
sisi4s::LapackMatrix< F >::LapackMatrix(const int rows_, const int columns_, const std::vector< F > &values_)
Construct an nxm Lapack matrix from a given vector of values.
sisi4s::LapackMatrix< F >::LapackMatrix(Tensor< F > &ctfA, const int rows_=0, const int columns_=0)
Constructs an LapackMatrix from a CTF tensor on all ranks if rows and columns is given, reinterpret the matrix.
References sisi4s::LapackMatrix< F >::columns, sisi4s::LapackMatrix< F >::rows, sisi4s::LapackMatrix< F >::values.
LapackMatrix< F > & sisi4s::LapackMatrix< F >::operator=(const LapackMatrix< F > &A)
References sisi4s::LapackMatrix< F >::columns, sisi4s::LapackMatrix< F >::rows, sisi4s::LapackMatrix< F >::values.
const F & sisi4s::LapackMatrix< F >::operator()(const int i, const int j) const
References sisi4s::LapackMatrix< F >::rows, sisi4s::LapackMatrix< F >::values.
F & sisi4s::LapackMatrix< F >::operator()(const int i, const int j)
References sisi4s::LapackMatrix< F >::rows, sisi4s::LapackMatrix< F >::values.
int sisi4s::LapackMatrix< F >::getRows() const
References sisi4s::LapackMatrix< F >::rows.
Referenced by sisi4s::LapackGeneralEigenSystem< complex >::LapackGeneralEigenSystem, sisi4s::LapackInverse< Complex64 >::LapackInverse, sisi4s::LapackGeneralEigenSystem< complex >::leftEigenError, logOverlap, logVectorNorms, sisi4s::operator*, sisi4s::LapackGeneralEigenSystem< complex >::orderEigenVectors, sisi4s::LapackGeneralEigenSystem< complex >::rightEigenError.
int sisi4s::LapackMatrix< F >::getColumns() const
References sisi4s::LapackMatrix< F >::columns.
Referenced by sisi4s::LapackGeneralEigenSystem< complex >::LapackGeneralEigenSystem, sisi4s::LapackInverse< Complex64 >::LapackInverse, logOverlap, logVectorNorms, sisi4s::operator*, sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
const F * sisi4s::LapackMatrix< F >::getValues() const
Returns the pointer to the column major data.
References sisi4s::LapackMatrix< F >::values.
Referenced by sisi4s::LapackGeneralEigenSystem< complex >::LapackGeneralEigenSystem, sisi4s::NaturalTransitionOrbitalsFromRhoAI::buildTransformations.
F * sisi4s::LapackMatrix< F >::getValues()
Returns the pointer to the mutable column major data.
References sisi4s::LapackMatrix< F >::values.
void sisi4s::LapackMatrix< F >::write(Tensor< F > &ctfA) const
Writes the data of this Lapack matrix to the CTF tensor.
References sisi4s::LapackMatrix< F >::columns, EXCEPTION, sisi4s::LapackMatrix< F >::rows, sisi4s::LapackMatrix< F >::values.