sisi4s::Log
int Log::rank
Referenced by getRank, setRank.
std::string Log::fileName
Referenced by getFileName, getLogStream, setFileName.
int Log::logLevel
Referenced by getLogLevel, getLogStream, setLogLevel.
LogStream * Log::logStream
Referenced by getLogStream.
void Log::setRank(const int rank)
References rank.
Referenced by main.
int Log::getRank()
References rank.
void Log::setFileName(const std::string &fileName)
References fileName.
Referenced by main.
std::string Log::getFileName()
References fileName.
void Log::setLogLevel(const int logLevel)
References logLevel.
Referenced by main.
int Log::getLogLevel()
References logLevel.
LogStream & Log::getLogStream()
References fileName, logLevel, logStream.