CLI::Option
option_state
The option is currently collecting parsed results.
results_t CLI::Option::results_
complete Results of parsing
results_t CLI::Option::proc_results_
results after reduction
option_state CLI::Option::current_option_state_
Whether the callback has run (needed for INI parsing)
bool CLI::Option::allow_extra_args_
Specify that extra args beyond type_size_max should be allowed.
bool CLI::Option::flag_like_
Specify that the option should act like a flag vs regular option.
bool CLI::Option::run_callback_for_default_
Control option to run the callback to set the default.
bool CLI::Option::inject_separator_
flag indicating a separator needs to be injected after each argument call
bool CLI::Option::trigger_on_result_
flag indicating that the option should trigger the validation and callback chain on each result when loaded
bool CLI::Option::force_callback_
flag indicating that the option should force the callback regardless if any results present
std::vector<std::string> CLI::Option::snames_
A list of the short names (-a) without the leading dashes.
Referenced by matching_name.
std::vector<std::string> CLI::Option::lnames_
A list of the long names (--long) without the leading dashes.
Referenced by matching_name.
std::vector<std::pair<std::string, std::string> > CLI::Option::default_flag_values_
A list of the flag names with the appropriate default value, the first part of the pair should be duplicates of what is in snames or lnames but will trigger a particular response on a flag
std::vector<std::string> CLI::Option::fnames_
a list of flag names with specified default values;
std::string CLI::Option::pname_
A positional name.
std::string CLI::Option::envname_
If given, check the environment for this option.
Referenced by CLI::App::_process_env.
std::string CLI::Option::description_
The description for help strings.
std::string CLI::Option::default_str_
A human readable default value, either manually set, captured, or captured by default.
std::string CLI::Option::option_text_
If given, replace the text that describes the option type and usage in the help text.
std::function<std::string()> CLI::Option::type_name_
A human readable type value, set when App creates this This is a lambda function so "types" can be dynamic, such as when a set prints its contents.
std::function<std::string()> CLI::Option::default_function_
Run this function to capture a default (ignore if empty)
int CLI::Option::type_size_max_
The number of arguments that make up one option. max is the nominal type size, min is the minimum number of strings
int CLI::Option::type_size_min_
The minimum number of arguments an option should be expecting.
int CLI::Option::expected_min_
The minimum number of expected values.
int CLI::Option::expected_max_
The maximum number of expected values.
std::vector<Validator> CLI::Option::validators_
A list of Validators to run on each value parsed.
std::set<Option *> CLI::Option::needs_
A list of options that are required with this option.
Referenced by CLI::App::_process_requirements.
std::set<Option *> CLI::Option::excludes_
A list of options that are excluded with this option.
Referenced by CLI::App::_process_requirements, excludes.
App* CLI::Option::parent_
link back up to the parent App for fallthrough
callback_t CLI::Option::callback_
Options store a callback to do all the work.
CLI::Option::Option(const Option &)=delete
Option & CLI::Option::operator=(const Option &)=delete
std::size_t CLI::Option::count() const
Count the total number of times an option was passed.
Referenced by CLI::App::_count_remaining_positionals, CLI::App::_has_remaining_positionals, CLI::App::_parse_positional, CLI::App::_process_env, CLI::App::_process_help_flags, CLI::App::_process_requirements, CLI::App::count_all.
bool CLI::Option::empty() const
True if the option was not passed.
Referenced by CLI::App::_parse_single_config.
CLI::Option::operator bool() const
This bool operator returns true if any arguments were passed or the option callback is forced.
void CLI::Option::clear()
Clear the parsed results (mostly for testing)
Referenced by CLI::App::clear.
Option * CLI::Option::expected(int value)
Set the number of expected arguments.
References CLI::detail::expected_max_vector_size.
Referenced by CLI::App::add_option, CLI::App::add_option_function, CLI::App::add_option_no_stream, CLI::retire_option.
Option * CLI::Option::expected(int value_min, int value_max)
Set the range of expected arguments.
References CLI::detail::expected_max_vector_size.
Option * CLI::Option::allow_extra_args(bool value=true)
Set the value of allow_extra_args which allows extra value arguments on the flag or option to be included with each instance
Referenced by CLI::retire_option.
bool CLI::Option::get_allow_extra_args() const
Get the current value of allow extra args.
Referenced by CLI::App::_parse_positional, CLI::retire_option.
Option * CLI::Option::trigger_on_parse(bool value=true)
Set the value of trigger_on_parse which specifies that the option callback should be triggered on every parse.
bool CLI::Option::get_trigger_on_parse() const
The status of trigger on parse.
Option * CLI::Option::force_callback(bool value=true)
Set the value of force_callback.
bool CLI::Option::get_force_callback() const
The status of force_callback.
Option * CLI::Option::run_callback_for_default(bool value=true)
Set the value of run_callback_for_default which controls whether the callback function should be called to set the default This is controlled automatically but could be manipulated by the user.
Referenced by CLI::App::add_option, CLI::App::add_option_no_stream.
bool CLI::Option::get_run_callback_for_default() const
Get the current value of run_callback_for_default.
Referenced by CLI::ConfigBase::to_config.
Option * CLI::Option::check(Validator validator, const std::string &validator_name="")
Adds a Validator with a built in type name.
References CLI::Validator::name, CLI::Validator::non_modifying.
Referenced by CLI::deprecate_option.
Option * CLI::Option::check(std::function< std::string(const std::string &)> Validator, std::string Validator_description="", std::string Validator_name="")
Adds a Validator. Takes a const string& and returns an error message (empty if conversion/check is okay).
Option * CLI::Option::transform(Validator Validator, const std::string &Validator_name="")
Adds a transforming Validator with a built in type name.
Option * CLI::Option::transform(const std::function< std::string(std::string)> &func, std::string transform_description="", std::string transform_name="")
Adds a Validator-like function that can change result.
Option * CLI::Option::each(const std::function< void(std::string)> &func)
Adds a user supplied function to run on each item passed in (communicate though lambda capture)
Validator * CLI::Option::get_validator(const std::string &Validator_name="")
Get a named Validator.
References CLI::Validator::get_name.
Validator * CLI::Option::get_validator(int index)
Get a Validator by index NOTE: this may not be the order of definition.
Option * CLI::Option::needs(Option *opt)
Sets required options.
Option * CLI::Option::needs(std::string opt_name)
Can find a string if needed.
References CLI::IncorrectConstruction::MissingOption.
Option * CLI::Option::needs(A opt, B opt1, ARG... args)
Any number supported, any mix of string and Opt.
bool CLI::Option::remove_needs(Option *opt)
Remove needs link from an option. Returns true if the option really was in the needs list.
Option * CLI::Option::excludes(Option *opt)
Sets excluded options.
References excludes_.
Option * CLI::Option::excludes(std::string opt_name)
Can find a string if needed.
References CLI::IncorrectConstruction::MissingOption.
Option * CLI::Option::excludes(A opt, B opt1, ARG... args)
Any number supported, any mix of string and Opt.
bool CLI::Option::remove_excludes(Option *opt)
Remove needs link from an option. Returns true if the option really was in the needs list.
Option * CLI::Option::envname(std::string name)
Sets environment variable to read if no option given.
Option * CLI::Option::ignore_case(bool value=true)
Ignore case The template hides the fact that we don't have the definition of App yet. You are never expected to add an argument to the template here.
References matching_name.
Option * CLI::Option::ignore_underscore(bool value=true)
Ignore underscores in the option names The template hides the fact that we don't have the definition of App yet. You are never expected to add an argument to the template here.
References matching_name.
Option * CLI::Option::multi_option_policy(MultiOptionPolicy value=MultiOptionPolicy::Throw)
Take the last argument if given multiple times (or another policy)
References CLI::detail::expected_max_vector_size, CLI::Throw.
Option * CLI::Option::disable_flag_override(bool value=true)
Disable flag overrides values, e.g. flag= is not allowed.
int CLI::Option::get_type_size() const
The number of arguments the option expects.
Referenced by CLI::Formatter::make_option_opts.
int CLI::Option::get_type_size_min() const
The minimum number of arguments the option expects.
Referenced by CLI::retire_option.
int CLI::Option::get_type_size_max() const
The maximum number of arguments the option expects.
Referenced by CLI::retire_option.
int CLI::Option::get_inject_separator() const
Return the inject_separator flag.
std::string CLI::Option::get_envname() const
The environment variable associated to this value.
Referenced by CLI::Formatter::make_option_opts.
std::set< Option * > CLI::Option::get_needs() const
The set of options needed.
Referenced by CLI::Formatter::make_option_opts.
std::set< Option * > CLI::Option::get_excludes() const
The set of options excluded.
Referenced by CLI::Formatter::make_option_opts.
std::string CLI::Option::get_default_str() const
The default value (for help printing)
Referenced by CLI::Formatter::make_option_opts, CLI::ConfigBase::to_config.
callback_t CLI::Option::get_callback() const
Get the callback function.
const std::vector< std::string > & CLI::Option::get_lnames() const
Get the long names.
const std::vector< std::string > & CLI::Option::get_snames() const
Get the short names.
const std::vector< std::string > & CLI::Option::get_fnames() const
Get the flag names with specified default values.
const std::string & CLI::Option::get_single_name() const
Get a single name for the option, first of lname, pname, sname, envname.
Referenced by CLI::ConfigBase::to_config.
int CLI::Option::get_expected() const
The number of times the option expects to be included.
Referenced by CLI::Formatter::make_option_opts, CLI::Formatter::make_option_usage.
int CLI::Option::get_expected_min() const
The number of times the option expects to be included.
Referenced by CLI::App::_parse_single_config, CLI::Formatter::make_option_opts, CLI::retire_option, CLI::ConfigBase::to_config.
int CLI::Option::get_expected_max() const
The max number of times the option expects to be included.
Referenced by CLI::Formatter::make_option_opts, CLI::Formatter::make_option_usage, CLI::retire_option.
int CLI::Option::get_items_expected_min() const
The total min number of expected string values to be used.
Referenced by CLI::App::_count_remaining_positionals, CLI::App::_has_remaining_positionals, CLI::App::_parse_positional.
int CLI::Option::get_items_expected_max() const
Get the maximum number of items expected to be returned and used for the callback.
References CLI::detail::checked_multiply, CLI::detail::expected_max_vector_size.
int CLI::Option::get_items_expected() const
The total min number of expected string values to be used.
bool CLI::Option::get_positional() const
True if the argument can be given directly.
Referenced by CLI::App::_count_remaining_positionals, CLI::App::_has_remaining_positionals, CLI::App::_parse_positional, CLI::Formatter::make_positionals, CLI::Formatter::make_usage.
bool CLI::Option::nonpositional() const
True if option has at least one non-positional name.
Referenced by CLI::Formatter::make_groups, CLI::Formatter::make_usage.
bool CLI::Option::has_description() const
True if option has description.
Referenced by CLI::ConfigBase::to_config.
const std::string & CLI::Option::get_description() const
Get the description.
Referenced by CLI::deprecate_option, CLI::Formatter::make_option_desc, CLI::ConfigBase::to_config.
Option * CLI::Option::description(std::string option_description)
Set the description.
Referenced by CLI::deprecate_option.
Option * CLI::Option::option_text(std::string text)
const std::string & CLI::Option::get_option_text() const
Referenced by CLI::Formatter::make_option_opts.
std::string CLI::Option::get_name(bool positional=false, bool all_options=false) const
Show the positional name
References CLI::detail::join.
Referenced by CLI::App::_move_option, CLI::App::_process_requirements, CLI::deprecate_option, CLI::Formatter::make_option_name, CLI::retire_option, CLI::FailureMessage::simple.
void CLI::Option::run_callback()
Process the callback.
References CLI::Error::get_name.
Referenced by CLI::App::_parse_single_config, CLI::App::_process_callbacks.
const std::string & CLI::Option::matching_name(const Option &other) const
If options share any of the same names, find it.
References check_lname, check_sname, lnames_, snames_.
Referenced by ignore_case, ignore_underscore.
bool CLI::Option::operator==(const Option &other) const
If options share any of the same names, they are equal (not counting positional)
bool CLI::Option::check_name(const std::string &name) const
Check a name. Requires "-" or "--" for short / long, supports positional name.
References CLI::detail::remove_underscore, CLI::detail::to_lower.
Referenced by CLI::App::get_option_no_throw.
bool CLI::Option::check_sname(std::string name) const
Requires "-" to be removed from string.
References CLI::detail::find_member.
Referenced by matching_name.
bool CLI::Option::check_lname(std::string name) const
Requires "--" to be removed from string.
References CLI::detail::find_member.
Referenced by matching_name.
bool CLI::Option::check_fname(std::string name) const
Requires "--" to be removed from string.
References CLI::detail::find_member.
std::string CLI::Option::get_flag_value(const std::string &name, std::string input_value) const
Get the value that goes for a flag, nominally gets the default value but allows for overrides if not disabled
References CLI::detail::find_member, CLI::ArgumentMismatch::FlagOverride, CLI::detail::to_flag_value, CLI::detail::to_string.
Referenced by CLI::App::_parse_single_config.
Option * CLI::Option::add_result(std::string s)
Puts a result at the end.
Referenced by CLI::App::_parse_positional, CLI::App::_parse_single_config, CLI::App::_process_env.
Option * CLI::Option::add_result(std::string s, int &results_added)
Puts a result at the end and get a count of the number of arguments actually added.
Option * CLI::Option::add_result(std::vector< std::string > s)
Puts a result at the end.
References CLI::detail::str.
const results_t & CLI::Option::results() const
Get the current complete results set.
results_t CLI::Option::reduced_results() const
Get a copy of the results.
Referenced by CLI::ConfigBase::to_config.
void CLI::Option::results(T &output) const
Get the results as a specified type.
References CLI::Error::get_name.
T CLI::Option::as() const
Return the results as the specified type.
bool CLI::Option::get_callback_run() const
See if the callback has been run already.
Referenced by CLI::App::_process_callbacks.
Option * CLI::Option::type_name_fn(std::function< std::string()> typefun)
Set the type function to run when displayed on this option.
Option * CLI::Option::type_name(std::string typeval)
Set a custom option typestring.
Referenced by CLI::App::add_option, CLI::App::add_option_function, CLI::App::add_option_no_stream, CLI::retire_option.
Option * CLI::Option::type_size(int option_type_size)
Set a custom option size.
References CLI::detail::expected_max_vector_size.
Referenced by CLI::App::add_option, CLI::App::add_option_function, CLI::App::add_option_no_stream, CLI::retire_option.
Option * CLI::Option::type_size(int option_type_size_min, int option_type_size_max)
Set a custom option type size range.
References sisi4s::abs, CLI::detail::expected_max_vector_size.
void CLI::Option::inject_separator(bool value=true)
Set the value of the separator injection flag.
Option * CLI::Option::default_function(const std::function< std::string()> &func)
Set a capture function for the default. Mostly used by App.
Option * CLI::Option::capture_default_str()
Capture the default value from the original value (if it can be captured)
Option * CLI::Option::default_str(std::string val)
Set the default value string representation (does not change the contained value)
Referenced by CLI::retire_option.
Option * CLI::Option::default_val(const X &val)
Set the default value and validate the results and run the callback if appropriate to set the value into the bound value only available for types that can be converted to a string
References CLI::detail::to_string.
Referenced by sisi4s::Options::Options.
std::string CLI::Option::get_type_name() const
Get the full typename for this option.
References CLI::Validator::get_description.
Referenced by CLI::Formatter::make_option_opts.
void CLI::Option::_validate_results(results_t &res) const
Run the results through the Validators.
void CLI::Option::_reduce_results(results_t &res, const results_t &original) const
reduce the results in accordance with the MultiOptionPolicy res results are assigned to res if there if they are different
std::string CLI::Option::_validate(std::string &result, int index) const
int CLI::Option::_add_result(std::string &&result, std::vector< std::string > &res) const
Add a single result to the result set, taking into account delimiters.
friend CLI::Option::App
CLI::Option::Option(std::string option_name, std::string option_description, callback_t callback, App *parent)
Making an option by hand is not defined, it must be made by the App class.
References CLI::detail::get_names, CLI::detail::split_names.