sisi4s::LapackGeneralEigenSystem< complex >
sisi4s::LapackGeneralEigenSystem< complex >::L
std::vector<complex> sisi4s::LapackGeneralEigenSystem< complex >::lambdas
sisi4s::LapackGeneralEigenSystem< complex >::LapackGeneralEigenSystem(const LapackMatrix< complex > &A_, bool computeRightEigenvectors=true, bool computeLeftEigenvectors=false)
References EXCEPTION, sisi4s::LapackMatrix< F >::getColumns, sisi4s::LapackMatrix< F >::getRows, sisi4s::LapackMatrix< F >::getValues, zgeev_.
sisi4s::LapackGeneralEigenSystem< complex >::~LapackGeneralEigenSystem()
const std::vector< complex > & sisi4s::LapackGeneralEigenSystem< complex >::getEigenValues() const
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
const LapackMatrix< complex > & sisi4s::LapackGeneralEigenSystem< complex >::getRightEigenVectors() const
References EXCEPTION.
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
const LapackMatrix< complex > & sisi4s::LapackGeneralEigenSystem< complex >::getLeftEigenVectors() const
References EXCEPTION.
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
double sisi4s::LapackGeneralEigenSystem< complex >::rightEigenError(const LapackMatrix< complex > &A)
References sisi4s::conj, sisi4s::LapackMatrix< F >::getRows.
double sisi4s::LapackGeneralEigenSystem< complex >::leftEigenError(const LapackMatrix< complex > &A)
References sisi4s::conj, sisi4s::LapackMatrix< F >::getRows.
double sisi4s::LapackGeneralEigenSystem< complex >::biorthogonalError()
References sisi4s::conj.
sisi4s::LapackGeneralEigenSystem< complex >::PTR(LapackMatrix< complex >) R
void sisi4s::LapackGeneralEigenSystem< complex >::orderEigenVectors(const std::vector< std::pair< int, complex > > &sortedEigenValues, LapackMatrix< complex > &U)
References sisi4s::LapackMatrix< F >::getRows.