sisi4s::DryTensor
int sisi4s::DryTensor< F >::order
Referenced by sisi4s::dryComposeCanonicalPolyadicDecompositionTensors, sisi4s::dryContractWithCanonicalPolyadicDecompositionTensors, sisi4s::DryTensor< F >::getElementsCount.
std::vector<int> sisi4s::DryTensor< F >::lens
Referenced by sisi4s::DryIterativePseudoInverse< F >::DryIterativePseudoInverse, sisi4s::DryTensor< F >::DryTensor, sisi4s::FiniteSizeCorrection::dryCalculateStructureFactor, sisi4s::dryComposeCanonicalPolyadicDecompositionTensors, sisi4s::dryContractWithCanonicalPolyadicDecompositionTensors, sisi4s::ParticleHoleCoulombVertexDecomposition::dryEvaluateMp2, sisi4s::dryFitRegularizedAlternatingLeastSquaresFactor, sisi4s::ApproximateCoulombVertex::dryRun, sisi4s::ApproximateParticleHoleCoulombVertex::dryRun, sisi4s::CcsdPerturbativeTriples::dryRun, sisi4s::CcsdPerturbativeTriplesComplex::dryRun, sisi4s::CoulombIntegralsFromVertex::dryRun, sisi4s::CoulombVertexSingularVectors::dryRun, sisi4s::DoublesAmplitudesDecomposition::dryRun, sisi4s::DoublesAmplitudesFromVertex::dryRun, sisi4s::ParticleHoleCoulombVertexSingularVectors::dryRun, sisi4s::PerturbativeTriples::dryRun, sisi4s::SingleParticleOccupancies::dryRun, sisi4s::SliceCoulombVertex::dryRun, sisi4s::UPerturbativeTriples::dryRun, sisi4s::PerturbativeTriples::dryRunPiecuch, sisi4s::DryTensor< F >::getElementsCount.
std::vector<int> sisi4s::DryTensor< F >::syms
Referenced by sisi4s::DryTensor< F >::DryTensor, sisi4s::ParticleHoleCoulombVertexDecomposition::dryEvaluateMp2, sisi4s::DoublesAmplitudesFromVertex::dryRun.
SourceLocation sisi4s::DryTensor< F >::location
Referenced by sisi4s::DryTensor< F >::allocate.
std::string sisi4s::DryTensor< F >::name
Referenced by sisi4s::DryTensor< F >::get_name, sisi4s::DryTensor< F >::set_name.
int64_t sisi4s::DryTensor< F >::size
Referenced by sisi4s::DryTensor< F >::allocate, sisi4s::DryTensor< F >::free.
sisi4s::DryTensor< F >::DryTensor(int order_, int const *lens_, int const *syms_, SourceLocation const &location_=SourceLocation())
Creates a dry tensor for resource consumption estimation without actually allocating its data. Note that currently only the memory requirement of a DryTensor is estimated. The number of FLOPS should also be estimated in the future. Symmetryies are also ignored at the moment.
References sisi4s::DryTensor< F >::allocate, sisi4s::DryTensor< F >::lens, sisi4s::DryTensor< F >::syms.
sisi4s::DryTensor< F >::DryTensor(DryTensor const &A, SourceLocation const &location_=SourceLocation())
References sisi4s::DryTensor< F >::allocate.
virtual sisi4s::DryTensor< F >::~DryTensor()
References sisi4s::DryTensor< F >::free.
virtual void sisi4s::DryTensor< F >::use()
Referenced by sisi4s::ParticleHoleCoulombVertexDecomposition::dryEvaluateMp2, sisi4s::DoublesAmplitudesFromVertex::dryRun.
int64_t sisi4s::DryTensor< F >::getElementsCount() const
References sisi4s::DryTensor< F >::lens, sisi4s::DryTensor< F >::order.
Referenced by sisi4s::DryTensor< F >::allocate.
void sisi4s::DryTensor< F >::set_name(std::string const &name_)
References sisi4s::DryTensor< F >::name.
std::string const & sisi4s::DryTensor< F >::get_name() const
References sisi4s::DryTensor< F >::name.
Referenced by sisi4s::CoulombIntegralsFromVertex::dryRun.
void sisi4s::DryTensor< F >::allocate()
References sisi4s::DryMemory::allocate, am::F, sisi4s::DryTensor< F >::getElementsCount, sisi4s::DryTensor< F >::location, sisi4s::DryTensor< F >::size.
Referenced by sisi4s::DryTensor< F >::DryTensor.
void sisi4s::DryTensor< F >::free()
References sisi4s::DryMemory::free, sisi4s::DryTensor< F >::size.
Referenced by sisi4s::DryTensor< F >::~DryTensor.