sisi4s::Algorithm
std::string sisi4s::Algorithm::note
bool sisi4s::Algorithm::fallible
std::map<std::string, std::string> sisi4s::Algorithm::arguments
Referenced by Algorithm, getArgumentData, getGivenArgumentNames, isArgumentGiven.
Algorithm::Algorithm(std::vector< Argument > const &argumentList)
References arguments, sisi4s::Argument::getData, sisi4s::Argument::getName.
Algorithm::~Algorithm()
virtual std::string sisi4s::Algorithm::getName()=0
Referenced by dryRun.
virtual void sisi4s::Algorithm::run()=0
void Algorithm::dryRun()
The dryRun estimates resource consumption, especially memory and processor time.
References getName, LOG.
bool Algorithm::isArgumentGiven(std::string const &argumentName)
References arguments.
Referenced by sisi4s::CoulombVertexDecomposition::~CoulombVertexDecomposition, sisi4s::CoulombIntegralsFromVertex::calculateComplexIntegrals, sisi4s::FiniteSizeCorrection::calculateComplexStructureFactor, sisi4s::CoulombIntegralsFromVertex::calculateRealIntegrals, sisi4s::FiniteSizeCorrection::calculateRealStructureFactor, computeAndExport, computeAndExport, sisi4s::ClusterSinglesDoublesAlgorithm::createAmplitudes, sisi4s::CoulombIntegralsFromVertex::dryCalculateComplexIntegrals, sisi4s::CoulombIntegralsFromVertex::dryCalculateRealIntegrals, sisi4s::FiniteSizeCorrection::dryCalculateStructureFactor, sisi4s::CoulombVertexDecomposition::dryRun, sisi4s::ParticleHoleCoulombVertexDecomposition::dryRun, sisi4s::BasisSetExtrapolation::evaluateQGG, getBooleanArgument, sisi4s::ClusterSinglesDoublesAlgorithm::getEnergy, getIntegerArgument, getRealArgument, sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum, sisi4s::CcsdEnergyFromCoulombIntegralsReference::getResiduum, sisi4s::DrccdEnergyFromCoulombIntegrals::getResiduum, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumSth, sisi4s::UccsdAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UccsdtqAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UrpaAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::CcsdtEnergyFromCoulombIntegrals::getResiduumTemplate, getTextArgument, sisi4s::FiniteSizeCorrection::interpolation3D, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::ClusterSinglesDoublesAlgorithm::run, sisi4s::CoulombIntegralsFromGaussian::run, sisi4s::CoulombIntegralsFromVertex::run, sisi4s::CoulombVertexDecomposition::run, sisi4s::FcidumpReader::run, sisi4s::FcidumpWriter::run, sisi4s::FromComplexTensor::run, sisi4s::HartreeFockFromCoulombIntegrals::run, sisi4s::MeanCorrelationHoleDepth::run, sisi4s::MoReader::run, sisi4s::Mp2NaturalOrbitals::run, sisi4s::OneBodyRotation::run, sisi4s::ParenthesisTriples::run, sisi4s::ParticleHoleCoulombVertexDecomposition::run, sisi4s::PQRSCoulombIntegralsToVertex::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::ClusterSinglesDoublesAlgorithm::storeAmplitudes.
std::string Algorithm::getTextArgument(std::string const &argumentName)
References EMIT, EXCEPTION, getArgumentData, sisi4s::Data::getTypeName, sisi4s::TextData::value.
Referenced by sisi4s::CoulombVertexDecomposition::computeOutgoingPi, sisi4s::CoulombVertexDecomposition::dryRun, sisi4s::CoulombVertexReader::dryRun, sisi4s::ParticleHoleCoulombVertexReader::dryRun, getBooleanArgument, getTextArgument, sisi4s::ParenthesisTriples::getVpppijkOnTheFly, sisi4s::CoulombVertexDecomposition::iterateQuadraticFactor, sisi4s::TensorReader::read, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::ClusterSinglesDoublesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run, sisi4s::ComplexTensorContraction::run, sisi4s::ComplexTensorReader::run, sisi4s::ComplexTensorSum::run, sisi4s::ComplexTensorWriter::run, sisi4s::CoulombIntegralsFromGaussian::run, sisi4s::CoulombIntegralsFromRotatedCoulombIntegrals::run, sisi4s::CoulombVertexDecomposition::run, sisi4s::CoulombVertexReader::run, sisi4s::FcidumpReader::run, sisi4s::FcidumpWriter::run, sisi4s::GenerateRandomComplexMatrix::run, sisi4s::GenerateRandomMatrix::run, sisi4s::HartreeFockFromGaussian::run, sisi4s::MoReader::run, sisi4s::NuclearRepulsionEnergy::run, sisi4s::OneBodyFromGaussian::run, sisi4s::ParenthesisTriples::run, sisi4s::ParticleHoleCoulombVertexReader::run, sisi4s::TensorContraction::run, sisi4s::TensorSlicer::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::TensorWriter::write.
std::string Algorithm::getTextArgument(std::string const &argumentName, std::string const &defaultValue)
References EMIT, getTextArgument, isArgumentGiven.
bool Algorithm::getBooleanArgument(std::string const &name)
References EMIT, getTextArgument.
Referenced by getBooleanArgument.
bool Algorithm::getBooleanArgument(std::string const &name, bool const &defaultValue)
References EMIT, getBooleanArgument, isArgumentGiven.
int64_t Algorithm::getIntegerArgument(std::string const &argumentName)
References EMIT, EXCEPTION, getArgumentData, sisi4s::Data::getTypeName, sisi4s::IntegerData::value.
Referenced by sisi4s::CoulombIntegralsFromVertex::calculateComplexIntegrals, sisi4s::FiniteSizeCorrection::calculateFiniteSizeCorrection, sisi4s::CoulombIntegralsFromVertex::calculateRealIntegrals, sisi4s::FiniteSizeCorrection::calculateRealStructureFactor, sisi4s::FiniteSizeCorrection::dryCalculateFiniteSizeCorrection, sisi4s::CoulombIntegralsFromVertex::dryRun, sisi4s::CoulombVertexDecomposition::dryRun, sisi4s::CoulombVertexSingularVectors::dryRun, sisi4s::DoublesAmplitudesDecomposition::dryRun, sisi4s::FiniteSizeCorrection::dryRun, sisi4s::ParticleHoleCoulombVertexDecomposition::dryRun, sisi4s::ParticleHoleCoulombVertexSingularVectors::dryRun, sisi4s::CoulombVertexDecomposition::fit, sisi4s::BasisSetExtrapolation::fitF12, sisi4s::ClusterSinglesDoublesAlgorithm::getEnergy, getIntegerArgument, sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum, sisi4s::CcsdEnergyFromCoulombIntegralsReference::getResiduum, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduum, sisi4s::DrccdEnergyFromCoulombIntegrals::getResiduum, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumSth, sisi4s::CoulombVertexReader::handleUnrestricted, sisi4s::FiniteSizeCorrection::interpolation3D, sisi4s::CoulombVertexDecomposition::iterateQuadraticFactor, sisi4s::TensorReader::read, sisi4s::BasisSetExtrapolation::run, sisi4s::CcsdDiagrammaticDecomposition::run, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::ClusterSinglesDoublesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run, sisi4s::ComplexTensorReader::run, sisi4s::CoulombIntegralsFromGaussian::run, sisi4s::CoulombIntegralsFromRotatedCoulombIntegrals::run, sisi4s::CoulombIntegralsFromVertex::run, sisi4s::CoulombVertexDecomposition::run, sisi4s::CoulombVertexSingularVectors::run, sisi4s::FcidumpReader::run, sisi4s::FcidumpWriter::run, sisi4s::FiniteSizeCorrection::run, sisi4s::GenerateRandomComplexMatrix::run, sisi4s::GenerateRandomMatrix::run, sisi4s::GenerateRandomTensor::run, sisi4s::HartreeFockFromCoulombIntegrals::run, sisi4s::HartreeFockFromGaussian::run, sisi4s::MoReader::run, sisi4s::Mp2NaturalOrbitals::run, sisi4s::NaturalTransitionOrbitalsFromRhoAI::run, sisi4s::OneBodyRotation::run, sisi4s::ParticleHoleCoulombVertexDecomposition::run, sisi4s::ParticleHoleCoulombVertexReader::run, sisi4s::ParticleHoleCoulombVertexSingularVectors::run, sisi4s::TensorReader::run, sisi4s::UccsdAmplitudesFromCoulombIntegrals::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UegVertexGenerator::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::DoublesAmplitudesDecomposition::sliceLargestEigenValues.
int64_t Algorithm::getIntegerArgument(std::string const &argumentName, int64_t const defaultValue)
References EMIT, getIntegerArgument, isArgumentGiven.
sisi4s::real Algorithm::getRealArgument(std::string const &argumentName)
References EXCEPTION, getArgumentData, getRealArgumentFromInteger, getRealArgumentFromTensor, sisi4s::Data::getTypeName, sisi4s::RealData::value.
Referenced by sisi4s::DiisMixer< F >::DiisMixer, sisi4s::LinearMixer< F >::LinearMixer, sisi4s::FiniteSizeCorrection::calculateFiniteSizeCorrection, sisi4s::BasisSetExtrapolation::calculateNewSF, sisi4s::FiniteSizeCorrection::dryCalculateFiniteSizeCorrection, sisi4s::CoulombVertexDecomposition::dryRun, sisi4s::CoulombVertexSingularVectors::dryRun, sisi4s::DoublesAmplitudesDecomposition::dryRun, sisi4s::ParticleHoleCoulombVertexSingularVectors::dryRun, sisi4s::ClusterSinglesDoublesAlgorithm::estimateAmplitudesFromResiduum, sisi4s::BasisSetExtrapolation::fitF12, getRealArgument, sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum, sisi4s::FiniteSizeCorrection::interpolation3D, sisi4s::BasisSetExtrapolation::run, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdPerturbativeTriples::run, sisi4s::CcsdPerturbativeTriplesComplex::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::ClusterSinglesDoublesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ComplexTensorSum::run, sisi4s::CoulombVertexDecomposition::run, sisi4s::CoulombVertexSingularVectors::run, sisi4s::FcidumpWriter::run, sisi4s::HartreeFockFromCoulombIntegrals::run, sisi4s::HartreeFockFromGaussian::run, sisi4s::Mp2NaturalOrbitals::run, sisi4s::ParticleHoleCoulombVertexDecomposition::run, sisi4s::ParticleHoleCoulombVertexSingularVectors::run, sisi4s::PerturbativeTriples::run, sisi4s::TensorContraction::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UegVertexGenerator::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::PerturbativeTriples::runInMemory, sisi4s::PerturbativeTriples::runPiecuch, sisi4s::DoublesAmplitudesDecomposition::sliceLargestEigenValues.
sisi4s::real Algorithm::getRealArgument(std::string const &argumentName, real const defaultValue)
References getRealArgument, isArgumentGiven.
template DryTensor< Complex64 > * Algorithm::getTensorArgument< Complex64, DryTensor< Complex64 > >(std::string const &argumentName)
References EXCEPTION, getArgumentData, sisi4s::Data::getTypeName, sisi4s::TensorData< F, T >::value.
Referenced by sisi4s::FiniteSizeCorrection::calculateRealStructureFactor, sisi4s::FiniteSizeCorrection::dryCalculateStructureFactor, sisi4s::ParticleHoleCoulombVertexDecomposition::dryEvaluateMp2, sisi4s::ApproximateCoulombVertex::dryRun, sisi4s::ApproximateParticleHoleCoulombVertex::dryRun, sisi4s::CcsdPerturbativeTriples::dryRun, sisi4s::CcsdPerturbativeTriplesComplex::dryRun, sisi4s::CoulombIntegralsFromVertex::dryRun, sisi4s::CoulombVertexDecomposition::dryRun, sisi4s::CoulombVertexSingularVectors::dryRun, sisi4s::DoublesAmplitudesDecomposition::dryRun, sisi4s::DoublesAmplitudesFromVertex::dryRun, sisi4s::ParticleHoleCoulombVertexDecomposition::dryRun, sisi4s::ParticleHoleCoulombVertexSingularVectors::dryRun, sisi4s::PerturbativeTriples::dryRun, sisi4s::SingleParticleOccupancies::dryRun, sisi4s::SliceCoulombVertex::dryRun, sisi4s::UPerturbativeTriples::dryRun, sisi4s::PerturbativeTriples::dryRunPiecuch, sisi4s::ParticleHoleCoulombVertexDecomposition::evaluateMp2, sisi4s::CcsdPerturbativeTriples::getEnergyDenominator, sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum, sisi4s::CcsdEnergyFromCoulombIntegralsReference::getResiduum, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumSth, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UccsdtqAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UrpaAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::CcsdtEnergyFromCoulombIntegrals::getResiduumTemplate, sisi4s::CcsdDiagrammaticDecomposition::run, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdPerturbativeTriples::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::CoulombIntegralsFromGaussian::run, sisi4s::CoulombIntegralsFromRotatedCoulombIntegrals::run, sisi4s::Mp2NaturalOrbitals::run, sisi4s::OneBodyRotation::run, sisi4s::PerturbativeTriples::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::UPerturbativeTriples::run, sisi4s::PerturbativeTriples::runInMemory, sisi4s::PerturbativeTriples::runPiecuch, sisi4s::ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors, sisi4s::ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors, sisi4s::CcsdPerturbativeTriples::sliceTensors, sisi4s::CoulombVertexReader::unrestrictEigenEnergies.
C * Algorithm::getContainerArgument(std::string const &argumentName)
References EXCEPTION, getArgumentData, sisi4s::Data::getTypeName, sisi4s::ContainerData< F, C >::value.
void Algorithm::allocateContainerArgument(std::string const &argumentName, C *container)
References getArgumentData, sisi4s::Data::getName.
std::vector< std::string > sisi4s::Algorithm::getGivenArgumentNames() const
References arguments.
Referenced by checkArgumentsOrDie.
void sisi4s::Algorithm::checkArgumentsOrDie(const std::vector< std::string > args) const
References EXCEPTION, getGivenArgumentNames.
Referenced by sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CoulombIntegralsFromGaussian::run, sisi4s::CoulombIntegralsFromRotatedCoulombIntegrals::run, sisi4s::HartreeFockFromCoulombIntegrals::run, sisi4s::HartreeFockFromGaussian::run, sisi4s::MeanCorrelationHoleDepth::run, sisi4s::NuclearRepulsionEnergy::run, sisi4s::OneBodyFromGaussian::run, sisi4s::OneBodyRotation::run, sisi4s::TensorReduceijij::run, sisi4s::TensorSlicer::run, sisi4s::UccsdAmplitudesFromCoulombIntegrals::run.
template void Algorithm::allocatedTensorArgument< Complex64, DryScalar< Complex64 > >(std::string const &argumentName, T *tensor)
Specifies the location of an output tensor data.
argumentName The argument name as specified in the sisi4s file tensor The reference of the tensor data allocated by the caller and later freed by the system if not needed any further. often explicit instantiation may be necessary, e.g. allocatedTensorArgument<complex>(complexTensor);
References getArgumentData, sisi4s::Data::getName.
Referenced by sisi4s::CoulombIntegralsFromVertex::calculateRealIntegrals, computeAndExport, computeAndExport, sisi4s::CoulombIntegralsFromVertex::dryCalculateRealIntegrals, sisi4s::FiniteSizeCorrection::dryCalculateStructureFactor, sisi4s::CoulombVertexReader::dryRun, sisi4s::ParticleHoleCoulombVertexReader::dryRun, sisi4s::CoulombVertexReader::run, sisi4s::CoulombVertexSingularVectors::run, sisi4s::DoublesAmplitudesFromVertex::run, sisi4s::FromComplexTensor::run, sisi4s::GenerateRandomMatrix::run, sisi4s::GenerateRandomTensor::run, sisi4s::Mp2NaturalOrbitals::run, sisi4s::ParticleHoleCoulombVertexReader::run.
void Algorithm::setRealArgument(std::string const &argumentName, real const value)
References getArgumentData, sisi4s::Data::getName.
Referenced by sisi4s::FiniteSizeCorrection::calculateFiniteSizeCorrection, sisi4s::FiniteSizeCorrection::dryCalculateFiniteSizeCorrection, sisi4s::BasisSetExtrapolation::fitF12, sisi4s::CcsdPerturbativeTriples::run, sisi4s::CcsdPerturbativeTriplesComplex::run, sisi4s::ClusterSinglesDoublesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run, sisi4s::ComplexTensorNorm::run, sisi4s::ParenthesisTriples::run, sisi4s::PerturbativeTriples::run, sisi4s::UPerturbativeTriples::run, sisi4s::PerturbativeTriples::runInMemory, sisi4s::PerturbativeTriples::runPiecuch.
void Algorithm::setIntegerArgument(std::string const &argumentName, int const value)
References getArgumentData, sisi4s::Data::getName.
Referenced by sisi4s::UccsdAmplitudesFromCoulombIntegrals::run, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::run.
sisi4s::real Algorithm::getRealArgumentFromInteger(IntegerData *data)
References LOG, sisi4s::IntegerData::value.
Referenced by getRealArgument.
sisi4s::real Algorithm::getRealArgumentFromTensor(TensorData< real > *data)
References Assert, sisi4s::TensorData< F, T >::value.
Referenced by getRealArgument.
template DryTensor< Complex64 > * Algorithm::getTensorArgumentFromReal< Complex64, DryTensor< Complex64 > >(RealData *realData)
Converts the given real data into a scalar tensor.
References sisi4s::RealData::value.
Data * Algorithm::getArgumentData(std::string const &argumentName)
References arguments, EXCEPTION, sisi4s::Data::get.
Referenced by allocateContainerArgument, allocatedTensorArgument, sisi4s::Delete::dryRun, getContainerArgument, getIntegerArgument, getRealArgument, getTensorArgument, getTextArgument, sisi4s::CcsdPerturbativeTriplesComplex::run, sisi4s::ClusterSinglesDoublesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesQuadruplesAlgorithm::run, sisi4s::ComplexTensorReader::run, sisi4s::ComplexTensorWriter::run, sisi4s::Delete::run, sisi4s::FiniteSizeCorrection::run, sisi4s::TensorReader::run, setIntegerArgument, setRealArgument.