sisi4s::ParenthesisTriples
AlgorithmRegistrar< ParenthesisTriples > ParenthesisTriples::registrar_
int64_t sisi4s::ParenthesisTriples::No
Referenced by doublesContribution, run, singlesContribution.
int64_t sisi4s::ParenthesisTriples::Nv
Referenced by doublesContribution, getEnergy, getVpppijkFromVertex, run, singlesContribution.
int64_t sisi4s::ParenthesisTriples::NG
Referenced by getVpppijkFromVertex, run.
int64_t sisi4s::ParenthesisTriples::NvCube
Referenced by getVpppijkFromVertex, getVpppijkOnTheFly, run.
double* sisi4s::ParenthesisTriples::Tabc
Referenced by ~ParenthesisTriples, run.
double* sisi4s::ParenthesisTriples::Zabc
Referenced by ~ParenthesisTriples, run.
double* sisi4s::ParenthesisTriples::scratch
Referenced by ~ParenthesisTriples, run.
double* sisi4s::ParenthesisTriples::Tabij
Referenced by doublesContribution, run.
double * sisi4s::ParenthesisTriples::Tai
Referenced by run, singlesContribution.
double* sisi4s::ParenthesisTriples::epsi
Referenced by run.
double * sisi4s::ParenthesisTriples::epsa
Referenced by getEnergy, run.
double* sisi4s::ParenthesisTriples::Vabij
Referenced by run, singlesContribution.
double * sisi4s::ParenthesisTriples::Vhphh
Referenced by doublesContribution, run.
double * sisi4s::ParenthesisTriples::Vppph
Referenced by run.
double* sisi4s::ParenthesisTriples::Vpppijk
Referenced by ~ParenthesisTriples, getVpppijkFromVertex, run.
double* sisi4s::ParenthesisTriples::realGab
Referenced by ~ParenthesisTriples, getVpppijkFromVertex, run.
double * sisi4s::ParenthesisTriples::imagGab
Referenced by ~ParenthesisTriples, getVpppijkFromVertex, run.
double * sisi4s::ParenthesisTriples::realGai
Referenced by ~ParenthesisTriples, getVpppijkFromVertex, run.
double * sisi4s::ParenthesisTriples::imagGai
Referenced by ~ParenthesisTriples, getVpppijkFromVertex, run.
bool sisi4s::ParenthesisTriples::particleDiagram
Referenced by doublesContribution, run.
bool sisi4s::ParenthesisTriples::holeDiagram
Referenced by doublesContribution, run.
virtual std::string sisi4s::ParenthesisTriples::getName()
ParenthesisTriples::ParenthesisTriples(std::vector< Argument > const &argumentList)
ParenthesisTriples::~ParenthesisTriples()
References imagGab, imagGai, realGab, realGai, scratch, Tabc, Vpppijk, Zabc.
void ParenthesisTriples::run()
Calculates perturbative triples correction, third attemp.
References doublesContribution, epsa, epsi, sisi4s::fromComplexTensor, getEnergyOne, getEnergyZero, sisi4s::Time::getFractionalSeconds, sisi4s::Algorithm::getTextArgument, getVpppijkFromVertex, getVpppijkOnTheFly, holeDiagram, sisi4s::IJKPointer::i, imagGab, imagGai, sisi4s::Algorithm::isArgumentGiven, sisi4s::IJKPointer::j, sisi4s::IJKPointer::k, LOG, NEW, NG, No, Nv, NvCube, particleDiagram, PTR, realGab, realGai, scratch, sisi4s::Algorithm::setRealArgument, singlesContribution, Tabc, Tabij, Tai, Vabij, Vhphh, Vppph, Vpppijk, sisi4s::Sisi4s::world, Zabc.
void ParenthesisTriples::dryRun()
Dry run for perturbative triples correction, third attemp.
double ParenthesisTriples::getEnergy(const double epsijk, const double *Tabc_, const double *Zabc_)
References epsa, Nv.
void ParenthesisTriples::doublesContribution(const std::array< int64_t, 3 > &ijk, IJKPointer integralContainer, double *scratchV, double *scratchO, double *output)
References holeDiagram, sisi4s::IJKPointer::i, sisi4s::IJKPointer::j, sisi4s::IJKPointer::k, No, Nv, particleDiagram, permuteAddOne, permuteMoveTwo, Tabij, Vhphh.
Referenced by run.
void ParenthesisTriples::singlesContribution(const std::array< int64_t, 3 > &ijk, double *scratchO, double *output)
References No, Nv, Tai, Vabij.
Referenced by run.
void ParenthesisTriples::getVpppijkFromVertex(const std::array< int64_t, 3 > &ijk, double *scratchO, double *output)
References imagGab, imagGai, NG, Nv, NvCube, permuteMoveOne, realGab, realGai, Vpppijk.
Referenced by run.
IJKPointer ParenthesisTriples::getVpppijkOnTheFly(const std::array< int64_t, 3 > &ijk, VectorTensor< double > &vtensor)
References sisi4s::Algorithm::getTextArgument, NvCube, sisi4s::VectorTensor< F >::refs, sisi4s::VectorTensor< F >::tensors, sisi4s::VectorTensor< F >::withReference.
Referenced by run.