sisi4s::CcsdPerturbativeTriples
AlgorithmRegistrar< CcsdPerturbativeTriples > CcsdPerturbativeTriples::registrar_
int sisi4s::CcsdPerturbativeTriples::No
Referenced by run, sliceTensors.
int sisi4s::CcsdPerturbativeTriples::Nv
Referenced by dryRun, run, sliceTensors.
CTF::Tensor* sisi4s::CcsdPerturbativeTriples::SVabc
Referenced by getDoublesContribution, getEnergyDenominator, getSinglesContribution, run.
CTF::Tensor * sisi4s::CcsdPerturbativeTriples::DVabc
Referenced by run.
CTF::Tensor* sisi4s::CcsdPerturbativeTriples::realGammaFab
Referenced by getDoublesContribution, run, sliceTensors.
CTF::Tensor * sisi4s::CcsdPerturbativeTriples::imagGammaFab
Referenced by getDoublesContribution, run, sliceTensors.
SlicedCtfTensor* sisi4s::CcsdPerturbativeTriples::Tai
Referenced by dryRun, run, sliceTensors.
SlicedCtfTensor * sisi4s::CcsdPerturbativeTriples::Tabij
Referenced by dryRun, run, sliceTensors.
SlicedCtfTensor * sisi4s::CcsdPerturbativeTriples::Tabil
Referenced by run, sliceTensors.
SlicedCtfTensor* sisi4s::CcsdPerturbativeTriples::Vabij
Referenced by getSinglesContribution, run, sliceTensors.
SlicedCtfTensor * sisi4s::CcsdPerturbativeTriples::Vijla
Referenced by getDoublesContribution, run, sliceTensors.
SlicedCtfTensor * sisi4s::CcsdPerturbativeTriples::realGammaFai
Referenced by run, sliceTensors.
SlicedCtfTensor * sisi4s::CcsdPerturbativeTriples::imagGammaFai
Referenced by run, sliceTensors.
virtual std::string sisi4s::CcsdPerturbativeTriples::getName()
CcsdPerturbativeTriples::CcsdPerturbativeTriples(std::vector< Argument > const &argumentList)
CcsdPerturbativeTriples::~CcsdPerturbativeTriples()
void CcsdPerturbativeTriples::run()
Calculates perturbative triples correction. Routine based on Helgaker book.
References DVabc, sisi4s::Time::getCurrentRealTime, getDoublesContribution, getEnergyDenominator, sisi4s::Algorithm::getRealArgument, getSinglesContribution, sisi4s::Algorithm::getTensorArgument, imagGammaFab, imagGammaFai, sisi4s::Permutation< N >::invariantElementsCount, LOG, No, Nv, realGammaFab, realGammaFai, sisi4s::Algorithm::setRealArgument, sliceTensors, SVabc, Tabij, Tabil, Tai, Vabij, Vijla, sisi4s::Sisi4s::world.
void CcsdPerturbativeTriples::dryRun()
Dry run for perturbative triples correction based on Helgaker book.
References sisi4s::Algorithm::getTensorArgument, sisi4s::DryTensor< F >::lens, Nv, SOURCE_LOCATION, Tabij, Tai.
void CcsdPerturbativeTriples::sliceTensors()
References sisi4s::fromComplexTensor, sisi4s::Algorithm::getTensorArgument, imagGammaFab, imagGammaFai, No, Nv, realGammaFab, realGammaFai, Tabij, Tabil, Tai, Vabij, Vijla.
Referenced by run.
Tensor & CcsdPerturbativeTriples::getSinglesContribution(const Map< 3 > &)
References SVabc, Vabij.
Referenced by run.
Tensor & CcsdPerturbativeTriples::getDoublesContribution(const Map< 3 > &)
References imagGammaFab, realGammaFab, SVabc, Vijla.
Referenced by run.
Tensor & CcsdPerturbativeTriples::getEnergyDenominator(const Map< 3 > &)
References sisi4s::Algorithm::getTensorArgument, SVabc.
Referenced by run.