sisi4s::Vector
typedef F sisi4s::Vector< F, D >::FieldType
F sisi4s::Vector< F, D >::coordinate[D][D]
Referenced by sisi4s::Vector< F, D >::Vector, sisi4s::Vector< F, D >::Vector, sisi4s::Vector< F, D >::at, sisi4s::Vector< F, D >::at, sisi4s::Vector< F, D >::cross, sisi4s::Vector< F, D >::dot, sisi4s::Vector< F, D >::operator*, sisi4s::Vector< F, D >::operator*=, sisi4s::Vector< F, D >::operator+, sisi4s::Vector< F, D >::operator+=, sisi4s::Vector< F, D >::operator-, sisi4s::Vector< F, D >::operator-=, sisi4s::Vector< F, D >::operator/, sisi4s::Vector< F, D >::operator/=, sisi4s::Vector< F, D >::operator<, sisi4s::operator<<, sisi4s::Vector< F, D >::operator=, sisi4s::Vector< F, D >::operator[], sisi4s::Vector< F, D >::operator[].
sisi4s::Vector< F, D >::Vector()
References sisi4s::Vector< F, D >::coordinate.
sisi4s::Vector< F, D >::Vector(Vector< F, D > const &v)
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > & sisi4s::Vector< F, D >::operator=(Vector< F, D > const &v)
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > & sisi4s::Vector< F, D >::operator+=(Vector< F, D > const &v)
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > & sisi4s::Vector< F, D >::operator-=(Vector< F, D > const &v)
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > & sisi4s::Vector< F, D >::operator*=(const F r)
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > & sisi4s::Vector< F, D >::operator/=(const F r)
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > sisi4s::Vector< F, D >::operator+(Vector< F, D > const &v) const
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > sisi4s::Vector< F, D >::operator-(Vector< F, D > const &v) const
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > sisi4s::Vector< F, D >::operator/(const F r) const
References sisi4s::Vector< F, D >::coordinate.
Vector< F, D > sisi4s::Vector< F, D >::operator*(const F r) const
References sisi4s::Vector< F, D >::coordinate.
Vector< F, 3 > sisi4s::Vector< F, D >::cross(Vector< F, 3 > const &v)
References sisi4s::Vector< F, D >::coordinate.
Referenced by sisi4s::FiniteSizeCorrection::interpolation3D.
F sisi4s::Vector< F, D >::dot(Vector< F, D > const &v) const
References sisi4s::Vector< F, D >::coordinate, sisi4s::dot.
Referenced by sisi4s::Vector< F, D >::approximately, sisi4s::Vector< F, D >::distance, sisi4s::FiniteSizeCorrection::interpolation3D, sisi4s::Vector< F, D >::length.
int sisi4s::Vector< F, D >::approximately(Vector< F, D > const &v, const double epsilon=1e-10) const
References sisi4s::Vector< F, D >::dot.
Referenced by sisi4s::FiniteSizeCorrection::Momentum::locate.
double sisi4s::Vector< F, D >::distance(Vector< F, D > const &v) const
References sisi4s::Vector< F, D >::dot.
double sisi4s::Vector< F, D >::length() const
References sisi4s::Vector< F, D >::dot.
Referenced by sisi4s::BasisSetExtrapolation::evaluateQGG, sisi4s::FiniteSizeCorrection::interpolation3D, sisi4s::Vector< F, D >::sortByLength.
F sisi4s::Vector< F, D >::operator[](int d) const
References sisi4s::Vector< F, D >::coordinate.
F & sisi4s::Vector< F, D >::operator[](int d)
References sisi4s::Vector< F, D >::coordinate.
F sisi4s::Vector< F, D >::at(int d) const
References sisi4s::Vector< F, D >::coordinate.
F & sisi4s::Vector< F, D >::at(int d)
References sisi4s::Vector< F, D >::coordinate.
bool sisi4s::Vector< F, D >::operator<(Vector< F, D > const &v) const
References sisi4s::Vector< F, D >::coordinate.
static bool sisi4s::Vector< F, D >::sortByLength(Vector< F, D > const &n, Vector< F, D > const &m)
References sisi4s::Vector< F, D >::length.