sisi4s::Data
Stage
std::string sisi4s::Data::name
Referenced by ~Data, get, getName.
std::string sisi4s::Data::typeName
Referenced by Data, getTypeName.
Stage sisi4s::Data::stage
Referenced by getStage.
std::map< std::string, Data * > Data::dataMap
Referenced by Data, Data, ~Data, get.
int64_t sisi4s::Data::nextAnynomousDataId
Data::Data(std::string const &name_)
References dataMap, typeName.
virtual sisi4s::Data::~Data()
References dataMap, name.
std::string sisi4s::Data::getName() const
References name.
Referenced by sisi4s::Algorithm::allocateContainerArgument, sisi4s::Algorithm::allocatedTensorArgument, sisi4s::Delete::dryRun, sisi4s::Delete::run, sisi4s::Algorithm::setIntegerArgument, sisi4s::Algorithm::setRealArgument.
std::string sisi4s::Data::getTypeName() const
References typeName.
Referenced by sisi4s::Algorithm::getContainerArgument, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, sisi4s::Algorithm::getTensorArgument, sisi4s::Algorithm::getTextArgument.
Stage sisi4s::Data::getStage() const
References stage.
Referenced by Data.
static Data * sisi4s::Data::get(std::string const &name)
References dataMap, name.
Referenced by sisi4s::Algorithm::getArgumentData.
sisi4s::Data::Data(std::string const &name_, std::string const &typeName_)
protected constructor for typed data.
References dataMap, getStage, LOG, MENTIONED.