sisi4s::CoulombVertexDecomposition
sisi4s::AlgorithmRegistrar< CoulombVertexDecomposition > CoulombVertexDecomposition::registrar_
int64_t constexpr sisi4s::CoulombVertexDecomposition::DEFAULT_RANK_SIZE
Referenced by dryRun, run.
double constexpr sisi4s::CoulombVertexDecomposition::DEFAULT_RANK_FACTOR
Referenced by dryRun, run.
constexpr int64_t sisi4s::CoulombVertexDecomposition::DEFAULT_MAX_ITERATIONS
Referenced by run.
constexpr double sisi4s::CoulombVertexDecomposition::DEFAULT_DELTA
Referenced by run.
constexpr double sisi4s::CoulombVertexDecomposition::DEFAULT_SWAMPING_THRESHOLD
Referenced by run.
constexpr double sisi4s::CoulombVertexDecomposition::DEFAULT_REGULARIZATION_FRICTION
Referenced by run.
constexpr bool sisi4s::CoulombVertexDecomposition::DEFAULT_REAL_FACTOR_ORBITALS
Referenced by dryRun, run.
constexpr bool sisi4s::CoulombVertexDecomposition::DEFAULT_NORMALIZED_FACTOR_ORBITALS
Referenced by dryRun, run.
constexpr bool sisi4s::CoulombVertexDecomposition::DEFAULT_WRITE_SUB_ITERATIONS
Referenced by run.
const std::string CoulombVertexDecomposition::SYMMETRIC
Referenced by computeOutgoingPi, dryRun, run.
const std::string CoulombVertexDecomposition::HERMITIAN
Referenced by computeOutgoingPi, dryRun, run.
const std::string CoulombVertexDecomposition::PSEUDO_INVERSE
Referenced by computeOutgoingPi, dryRun, run.
int64_t sisi4s::CoulombVertexDecomposition::rank
The rank $N_R$ of the tensor rank decomposition.
Referenced by dryRun, run.
double sisi4s::CoulombVertexDecomposition::Delta
The Frobenius norm of the difference between $\Gamma^q_{rG}$ and its decomposition.
Referenced by fit, getDelta, iterateQuadraticFactor, run.
bool sisi4s::CoulombVertexDecomposition::realFactorOrbitals
Whether the factor orbitals $\Pi_{qR}$ are required to be real.
Referenced by dryRun, iterateQuadraticFactor, run.
bool sisi4s::CoulombVertexDecomposition::normalizedFactorOrbitals
Whether the factor orbitals $\Pi_{qR}$ are required to be normalized, i.e. ${\Pi^\ast}^{qR}\Pi_{qR} = \delta{qq}$.
Referenced by dryRun, iterateQuadraticFactor, run.
bool sisi4s::CoulombVertexDecomposition::writeSubIterations
Whether to write Delta after each part of one RALS iteration, where Delta is the Frobenius norm of ${\Pi^\ast}^{qR}Pi_{rR}\Lambda_{GR} - \Gamma^q_{rG}$.
Referenced by iterateQuadraticFactor, run.
Tensor<complex>* sisi4s::CoulombVertexDecomposition::GammaGqr
The full Coulomb vertex $\Gamma^q_{rG}$.
Referenced by dryFit, dryRun, fit, iterateQuadraticFactor, run.
Tensor<complex>* sisi4s::CoulombVertexDecomposition::composedGammaGqr
The fit ${\Pi^\ast}^{qR}\Pi_{rR}\Lambda_{GR}$.
Referenced by ~CoulombVertexDecomposition, dryFit, dryRun, getDelta, run.
CTF::Matrix<complex>* sisi4s::CoulombVertexDecomposition::PiqR
The conjugated factor orbitals ${\Pi^\ast}^{qR} = (\Pi_{qR})^\ast$.
Referenced by ~CoulombVertexDecomposition, computeOutgoingPi, dryFit, dryRun, fit, getDelta, iterateQuadraticFactor, run.
CTF::Matrix<complex>* sisi4s::CoulombVertexDecomposition::PirR
The factor orbitals $\Pi_{rR} = ({\Pi^\ast}^{rR})^\ast$.
Referenced by computeOutgoingPi, dryFit, dryRun, fit, getDelta, iterateQuadraticFactor, run.
CTF::Matrix<complex>* sisi4s::CoulombVertexDecomposition::LambdaGR
The full Coulomb factors $\Lambda_{GR}$.
Referenced by dryFit, dryRun, fit, getDelta, iterateQuadraticFactor, run.
AlternatingLeastSquaresRegularizationEstimator* sisi4s::CoulombVertexDecomposition::regularizationEstimator
Estimator for the regularization parameter during the alternating least squares fits. They estimate the regularization parameter $\lambda$ in each iteration from the swamping factor in the previous iteration.
Referenced by ~CoulombVertexDecomposition, fit, run.
virtual std::string sisi4s::CoulombVertexDecomposition::getName()
CoulombVertexDecomposition::CoulombVertexDecomposition(std::vector< Argument > const &argumentList)
CoulombVertexDecomposition::~CoulombVertexDecomposition()
References composedGammaGqr, sisi4s::Algorithm::isArgumentGiven, PiqR, regularizationEstimator.
void CoulombVertexDecomposition::run()
References composedGammaGqr, computeOutgoingPi, DEFAULT_DELTA, DEFAULT_MAX_ITERATIONS, DEFAULT_NORMALIZED_FACTOR_ORBITALS, DEFAULT_RANK_FACTOR, DEFAULT_RANK_SIZE, DEFAULT_REAL_FACTOR_ORBITALS, DEFAULT_REGULARIZATION_FRICTION, DEFAULT_SWAMPING_THRESHOLD, DEFAULT_WRITE_SUB_ITERATIONS, Delta, EXCEPTION, fit, GammaGqr, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, sisi4s::Algorithm::getTextArgument, HERMITIAN, sisi4s::Algorithm::isArgumentGiven, LambdaGR, LOG, normalizedFactorOrbitals, normalizePi, PiqR, PirR, PSEUDO_INVERSE, rank, realFactorOrbitals, realizePi, regularizationEstimator, sisi4s::setRandomTensor, SYMMETRIC, writeSubIterations.
void CoulombVertexDecomposition::dryRun()
The dryRun estimates resource consumption, especially memory and processor time.
References composedGammaGqr, DEFAULT_NORMALIZED_FACTOR_ORBITALS, DEFAULT_RANK_FACTOR, DEFAULT_RANK_SIZE, DEFAULT_REAL_FACTOR_ORBITALS, dryFit, EXCEPTION, GammaGqr, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, sisi4s::Algorithm::getTensorArgument, sisi4s::Algorithm::getTextArgument, HERMITIAN, sisi4s::Algorithm::isArgumentGiven, LambdaGR, LOG, normalizedFactorOrbitals, PiqR, PirR, PSEUDO_INVERSE, rank, realFactorOrbitals, SYMMETRIC.
void CoulombVertexDecomposition::fit(int64_t iterationsCount)
Performs one iteration in fitting the factor orbitals and the Coulomb factors according to the given algorithm.
References Delta, sisi4s::fitRegularizedAlternatingLeastSquaresFactor, GammaGqr, getDelta, sisi4s::Algorithm::getIntegerArgument, iterateQuadraticFactor, LambdaGR, LOG, PiqR, PirR, regularizationEstimator.
Referenced by run.
void CoulombVertexDecomposition::dryFit(DryTensor< complex > *GammaGqr, DryTensor< complex > *PiqR, DryTensor< complex > *PirR, DryTensor< complex > *LambdaGR, DryTensor< complex > *composedGammaGqr)
Performs a dry run of one iteration in fitting the factor orbitals and the Coulomb factors according to the given algorithm.
References composedGammaGqr, sisi4s::dryComposeCanonicalPolyadicDecompositionTensors, sisi4s::dryFitRegularizedAlternatingLeastSquaresFactor, GammaGqr, LambdaGR, PiqR, PirR.
Referenced by dryRun.
void CoulombVertexDecomposition::normalizePi(Tensor< complex > &Pi)
Normalizes the given factor orbitals, such that ${\Pi^\ast}^{qR}\Pi_{qR} = \delta_{qq}$.
References sisi4s::Pi.
Referenced by iterateQuadraticFactor, run.
void CoulombVertexDecomposition::realizePi(Tensor< complex > &Pi)
Discards the imaginary part of the given factor orbitals.
References sisi4s::Pi.
Referenced by iterateQuadraticFactor, run.
void CoulombVertexDecomposition::iterateQuadraticFactor(int iterationsCount)
Solves the quadratically occurring factor Pi iteratively similar to the Babylonian algorithm.
{ Currently \f$\Pi_{qR}Pi_{rR}\Lambda_{GR} $ is solved for instead of ${\Pi^\ast}^{qR}Pi_{rR}\Lambda_{GR}
References computeOutgoingPi, Delta, EXCEPTION, sisi4s::fitAlternatingLeastSquaresFactor, GammaGqr, sisi4s::FockVector< F >::get, getDelta, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getTextArgument, LambdaGR, LOG, NEW, normalizedFactorOrbitals, normalizePi, sisi4s::Pi, PiqR, PirR, PTR, realFactorOrbitals, realizePi, writeSubIterations.
Referenced by fit.
void CoulombVertexDecomposition::computeOutgoingPi()
Takes the incoming factor orbitals and computes the outgoing factor orbitals according to the chosen ansatz. The ansatz is specified as the string argument ansatz and can be one of the following: "symmetric", "hermitian", "pseudoInverse".
References EXCEPTION, sisi4s::IterativePseudoInverse< F >::get, sisi4s::Algorithm::getTextArgument, HERMITIAN, PiqR, PirR, PSEUDO_INVERSE, SYMMETRIC.
Referenced by iterateQuadraticFactor, run.
double CoulombVertexDecomposition::getDelta()
Computes and returns the difference.
References sisi4s::composeCanonicalPolyadicDecompositionTensors, composedGammaGqr, Delta, sisi4s::frobeniusNorm, LambdaGR, PiqR, PirR.
Referenced by fit, iterateQuadraticFactor.