sisi4s::RandomGenerator
unsigned int sisi4s::RandomGenerator::x
Referenced by nextCoarseInteger.
unsigned int sisi4s::RandomGenerator::y
Referenced by nextCoarseInteger.
unsigned int sisi4s::RandomGenerator::z
Referenced by nextCoarseInteger.
unsigned int sisi4s::RandomGenerator::n
Referenced by nextCoarseInteger.
unsigned int sisi4s::RandomGenerator::c
Referenced by nextCoarseInteger.
sisi4s::RandomGenerator::RandomGenerator(unsigned int seed=1, int shaking=32)
References nextInteger.
double sisi4s::RandomGenerator::nextUniform()
References nextCoarseInteger.
unsigned int sisi4s::RandomGenerator::nextInteger()
Returns the next integer with 32 random bits where all bits show good randomness.
References nextCoarseInteger.
Referenced by RandomGenerator.
unsigned int sisi4s::RandomGenerator::nextCoarseInteger()
Returns the next integer with 32 random bits where only the most significant bits show good randomness.
References c, n, x, y, z.
Referenced by nextInteger, nextUniform.