sisi4s::ParticleHoleCoulombVertexDecomposition
AlgorithmRegistrar< ParticleHoleCoulombVertexDecomposition > ParticleHoleCoulombVertexDecomposition::registrar_
int64_t constexpr sisi4s::ParticleHoleCoulombVertexDecomposition::DEFAULT_MAX_ITERATIONS
Referenced by run.
double constexpr sisi4s::ParticleHoleCoulombVertexDecomposition::DEFAULT_DELTA
Referenced by run.
int constexpr sisi4s::ParticleHoleCoulombVertexDecomposition::DEFAULT_EPSILON_STEP
Referenced by dryRun, run.
double constexpr sisi4s::ParticleHoleCoulombVertexDecomposition::DEFAULT_SWAMPING_THRESHOLD
Referenced by run.
double constexpr sisi4s::ParticleHoleCoulombVertexDecomposition::DEFAULT_REGULARIZATION_FRICTION
Referenced by run.
bool constexpr sisi4s::ParticleHoleCoulombVertexDecomposition::DEFAULT_REAL_FACTOR_ORBITALS
Referenced by dryRun, run.
bool constexpr sisi4s::ParticleHoleCoulombVertexDecomposition::DEFAULT_NORMALIZED_FACTOR_ORBITALS
Referenced by dryRun, run.
int64_t sisi4s::ParticleHoleCoulombVertexDecomposition::rank
The rank $N_R$ of the tensor rank decomposition.
Referenced by dryRun, run.
double sisi4s::ParticleHoleCoulombVertexDecomposition::Delta
The Frobenius norm of the difference between $\Gamma^a_{iG}$ and its decomposition.
Referenced by fit, run.
int sisi4s::ParticleHoleCoulombVertexDecomposition::epsilonStep
The number of steps between two evaluations of the error in the MP2 energy of the decomposition. A value below 1 results in no evaluations.
Referenced by dryRun, run.
bool sisi4s::ParticleHoleCoulombVertexDecomposition::realFactorOrbitals
Whether the factor orbitals $\Pi_{aR},\Pi_{iR}$ are required to be real.
Referenced by dryRun, fit, run.
bool sisi4s::ParticleHoleCoulombVertexDecomposition::normalizedFactorOrbitals
Whether the factor orbitals $\Pi_{aR},\Pi_{iR}$ are required to be normalized, i.e. ${\Pi^\ast}^{qR}\Pi_{qR} = \delta{qq}$.
Referenced by dryRun, fit, run.
CTF::Tensor<complex>* sisi4s::ParticleHoleCoulombVertexDecomposition::GammaGai
The Coulomb vertex $\Gamma^a_{iG}$ restricted to a particle and a hole index.
Referenced by dryFit, dryRun, fit, run.
CTF::Tensor<complex>* sisi4s::ParticleHoleCoulombVertexDecomposition::Gamma0Gai
The fit ${\Pi^\ast}^{aR}\Pi_{iR}\Lambda_{GR}$.
Referenced by dryFit, dryRun, evaluateMp2Error, fit, run.
CTF::Tensor<complex>* sisi4s::ParticleHoleCoulombVertexDecomposition::PiiR
The factor orbitals for occupied states $\Pi_{iR}$.
Referenced by dryFit, dryRun, fit, run.
CTF::Tensor<complex>* sisi4s::ParticleHoleCoulombVertexDecomposition::PiaR
The conjugated factor orbitals for virtual states ${\Pi^\ast}^{aR}$.
Referenced by dryFit, dryRun, fit, run.
CTF::Tensor<complex>* sisi4s::ParticleHoleCoulombVertexDecomposition::LambdaGR
The Coulomb factors $\Lambda_{GR}$ in the particle/hole decomposition.
Referenced by dryFit, dryRun, fit, run.
AlternatingLeastSquaresRegularizationEstimator* sisi4s::ParticleHoleCoulombVertexDecomposition::regularizationEstimatorPiiR
Estimators for the regularization parameter during the alternating least squares fits. They estimate the regularization parameter $\lambda$ in each iteration from the swamping factor in the previous iteration.
Referenced by fit, run.
AlternatingLeastSquaresRegularizationEstimator * sisi4s::ParticleHoleCoulombVertexDecomposition::regularizationEstimatorPiaR
Referenced by fit, run.
AlternatingLeastSquaresRegularizationEstimator * sisi4s::ParticleHoleCoulombVertexDecomposition::regularizationEstimatorLambdaGR
Referenced by fit, run.
double sisi4s::ParticleHoleCoulombVertexDecomposition::mp2Energy
Referenced by evaluateMp2Error, run.
virtual std::string sisi4s::ParticleHoleCoulombVertexDecomposition::getName()
ParticleHoleCoulombVertexDecomposition::ParticleHoleCoulombVertexDecomposition(std::vector< Argument > const &argumentList)
ParticleHoleCoulombVertexDecomposition::~ParticleHoleCoulombVertexDecomposition()
void ParticleHoleCoulombVertexDecomposition::run()
References DEFAULT_DELTA, DEFAULT_EPSILON_STEP, DEFAULT_MAX_ITERATIONS, DEFAULT_NORMALIZED_FACTOR_ORBITALS, DEFAULT_REAL_FACTOR_ORBITALS, DEFAULT_REGULARIZATION_FRICTION, DEFAULT_SWAMPING_THRESHOLD, Delta, epsilonStep, evaluateMp2, evaluateMp2Error, fit, Gamma0Gai, GammaGai, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, sisi4s::Algorithm::isArgumentGiven, LambdaGR, LOG, mp2Energy, normalizedFactorOrbitals, normalizePi, PiaR, PiiR, rank, realFactorOrbitals, realizePi, regularizationEstimatorLambdaGR, regularizationEstimatorPiaR, regularizationEstimatorPiiR, sisi4s::setRandomTensor.
void ParticleHoleCoulombVertexDecomposition::dryRun()
The dryRun estimates resource consumption, especially memory and processor time.
References DEFAULT_EPSILON_STEP, DEFAULT_NORMALIZED_FACTOR_ORBITALS, DEFAULT_REAL_FACTOR_ORBITALS, dryEvaluateMp2, dryFit, epsilonStep, Gamma0Gai, GammaGai, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getTensorArgument, sisi4s::Algorithm::isArgumentGiven, LambdaGR, LOG, normalizedFactorOrbitals, PiaR, PiiR, rank, realFactorOrbitals.
void ParticleHoleCoulombVertexDecomposition::fit(int64_t iterationsCount)
Performs one iteration in fitting the factor orbitals and the Coulomb factors according to the given algorithm.
References sisi4s::composeCanonicalPolyadicDecompositionTensors, Delta, sisi4s::fitRegularizedAlternatingLeastSquaresFactor, sisi4s::frobeniusNorm, Gamma0Gai, GammaGai, LambdaGR, LOG, normalizedFactorOrbitals, normalizePi, PiaR, PiiR, realFactorOrbitals, realizePi, regularizationEstimatorLambdaGR, regularizationEstimatorPiaR, regularizationEstimatorPiiR.
Referenced by run.
void ParticleHoleCoulombVertexDecomposition::dryFit(DryTensor< complex > *GammaGai, DryTensor< complex > *PiaR, DryTensor< complex > *PiiR, DryTensor< complex > *LambdaGR, DryTensor< complex > *Gamma0Gai)
Performs a dry run of one iteration in fitting the factor orbitals and the Coulomb factors according to the given algorithm.
References sisi4s::dryComposeCanonicalPolyadicDecompositionTensors, sisi4s::dryFitRegularizedAlternatingLeastSquaresFactor, Gamma0Gai, GammaGai, LambdaGR, PiaR, PiiR.
Referenced by dryRun.
void ParticleHoleCoulombVertexDecomposition::normalizePi(CTF::Tensor< complex > &Pi)
Normalizes the given factor orbitals, such that ${\Pi^\ast}^{qR}\Pi_{qR} = \delta_{qq}$.
References sisi4s::frobeniusNorm, LOG, sisi4s::Pi.
Referenced by fit, run.
void ParticleHoleCoulombVertexDecomposition::realizePi(CTF::Tensor< complex > &Pi)
Discards the imaginary part of the given factor orbitals.
References sisi4s::Pi.
Referenced by fit, run.
void ParticleHoleCoulombVertexDecomposition::evaluateMp2Error()
Evaluates and prints the error of the MP2 energy between the current decomposition and the full MP2 energy.
References evaluateMp2, Gamma0Gai, LOG, mp2Energy.
Referenced by run.
double ParticleHoleCoulombVertexDecomposition::evaluateMp2(CTF::Tensor< complex > &Gamma)
Evaluates the MP2 energy for the given Coulomb vertex.
References sisi4s::fromComplexTensor, sisi4s::Algorithm::getTensorArgument.
Referenced by evaluateMp2Error, run.
void ParticleHoleCoulombVertexDecomposition::dryEvaluateMp2(DryTensor< complex > &Gamma)
Performs a dry run of evaluating the MP2 energy for the given Coulomb vertex.
References sisi4s::Algorithm::getTensorArgument, sisi4s::DryTensor< F >::lens, sisi4s::DryTensor< F >::syms, sisi4s::DryTensor< F >::use.
Referenced by dryRun.