sisi4s::PseudoInverseSvd
CTF::Matrix<F> sisi4s::PseudoInverseSvd< F >::inverse
Referenced by sisi4s::PseudoInverseSvd< F >::PseudoInverseSvd.
template PseudoInverseSvd::PseudoInverseSvd(Tensor< F > &A, double epsilon=1e-12)
References sisi4s::PseudoInverseSvd< F >::inverse, sisi4s::ScaLapackMatrix< F >::write.
template CTF::Matrix< sisi4s::Complex64 > & PseudoInverseSvd::get()
References inverse.
Referenced by sisi4s::fitAlternatingLeastSquaresFactor, sisi4s::fitRegularizedAlternatingLeastSquaresFactor, sisi4s::BasisSetExtrapolation::invertQGG.