sisi4s::EigenSystemDavidson
typedef V::FieldType sisi4s::EigenSystemDavidson< H, P, V >::F
H* sisi4s::EigenSystemDavidson< H, P, V >::h
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
int sisi4s::EigenSystemDavidson< H, P, V >::eigenVectorsCount
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
P* sisi4s::EigenSystemDavidson< H, P, V >::p
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
const struct sisi4s::EigenSystemDavidson sisi4s::EigenSystemDavidson< H, P, V >::tolerance
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
unsigned int sisi4s::EigenSystemDavidson< H, P, V >::maxBasisSize
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
unsigned int sisi4s::EigenSystemDavidson< H, P, V >::maxIterations
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
unsigned int sisi4s::EigenSystemDavidson< H, P, V >::minIterations
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
std::vector<int> sisi4s::EigenSystemDavidson< H, P, V >::refreshIterations
Referenced by sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
bool sisi4s::EigenSystemDavidson< H, P, V >::refreshOnMaxBasisSizeValue
Referenced by sisi4s::EigenSystemDavidson< H, P, V >::refreshOnMaxBasisSize, sisi4s::EigenSystemDavidson< H, P, V >::refreshOnMaxBasisSize.
std::vector<complex> sisi4s::EigenSystemDavidson< H, P, V >::eigenValues
Referenced by sisi4s::EigenSystemDavidson< H, P, V >::getEigenValues, sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
std::vector<V> sisi4s::EigenSystemDavidson< H, P, V >::rightEigenVectors
Referenced by sisi4s::EigenSystemDavidson< H, P, V >::getRightEigenVectors, sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
std::vector<V> sisi4s::EigenSystemDavidson< H, P, V >::leftEigenVectors
Referenced by sisi4s::EigenSystemDavidson< H, P, V >::getLeftEigenVectors, sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
double sisi4s::EigenSystemDavidson< H, P, V >::energy
double sisi4s::EigenSystemDavidson< H, P, V >::vectors
sisi4s::EigenSystemDavidson< H, P, V >::EigenSystemDavidson(H *h_, const int eigenVectorsCount_, P *p_, const double toleranceVectors, const double toleranceEnergy, const unsigned int maxBasisSize_, const unsigned int maxIterations_, const unsigned int minIterations_)
...
h object representing the matrix whose eigen system is sought offering the following method: V right_apply(V &v); Also, if the dual version of the Davidson algorithm is to be used h should offer the leftApply method V leftApply(V &v); returning the action of h on v standing right of h. eigenVectorsCount the number of eigenvalues and vectors to be computed. p object representing the preconditioner offering the following method: std::vector<V> getInitialBasis(int eigenVectorsCount); returning an initial guess the basis consisting of eigenVectorsCount vectors. V getCorrection(const complex eigenValue, V &residuum); computing the estimated correction for the k-th eigenvector given its eigenvalue and the residuum of the current k-th estimated eigenvector. tolerance the targeted relative tolerance to be met by all residua. maxBasisSize the maximum allowed number of vectors representing eigenvectors. dualVersion If the dual version of the algorithm is to be used. The dual version of the algorithm calculates both the right and left eigenvectors of the h object. If the dual version is not to be used then only the right eigenvectors are to be calculated. refreshIterations This vector of integers represents the iterations where the refreshment should be done. Refreshment meaning that the trial Davidson basis should be thrown away and only keep the current approximations to the eigenvectors.
virtual void sisi4s::EigenSystemDavidson< H, P, V >::run()=0
const std::vector< complex > & sisi4s::EigenSystemDavidson< H, P, V >::getEigenValues() const
References sisi4s::EigenSystemDavidson< H, P, V >::eigenValues.
Referenced by sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run.
const std::vector< V > & sisi4s::EigenSystemDavidson< H, P, V >::getRightEigenVectors() const
References sisi4s::EigenSystemDavidson< H, P, V >::rightEigenVectors.
Referenced by sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run.
const std::vector< V > & sisi4s::EigenSystemDavidson< H, P, V >::getLeftEigenVectors() const
References sisi4s::EigenSystemDavidson< H, P, V >::leftEigenVectors.
void sisi4s::EigenSystemDavidson< H, P, V >::refreshOnMaxBasisSize(const bool value)
Controls if the Davidson algorithm should make a refreshment of the basis whenever the maximal basis size has been attained.
value If value is true, it will be refreshed, otherwise not.
References sisi4s::EigenSystemDavidson< H, P, V >::refreshOnMaxBasisSizeValue.
Referenced by sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run.
bool sisi4s::EigenSystemDavidson< H, P, V >::refreshOnMaxBasisSize()
Check wether or not the basis should be refreshed whenever the maximal basis size has been reached.
References sisi4s::EigenSystemDavidson< H, P, V >::refreshOnMaxBasisSizeValue.