sisi4s::BasisSetExtrapolation
AlgorithmRegistrar< BasisSetExtrapolation > BasisSetExtrapolation::registrar_
virtual std::string sisi4s::BasisSetExtrapolation::getName()
BasisSetExtrapolation::BasisSetExtrapolation(std::vector< Argument > const &argumentList)
BasisSetExtrapolation::~BasisSetExtrapolation()
void BasisSetExtrapolation::run()
References evaluateQGG, EXCEPTION, fitF12, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, invertQGG, LOG.
void BasisSetExtrapolation::evaluateQGG(int orbitalPairStart, int orbtialPairEnd, int slice)
References sisi4s::conjugate, EXCEPTION, sisi4s::fromComplexTensor, sisi4s::Algorithm::isArgumentGiven, sisi4s::Vector< F, D >::length, LOG, NEW, PTR, sisi4s::sqrt.
Referenced by run.
void BasisSetExtrapolation::fitF12(int type, real minG, real maxG)
References calculateNewSF, CLI::detail::dummy, EXCEPTION, sisi4s::Algorithm::getIntegerArgument, sisi4s::Algorithm::getRealArgument, LOG, sisi4s::Algorithm::setRealArgument, sisi4s::sqrt, sisi4s::Sisi4s::world.
Referenced by run.
void BasisSetExtrapolation::calculateNewSF(int type, real gamma, Tensor< double > *coulombKernel, Tensor< double > *newSF, Tensor< double > *resNewSF)
References sisi4s::Algorithm::getRealArgument.
Referenced by fitF12.
void BasisSetExtrapolation::invertQGG()
References EXCEPTION, sisi4s::PseudoInverseSvd< F >::get, LOG.
Referenced by run.