sisi4s::FockVector
typedef F sisi4s::FockVector< F >::FieldType
std::vector<std::shared_ptr< Tensor<F> > > sisi4s::FockVector< F >::component_tensors
Referenced by sisi4s::FockVector< F >::FockVector, sisi4s::FockVectorNdCanonical< F, N, StartDimension >::FockVectorNdCanonical, sisi4s::SDFockVector< F >::SDFockVector, sisi4s::SDFockVector< F >::SDFockVector, sisi4s::SDFockVector< F >::SDFockVector, sisi4s::SDTFockVector< F >::SDTFockVector, sisi4s::SFockVector< F >::SFockVector, sisi4s::SFockVector< F >::SFockVector, sisi4s::FockVector< F >::braket, sisi4s::FockVector< F >::build_index_translation, sisi4s::FockVector< F >::checkCompatibilityTo, sisi4s::FockVector< F >::checkDualCompatibility, sisi4s::FockVector< F >::conjugateTranspose, sisi4s::FockVector< F >::copy_components, sisi4s::FockVector< F >::dot, sisi4s::ClusterSinglesDoublesAlgorithm::estimateAmplitudesFromResiduum, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_components_count, sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::FockVector< F >::operator*=, sisi4s::FockVector< F >::operator+=, sisi4s::FockVector< F >::operator-=, sisi4s::operator<<, sisi4s::FockVector< F >::operator=, sisi4s::FockVector< F >::operator=, sisi4s::SDFockVector< F >::operator=, sisi4s::SDTFockVector< F >::operator=, sisi4s::SFockVector< F >::operator=, sisi4s::FockVector< F >::readLocal, sisi4s::FockVector< F >::write.
std::vector<std::string> sisi4s::FockVector< F >::component_indices
Referenced by sisi4s::FockVectorNdCanonical< F, N, StartDimension >::FockVectorNdCanonical, sisi4s::SDFockVector< F >::SDFockVector, sisi4s::SDFockVector< F >::SDFockVector, sisi4s::SDFockVector< F >::SDFockVector, sisi4s::SDTFockVector< F >::SDTFockVector, sisi4s::SFockVector< F >::SFockVector, sisi4s::SFockVector< F >::SFockVector, sisi4s::FockVector< F >::checkCompatibilityTo, sisi4s::FockVector< F >::conjugateTranspose, sisi4s::FockVector< F >::get_indices, sisi4s::FockVector< F >::get_indices, sisi4s::CcsdPreconditioner< F >::getCorrection, sisi4s::IPCcsdPreconditioner< F >::getCorrection, sisi4s::EACcsdPreconditioner< F >::getCorrection, sisi4s::CISPreconditioner< F >::getCorrection, sisi4s::FockVector< F >::operator+=, sisi4s::FockVector< F >::operator=, sisi4s::FockVector< F >::operator=, sisi4s::SDFockVector< F >::operator=, sisi4s::SDTFockVector< F >::operator=, sisi4s::SFockVector< F >::operator=, sisi4s::FockVector< F >::readLocal.
std::vector<size_t> sisi4s::FockVector< F >::index_ends
The end of the FockVector index range for each component. This vector is used for translating component number and indices into FockVector indicies.
Referenced by sisi4s::FockVector< F >::build_index_translation, sisi4s::FockVector< F >::fromIndex, sisi4s::FockVector< F >::get_dimension, sisi4s::FockVector< F >::get_index.
sisi4s::FockVector< F >::FockVector()
Default constructor for an empty Fock vector without elements.
sisi4s::FockVector< F >::FockVector(FockVector< F > &&a)
Move constructor taking possession of the tensors owned by a.
References sisi4s::FockVector< F >::build_index_translation.
sisi4s::FockVector< F >::FockVector(const FockVector< F > &a)
Copy constructor copying the tensors owned by a.
References sisi4s::FockVector< F >::build_index_translation, sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::copy_components.
sisi4s::FockVector< F >::FockVector(const std::vector< std::shared_ptr< Tensor< F > > > &tensors, const std::vector< std::string > &indices)
Move constructor taking possession of the tensors given.
References sisi4s::FockVector< F >::build_index_translation.
sisi4s::FockVector< F >::FockVector(TensorsIterator tensorsBegin, TensorsIterator tensorsEnd, IndicesIterator indicesBegin, IndicesIterator indicesEnd)
Move constructor taking possession of the tensors given by the iterators.
References sisi4s::FockVector< F >::build_index_translation.
const std::shared_ptr< Tensor< F > > & sisi4s::FockVector< F >::get(const size_t i) const
Retrieves the i-th component tensor. Note that the Tensor is not const since rearrangement may be required also in non-modifying tensor operations.
References sisi4s::FockVector< F >::component_tensors.
Referenced by sisi4s::FockVector< F >::braket, sisi4s::FockVector< F >::build_index_translation, sisi4s::FockVector< F >::checkDualCompatibility, sisi4s::FockVector< F >::conjugateTranspose, sisi4s::FockVector< F >::dot, sisi4s::ClusterSinglesDoublesAlgorithm::estimateAmplitudesFromResiduum, sisi4s::CcsdPreconditioner< F >::getCorrection, sisi4s::IPCcsdPreconditioner< F >::getCorrection, sisi4s::EACcsdPreconditioner< F >::getCorrection, sisi4s::CISPreconditioner< F >::getCorrection, sisi4s::ClusterSinglesDoublesAlgorithm::getEnergy, sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::IPCcsdPreconditioner< F >::getInitialBasis, sisi4s::EACcsdPreconditioner< F >::getInitialBasis, sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum, sisi4s::CcsdEnergyFromCoulombIntegralsReference::getResiduum, sisi4s::DrccdEnergyFromCoulombIntegrals::getResiduum, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumSth, sisi4s::UccsdAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UccsdtqAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UrpaAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::CcsdtEnergyFromCoulombIntegrals::getResiduumTemplate, sisi4s::CoulombVertexDecomposition::iterateQuadraticFactor, sisi4s::SimilarityTransformedHamiltonian< F >::leftApply_hirata, sisi4s::SimilarityTransformedHamiltonian< F >::leftApplyIntermediates, sisi4s::FockVector< F >::operator*=, sisi4s::FockVector< F >::operator+=, sisi4s::FockVector< F >::operator-=, sisi4s::operator<<, sisi4s::FockVector< F >::readLocal, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_CISD, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_hirata, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_hirata, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_hirata_CCSD_EA, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_hirata_CCSD_IP, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_hirata_RPA, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_Intermediates, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_Intermediates_CCSD_EA, sisi4s::SimilarityTransformedHamiltonian< F >::right_apply_Intermediates_CCSD_IP, sisi4s::ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors, sisi4s::ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors, sisi4s::ClusterSinglesDoublesAlgorithm::sliceCoupledCoulombIntegrals, sisi4s::ClusterSinglesDoublesAlgorithm::storeAmplitudes, sisi4s::SimilarityTransformedHamiltonian< F >::structureFactor, sisi4s::FockVector< F >::write.
std::shared_ptr< Tensor< F > > & sisi4s::FockVector< F >::get(const size_t i)
Retrieves the i-th component tensor.
References sisi4s::FockVector< F >::component_tensors.
const std::string & sisi4s::FockVector< F >::get_indices(const size_t i) const
Retrieves the i-th component indices.
References sisi4s::FockVector< F >::component_indices.
Referenced by sisi4s::FockVector< F >::braket, sisi4s::FockVector< F >::conjugateTranspose, sisi4s::FockVector< F >::dot, sisi4s::ClusterSinglesDoublesAlgorithm::estimateAmplitudesFromResiduum, sisi4s::FockVector< F >::operator*=, sisi4s::FockVector< F >::operator-=, sisi4s::operator<<.
std::string & sisi4s::FockVector< F >::get_indices(const size_t i)
Retrieves the i-th component indices as modifiable string.
References sisi4s::FockVector< F >::component_indices.
FockVector< F > & sisi4s::FockVector< F >::operator=(const FockVector< F > &&a)
Move assignment operator taking possession of the tensors owned by a.
References sisi4s::FockVector< F >::build_index_translation, sisi4s::FockVector< F >::component_indices, sisi4s::FockVector< F >::component_tensors.
FockVector< F > & sisi4s::FockVector< F >::operator=(const FockVector< F > &a)
Copy assignment operator copying the tensors owned by a.
References sisi4s::FockVector< F >::build_index_translation, sisi4s::FockVector< F >::component_indices, sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::copy_components.
FockVector< F > & sisi4s::FockVector< F >::operator+=(const FockVector< F > &a)
Add-to assignment operator adding each component of a to the respective component of this FockVector.
References sisi4s::FockVector< F >::checkCompatibilityTo, sisi4s::FockVector< F >::component_indices, sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get.
FockVector< F > & sisi4s::FockVector< F >::operator-=(const FockVector< F > &a)
Subtract-from assignment operator subtracting each component of a from the respective component of this FockVector.
References sisi4s::FockVector< F >::checkCompatibilityTo, sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_indices.
FockVector< F > & sisi4s::FockVector< F >::operator*=(const F s)
Multiply-by assignment operator scalar multiplying each component each component of this FockVector by the given scalar.
References sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_indices.
FockVector< F > sisi4s::FockVector< F >::conjugateTranspose() const
Creates and returns the conjugate transpose of this FockVector. The first and the second half of the inidices in each component are swapped for the transposition. For real types F the conjugation does nothing.
References sisi4s::FockVector< F >::component_indices, sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_indices, NEW.
Referenced by sisi4s::CcsdEquationOfMotionDavidson::run.
F sisi4s::FockVector< F >::braket(const FockVector< F > &ket) const
Returns the matrix product of this bra-FockVector with the given dual ket-FockVector ket.
References sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_indices.
F sisi4s::FockVector< F >::dot(const FockVector< F > &a) const
Returns the inner product of this ket-FockVector with the given ket-FockVector a. The elements of this FockVector are conjugated in the inner product, i.e. this->dot(a) yields the same results as this->conjugateTranspose().braket(a).
References sisi4s::FockVector< F >::checkCompatibilityTo, sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_indices.
Referenced by sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::IPCcsdPreconditioner< F >::getInitialBasis, sisi4s::EACcsdPreconditioner< F >::getInitialBasis, sisi4s::CISPreconditioner< F >::getInitialBasis.
size_t sisi4s::FockVector< F >::get_components_count() const
Get the number of component tensors of this FockVector.
References sisi4s::FockVector< F >::component_tensors.
Referenced by sisi4s::CcsdPreconditioner< F >::getCorrection, sisi4s::IPCcsdPreconditioner< F >::getCorrection, sisi4s::EACcsdPreconditioner< F >::getCorrection, sisi4s::CISPreconditioner< F >::getCorrection.
size_t sisi4s::FockVector< F >::get_dimension() const
Get the total number of degrees of freedom represented by this FockVector, i.e. the total number of field values contained in all component tensors. The indices used by read and write are between 0 and get_dimension()-1.
References sisi4s::FockVector< F >::index_ends.
size_t sisi4s::FockVector< F >::get_index(const size_t component, const size_t componentIndex) const
\Brief Translates the given component and component index into its element into an index between 0 and get_dimension()-1.
References sisi4s::FockVector< F >::index_ends.
Referenced by sisi4s::FockVector< F >::readLocal.
void sisi4s::FockVector< F >::fromIndex(const size_t index, size_t &component, size_t &componentIndex) const
\Brief Translates the given index between 0 and get_dimension()-1 into a component number and component index into the corresponding component tensor.
References EXCEPTION, sisi4s::FockVector< F >::index_ends.
Referenced by sisi4s::FockVector< F >::write.
std::vector< std::pair< size_t, F > > sisi4s::FockVector< F >::readLocal() const
Reads out all locally stored values together with their respective indices. The indices are between 0 and get_dimension()-1.
References sisi4s::FockVector< F >::component_indices, sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::get_index.
void sisi4s::FockVector< F >::write(const std::vector< std::pair< size_t, F > > &elements)
Writes the given values together with their respective indices. The indices are between 0 and get_dimension()-1.
References sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::fromIndex, sisi4s::FockVector< F >::get.
Referenced by sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::IPCcsdPreconditioner< F >::getInitialBasis, sisi4s::EACcsdPreconditioner< F >::getInitialBasis, sisi4s::CISPreconditioner< F >::getInitialBasis.
void sisi4s::FockVector< F >::build_index_translation()
\Brief Builds the index ends vector needed for the index translation methods get_index and fromIndex.
References sisi4s::FockVector< F >::component_tensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::index_ends.
Referenced by sisi4s::FockVector< F >::FockVector, sisi4s::FockVector< F >::FockVector, sisi4s::FockVector< F >::FockVector, sisi4s::FockVector< F >::FockVector, sisi4s::FockVector< F >::operator=, sisi4s::FockVector< F >::operator=.
void sisi4s::FockVector< F >::copy_components(const std::vector< std::shared_ptr< Tensor< F > > > &components)
Sets this FockVector's component tensors by copying the given component tensors. Called by copy constructors and copy assignments.
References sisi4s::FockVector< F >::component_tensors, NEW.
Referenced by sisi4s::FockVector< F >::FockVector, sisi4s::FockVector< F >::operator=.
void sisi4s::FockVector< F >::checkDualCompatibility(const FockVector< F > &a) const
Check if two FockVectors are transpose of each other by swapping the first and the second half of the component indices.
References sisi4s::FockVector< F >::checkCompatibilityTo, sisi4s::FockVector< F >::component_tensors, EXCEPTION, sisi4s::FockVector< F >::get.
void sisi4s::FockVector< F >::checkCompatibilityTo(const FockVector< F > &a) const
References sisi4s::FockVector< F >::component_indices, sisi4s::FockVector< F >::component_tensors, EXCEPTION.
Referenced by sisi4s::FockVector< F >::checkDualCompatibility, sisi4s::FockVector< F >::dot, sisi4s::FockVector< F >::operator+=, sisi4s::FockVector< F >::operator-=.