sisi4s::EigenSystemDavidsonMono
typedef V::FieldType sisi4s::EigenSystemDavidsonMono< H, P, V >::F
sisi4s::EigenSystemDavidsonMono< H, P, V >::EigenSystemDavidsonMono(H *h_, const int eigenVectorsCount_, P *p_, const double toleranceVectors, const double toleranceEnergy, const unsigned int maxBasisSize_, const unsigned int maxIterations_, const unsigned int minIterations_)
void sisi4s::EigenSystemDavidsonMono< H, P, V >::run()
References sisi4s::dot, sisi4s::EigenSystemDavidson< H, P, V >::eigenValues, sisi4s::EigenSystemDavidson< H, P, V >::eigenVectorsCount, FILE, sisi4s::LapackMatrix< F >::getColumns, sisi4s::EigenSystemDavidson< H, P, V >::h, sisi4s::EigenSystemDavidson< H, P, V >::leftEigenVectors, LOG, sisi4s::EigenSystemDavidson< H, P, V >::maxBasisSize, sisi4s::EigenSystemDavidson< H, P, V >::maxIterations, sisi4s::EigenSystemDavidson< H, P, V >::minIterations, OUT, sisi4s::EigenSystemDavidson< H, P, V >::p, sisi4s::EigenSystemDavidson< H, P, V >::refreshIterations, sisi4s::EigenSystemDavidson< H, P, V >::rightEigenVectors, sisi4s::EigenSystemDavidson< H, P, V >::tolerance.
Referenced by sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run.