sisi4s::Sisi4s
World * Sisi4s::world
Referenced by sisi4s::DefaultRandomEngine::DefaultRandomEngine, sisi4s::DiisMixer< F >::DiisMixer, sisi4s::FockVectorNdCanonical< F, N, StartDimension >::FockVectorNdCanonical, sisi4s::SDTFockVector< F >::SDTFockVector, IntegralParser::allocateTensor, sisi4s::DiisMixer< F >::append, sisi4s::NaturalTransitionOrbitalsFromRhoAI::buildTransformations, sisi4s::CoulombIntegralsFromVertex::calculateComplexIntegrals, sisi4s::CoulombIntegralsFromVertex::calculateRealIntegrals, sisi4s::FiniteSizeCorrection::calculateRealStructureFactor, sisi4s::ClusterSinglesDoublesAlgorithm::createAmplitudes, Unrestricter::doEigenEnergies, Unrestricter::doVertex, eigenToCtfMatrix, sisi4s::BasisSetExtrapolation::fitF12, SzOperator< F >::getAB, sisi4s::EomOneBodyReducedDensityMatrix< F >::getAB, sisi4s::ClusterSinglesDoublesAlgorithm::getEnergy, sisi4s::EomOneBodyReducedDensityMatrix< F >::getIA, SzOperator< F >::getIJ, sisi4s::EomOneBodyReducedDensityMatrix< F >::getIJ, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumSth, sisi4s::UccsdAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UccsdtAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UccsdtqAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::UrpaAmplitudesFromCoulombIntegrals::getResiduumTemplate, sisi4s::FiniteSizeCorrection::interpolation3D, listHosts, main, sisi4s::SDTFockVector< F >::operator=, printBanner, printStatistics, sisi4s::TensorIo::readBinary, sisi4s::TensorIo::readBinaryHeader, sisi4s::TensorIo::readText, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdPerturbativeTriples::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::ComplexTensorReader::run, sisi4s::CoulombIntegralsFromGaussian::run, sisi4s::CoulombVertexReader::run, sisi4s::DoublesAmplitudesFromVertex::run, sisi4s::FockMatrixFromCoulombIntegrals::run, sisi4s::GenerateRandomComplexMatrix::run, sisi4s::GenerateRandomMatrix::run, sisi4s::GenerateRandomTensor::run, sisi4s::HartreeFockFromCoulombIntegrals::run, sisi4s::HartreeFockFromGaussian::run, sisi4s::MeanCorrelationHoleDepth::run, sisi4s::MoReader::run, sisi4s::Mp2NaturalOrbitals::run, sisi4s::NaturalTransitionOrbitalsFromRhoAI::run, sisi4s::OneBodyFromGaussian::run, sisi4s::ParenthesisTriples::run, sisi4s::ParticleHoleCoulombVertexReader::run, sisi4s::PerturbativeTriples::run, sisi4s::TensorReader::run, sisi4s::TensorReduceijij::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UegVertexGenerator::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::UPerturbativeTriples::run, run, sisi4s::PerturbativeTriples::runInMemory, sisi4s::PerturbativeTriples::runPiecuch, sisi4s::CoulombVertexReader::unrestrictEigenEnergies, sisi4s::CoulombVertexReader::unrestrictVertex.
Options * Sisi4s::options
Referenced by dryRun, main, run.
Sisi4s::Sisi4s()
Sisi4s::~Sisi4s()
void Sisi4s::run()
References sisi4s::Options::cc4s, EMIT, sisi4s::Time::getFractionalSeconds, sisi4s::Options::inFile, listHosts, LOG, options, OUT, sisi4s::InputFileParser< InputFileFormat::YAML >::parse, sisi4s::InputFileParser< InputFileFormat::CC4S >::parse, printBanner, printStatistics, world.
void Sisi4s::dryRun()
References EMIT, sisi4s::Options::inFile, LOG, sisi4s::DryMemory::maxTotalSize, options, OUT, sisi4s::InputFileParser< InputFileFormat::YAML >::parse, printBanner.
bool Sisi4s::isDebugged()
References LOG.
Referenced by main.
void Sisi4s::printBanner()
References EMIT, LOG, OUT, world.
Referenced by dryRun, run.
void Sisi4s::printStatistics()
References EMIT, LOG, sisi4s::MpiCommunicator::reduce, world.
Referenced by run.
void Sisi4s::listHosts()
References EMIT, world.
Referenced by run.