DiisMixer.cxx
MIXER_REGISTRAR_DEFINITION(DiisMixer)
std::vector< double > inverse(std::vector< double > matrix, int N)
References dsysv_, LOG.
Referenced by sisi4s::DiisMixer< F >::append, sisi4s::IterativePseudoInverse< F >::get, sisi4s::DryIterativePseudoInverse< F >::get, sisi4s::PseudoInverseHermitianSvd< F >::get, sisi4s::DryPseudoInverseHermitianSvd< F >::get, sisi4s::PseudoInverseSvd< F >::get, sisi4s::DryPseudoInverseSvd< F >::get, sisi4s::IterativePseudoInverse< F >::iterate, sisi4s::IterativePseudoInverse< F >::iterateQuadratically.
std::vector< sisi4s::complex > inverse(std::vector< sisi4s::complex > matrix, int N)
PTR(const FockVector< F >) DiisMixer< F >