HartreeFockFromGaussian.cxx
LOGGER
IF_GIVEN
Tensor< double > eigenToCtfMatrix(const Eigen::MatrixXd &m)
References sisi4s::Sisi4s::world.
Referenced by sisi4s::HartreeFockFromGaussian::run.
double getNuclearRepulsionEnergy(std::vector< libint2::Atom > &structure)
References LOGGER, sisi4s::sqrt.
Referenced by sisi4s::HartreeFockFromGaussian::run.
Eigen::MatrixXd getOneBodyIntegrals_(const libint2::BasisSet &shells, const libint2::Operator obtype, const std::vector< libint2::Atom > &atoms)
References atom, ShellInfo::begin, ShellInfo::size.
Referenced by sisi4s::HartreeFockFromGaussian::run.
Eigen::MatrixXd getTwoBodyFock(const libint2::BasisSet &shells, const Eigen::MatrixXd &D)
Referenced by sisi4s::HartreeFockFromGaussian::run.