Lapack.hpp
void dgeev_(const char *jobvLeft, const char *jobvRight, const int *n, sisi4s::Float64 *a, const int *lda, sisi4s::Float64 *wReal, sisi4s::Float64 *wImag, sisi4s::Float64 *vLeft, const int *ldvLeft, sisi4s::Float64 *vRight, const int *ldvRight, sisi4s::Float64 *work, const int *workSize, int *info)
void zgeev_(const char *jobvLeft, const char *jobvRight, const int *n, const sisi4s::Complex64 *a, const int *lda, sisi4s::Complex64 *w, sisi4s::Complex64 *vLeft, const int *ldvLeft, sisi4s::Complex64 *vRight, const int *ldvRight, sisi4s::Complex64 *work, const int *workSize, sisi4s::Float64 *rwork, int *info)
Referenced by sisi4s::LapackGeneralEigenSystem< complex >::LapackGeneralEigenSystem.
void dsyev_(const char *jobz, const char *uplo, const int *n, sisi4s::Float64 *a, const int *lda, sisi4s::Float64 *w, sisi4s::Float64 *work, const int *lwork, int *info)
Referenced by sisi4s::Mp2NaturalOrbitals::run, sisi4s::PQRSCoulombIntegralsToVertex::run.
void dsysv_(const char *uplo, const int *n, const int *m, sisi4s::Float64 *a, const int *lda, const int *ipiv, sisi4s::Float64 *b, const int *ldb, sisi4s::Float64 *work, const int *lwork, const int *info)
Referenced by inverse.
void dgetrf_(const int *m, const int *n, sisi4s::Float64 *a, const int *lda, const int *rowPermutation, int *info)
void zgetrf_(const int *m, const int *n, sisi4s::Complex64 *a, const int *lda, const int *rowPermutation, int *info)
Referenced by sisi4s::LapackInverse< Complex64 >::LapackInverse.
void dgetri_(const int *n, sisi4s::Float64 *a, const int *lda, const int *rowPermutation, sisi4s::Float64 *work, const int *workSize, int *info)
void zgetri_(const int *n, sisi4s::Complex64 *a, const int *lda, const int *rowPermutation, sisi4s::Complex64 *work, const int *workSize, int *info)
Referenced by sisi4s::LapackInverse< Complex64 >::LapackInverse.
void dger_(const int *M, const int *N, const double *alpha, const double *X, const int *incx, const double *Y, const int *incy, double *A, const int *lda)