ghc::filesystem::detail
utf8_states_t
portable_error
using ghc::filesystem::detail::EnableBitmask = typedef typename std::enable_if<std::is_same<Enum, perms>::value || std::is_same<Enum, perm_options>::value || std::is_same<Enum, copy_options>::value || std::is_same<Enum, directory_options>::value, Enum>::type
void ghc::filesystem::detail::appendUTF8(std::string &str, uint32_t unicode)
References appendUTF8.
Referenced by appendUTF8.
bool ghc::filesystem::detail::is_surrogate(uint32_t c)
References in_range.
bool ghc::filesystem::detail::is_high_surrogate(uint32_t c)
bool ghc::filesystem::detail::is_low_surrogate(uint32_t c)
unsigned ghc::filesystem::detail::consumeUtf8Fragment(const unsigned state, const uint8_t fragment, uint32_t &codepoint)
References S_RJCT.
Referenced by validUtf8.
std::error_code ghc::filesystem::detail::make_error_code(portable_error err)
References exists, invalid_argument, is_a_directory, none, not_found, not_implemented, not_supported.
Referenced by ghc::filesystem::copy, ghc::filesystem::copy_file, ghc::filesystem::hard_link_count, ghc::filesystem::permissions, ghc::filesystem::read_symlink, ghc::filesystem::remove_all.
std::error_code ghc::filesystem::detail::make_system_error(int err=0)
Referenced by ghc::filesystem::directory_iterator::impl::impl, ghc::filesystem::absolute, ghc::filesystem::copy_file, ghc::filesystem::create_directory, create_hardlink, create_symlink, ghc::filesystem::current_path, ghc::filesystem::current_path, ghc::filesystem::equivalent, ghc::filesystem::file_size, ghc::filesystem::hard_link_count, ghc::filesystem::directory_iterator::impl::increment, ghc::filesystem::last_write_time, ghc::filesystem::permissions, ghc::filesystem::remove, ghc::filesystem::rename, ghc::filesystem::resize_file, resolveSymlink, ghc::filesystem::space, status_ex, symlink_status_ex, ghc::filesystem::temp_directory_path.
file_type ghc::filesystem::detail::file_type_from_dirent_impl(const T &, std::false_type)
References ghc::filesystem::none.
Referenced by file_type_from_dirent.
file_type ghc::filesystem::detail::file_type_from_dirent_impl(const T &t, std::true_type)
References ghc::filesystem::block, ghc::filesystem::character, ghc::filesystem::directory, ghc::filesystem::fifo, ghc::filesystem::none, ghc::filesystem::regular, ghc::filesystem::socket, ghc::filesystem::symlink, ghc::filesystem::unknown.
file_type ghc::filesystem::detail::file_type_from_dirent(const T &t)
References file_type_from_dirent_impl.
Referenced by ghc::filesystem::directory_iterator::impl::copyToDirEntry.
bool ghc::filesystem::detail::in_range(uint32_t c, uint32_t lo, uint32_t hi)
Referenced by is_surrogate.
bool ghc::filesystem::detail::validUtf8(const std::string &utf8String)
References consumeUtf8Fragment, S_RJCT, S_STRT.
StringType ghc::filesystem::detail::fromUtf8(const Utf8String &utf8String, const typename StringType::allocator_type &alloc=typename StringType::allocator_type())
StringType ghc::filesystem::detail::fromUtf8(const charT(&utf8String)[N])
std::string ghc::filesystem::detail::toUtf8(const strT &unicodeString)
Referenced by ghc::filesystem::u8arguments::u8arguments, ghc::filesystem::path::assign, ghc::filesystem::path::string, systemErrorText, toUtf8, ghc::filesystem::path::u8string.
std::string ghc::filesystem::detail::toUtf8(const charT *unicodeString)
References toUtf8.
bool ghc::filesystem::detail::startsWith(const strT &what, const strT &with)
Referenced by resolveSymlink.
bool ghc::filesystem::detail::endsWith(const strT &what, const strT &with)
Referenced by resolveSymlink.
bool ghc::filesystem::detail::equals_simple_insensitive(const path::value_type *str1, const path::value_type *str2)
Referenced by ghc::filesystem::u8arguments::u8arguments.
int ghc::filesystem::detail::compare_simple_insensitive(const path::value_type *str1, size_t len1, const path::value_type *str2, size_t len2)
Referenced by ghc::filesystem::path::compare.
const char * ghc::filesystem::detail::strerror_adapter(char *gnu, char *)
Referenced by systemErrorText.
const char * ghc::filesystem::detail::strerror_adapter(int posix, char *buffer)
std::string ghc::filesystem::detail::systemErrorText(ErrorNumber code=0)
References strerror_adapter, toUtf8.
Referenced by ghc::filesystem::last_write_time.
void ghc::filesystem::detail::create_symlink(const path &target_name, const path &new_symlink, bool, std::error_code &ec)
References ghc::filesystem::path::c_str, make_system_error, ghc::filesystem::symlink.
Referenced by ghc::filesystem::create_directory_symlink, ghc::filesystem::create_symlink.
void ghc::filesystem::detail::create_hardlink(const path &target_name, const path &new_hardlink, std::error_code &ec)
References ghc::filesystem::path::c_str, make_system_error.
Referenced by ghc::filesystem::create_hard_link.
file_status ghc::filesystem::detail::file_status_from_st_mode(T mode)
References ghc::filesystem::block, ghc::filesystem::character, ghc::filesystem::directory, ghc::filesystem::fifo, ghc::filesystem::regular, ghc::filesystem::socket, ghc::filesystem::symlink, ghc::filesystem::unknown.
Referenced by status_ex, symlink_status_ex.
path ghc::filesystem::detail::resolveSymlink(const path &p, std::error_code &ec)
References ghc::filesystem::path::c_str, endsWith, GHC_NATIVEWP, make_system_error, ghc::filesystem::path::parent_path, startsWith.
Referenced by ghc::filesystem::read_symlink, status_ex.
bool ghc::filesystem::detail::is_not_found_error(std::error_code &ec)
Referenced by ghc::filesystem::recursive_directory_iterator::increment, ghc::filesystem::remove_all, status_ex, symlink_status_ex.
file_status ghc::filesystem::detail::symlink_status_ex(const path &p, std::error_code &ec, uintmax_t *sz=nullptr, uintmax_t *nhl=nullptr, time_t *lwt=nullptr) noexcept
References ghc::filesystem::path::c_str, file_status_from_st_mode, GHC_NATIVEWP, is_not_found_error, make_system_error, ghc::filesystem::none, ghc::filesystem::not_found, ghc::filesystem::unknown.
Referenced by ghc::filesystem::symlink_status.
file_status ghc::filesystem::detail::status_ex(const path &p, std::error_code &ec, file_status *sls=nullptr, uintmax_t *sz=nullptr, uintmax_t *nhl=nullptr, time_t *lwt=nullptr, int recurse_count=0) noexcept
References ghc::filesystem::path::c_str, ghc::filesystem::path::empty, file_status_from_st_mode, GHC_NATIVEWP, is_not_found_error, make_system_error, ghc::filesystem::none, ghc::filesystem::not_found, resolveSymlink, status_ex, ghc::filesystem::symlink, ghc::filesystem::unknown.
Referenced by ghc::filesystem::hard_link_count, ghc::filesystem::last_write_time, ghc::filesystem::directory_entry::refresh, ghc::filesystem::status, status_ex.