ghc::filesystem
file_type
perms
perm_options
copy_options
directory_options
using ghc::filesystem::file_time_type = typedef std::chrono::time_point<std::chrono::system_clock>
typedef basic_filebuf<char> ghc::filesystem::filebuf
typedef basic_filebuf<wchar_t> ghc::filesystem::wfilebuf
typedef basic_ifstream<char> ghc::filesystem::ifstream
typedef basic_ifstream<wchar_t> ghc::filesystem::wifstream
typedef basic_ofstream<char> ghc::filesystem::ofstream
typedef basic_ofstream<wchar_t> ghc::filesystem::wofstream
typedef basic_fstream<char> ghc::filesystem::fstream
typedef basic_fstream<wchar_t> ghc::filesystem::wfstream
void ghc::filesystem::swap(path &lhs, path &rhs) noexcept
size_t ghc::filesystem::hash_value(const path &p) noexcept
bool ghc::filesystem::operator==(const path &lhs, const path &rhs) noexcept
Referenced by ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::operator!=(const path &lhs, const path &rhs) noexcept
Referenced by ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::operator<(const path &lhs, const path &rhs) noexcept
Referenced by ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::operator<=(const path &lhs, const path &rhs) noexcept
Referenced by ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::operator>(const path &lhs, const path &rhs) noexcept
Referenced by ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::operator>=(const path &lhs, const path &rhs) noexcept
Referenced by ghc::filesystem::directory_entry::operator=.
path ghc::filesystem::operator/(const path &lhs, const path &rhs)
std::basic_ostream< charT, traits > & ghc::filesystem::operator<<(std::basic_ostream< charT, traits > &os, const path &p)
std::basic_istream< charT, traits > & ghc::filesystem::operator>>(std::basic_istream< charT, traits > &is, path &p)
References ghc::filesystem::path::path.
path ghc::filesystem::u8path(const Source &source)
path ghc::filesystem::u8path(InputIterator first, InputIterator last)
directory_iterator ghc::filesystem::begin(directory_iterator iter) noexcept
directory_iterator ghc::filesystem::end(const directory_iterator &) noexcept
recursive_directory_iterator ghc::filesystem::begin(recursive_directory_iterator iter) noexcept
recursive_directory_iterator ghc::filesystem::end(const recursive_directory_iterator &) noexcept
path ghc::filesystem::absolute(const path &p, std::error_code &ec)
References absolute, ghc::filesystem::path::clear, current_path, ghc::filesystem::path::empty, ghc::filesystem::path::filename, GHC_NATIVEWP, ghc::filesystem::path::has_root_directory, ghc::filesystem::path::has_root_name, ghc::filesystem::detail::make_system_error, ghc::filesystem::path::relative_path, ghc::filesystem::path::root_directory, ghc::filesystem::path::root_name.
Referenced by absolute.
path ghc::filesystem::canonical(const path &p, std::error_code &ec)
Referenced by copy, weakly_canonical.
void ghc::filesystem::copy(const path &from, const path &to, std::error_code &ec) noexcept
References copy, none.
Referenced by copy.
void ghc::filesystem::copy(const path &from, const path &to, copy_options options, std::error_code &ec) noexcept
References canonical, copy, copy_file, copy_symlink, copy_symlinks, create_directory, create_hard_link, create_hard_links, create_symlink, create_symlinks, directories_only, equivalent, exists, ghc::filesystem::detail::invalid_argument, ghc::filesystem::detail::is_a_directory, is_directory, is_other, is_regular_file, is_symlink, ghc::filesystem::detail::make_error_code, none, ghc::filesystem::detail::not_found, recursive, skip_symlinks, status, symlink_status.
bool ghc::filesystem::copy_file(const path &from, const path &to, std::error_code &ec) noexcept
References copy_file, none.
Referenced by copy, copy_file.
bool ghc::filesystem::copy_file(const path &from, const path &to, copy_options option, std::error_code &ec) noexcept
References all, equivalent, ghc::filesystem::detail::exists, exists, GHC_NATIVEWP, is_regular_file, last_write_time, ghc::filesystem::detail::make_error_code, ghc::filesystem::detail::make_system_error, none, overwrite_existing, skip_existing, status, update_existing.
void ghc::filesystem::copy_symlink(const path &existing_symlink, const path &new_symlink, std::error_code &ec) noexcept
References create_directory_symlink, create_symlink, exists, is_directory, read_symlink.
Referenced by copy.
bool ghc::filesystem::create_directories(const path &p, std::error_code &ec) noexcept
bool ghc::filesystem::create_directory(const path &p, std::error_code &ec) noexcept
References create_directory.
Referenced by copy, create_directory.
bool ghc::filesystem::create_directory(const path &p, const path &attributes, std::error_code &ec) noexcept
References all, exists, GHC_NATIVEWP, is_directory, ghc::filesystem::detail::make_system_error, status, status_known.
void ghc::filesystem::create_directory_symlink(const path &to, const path &new_symlink, std::error_code &ec) noexcept
References ghc::filesystem::detail::create_symlink.
Referenced by copy_symlink.
void ghc::filesystem::create_symlink(const path &to, const path &new_symlink, std::error_code &ec) noexcept
References ghc::filesystem::detail::create_symlink.
Referenced by copy, copy_symlink.
path ghc::filesystem::current_path(std::error_code &ec)
References ghc::filesystem::path::clear, ghc::filesystem::detail::make_system_error, ghc::filesystem::path::native_format, PATH_MAX.
Referenced by absolute, relative.
void ghc::filesystem::current_path(const path &p, std::error_code &ec) noexcept
References ghc::filesystem::path::clear, GHC_NATIVEWP, ghc::filesystem::detail::make_system_error.
bool ghc::filesystem::exists(file_status s) noexcept
References not_found, status_known.
Referenced by copy, copy_file, copy_symlink, create_directory, exists, is_other, ghc::filesystem::directory_entry::operator=, remove_all, weakly_canonical.
bool ghc::filesystem::exists(const path &p, std::error_code &ec) noexcept
References exists, status, status_known.
bool ghc::filesystem::equivalent(const path &p1, const path &p2, std::error_code &ec) noexcept
References GHC_NATIVEWP, ghc::filesystem::detail::make_system_error.
Referenced by copy, copy_file.
uintmax_t ghc::filesystem::file_size(const path &p, std::error_code &ec) noexcept
References GHC_NATIVEWP, ghc::filesystem::detail::make_system_error.
Referenced by ghc::filesystem::directory_entry::file_size, is_empty, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_block_file(file_status s) noexcept
References block.
Referenced by is_block_file, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_block_file(const path &p, std::error_code &ec) noexcept
References is_block_file, status.
bool ghc::filesystem::is_character_file(file_status s) noexcept
References character.
Referenced by is_character_file, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_character_file(const path &p, std::error_code &ec) noexcept
References is_character_file, status.
bool ghc::filesystem::is_directory(file_status s) noexcept
References directory.
Referenced by copy, copy_symlink, create_directory, is_directory, is_empty, is_other, ghc::filesystem::directory_entry::operator=, remove_all.
bool ghc::filesystem::is_directory(const path &p, std::error_code &ec) noexcept
References is_directory, status.
bool ghc::filesystem::is_empty(const path &p, std::error_code &ec) noexcept
References file_size, is_directory, status.
bool ghc::filesystem::is_fifo(file_status s) noexcept
References fifo.
Referenced by is_fifo, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_fifo(const path &p, std::error_code &ec) noexcept
References is_fifo, status.
bool ghc::filesystem::is_other(file_status s) noexcept
References exists, is_directory, is_regular_file, is_symlink.
Referenced by copy, is_other, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_other(const path &p, std::error_code &ec) noexcept
References is_other, status.
bool ghc::filesystem::is_regular_file(file_status s) noexcept
References regular.
Referenced by copy, copy_file, is_other, is_regular_file, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_regular_file(const path &p, std::error_code &ec) noexcept
References is_regular_file, status.
bool ghc::filesystem::is_socket(file_status s) noexcept
References socket.
Referenced by is_socket, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_socket(const path &p, std::error_code &ec) noexcept
References is_socket, status.
bool ghc::filesystem::is_symlink(file_status s) noexcept
References symlink.
Referenced by copy, is_other, ghc::filesystem::directory_entry::is_other, is_symlink, ghc::filesystem::directory_entry::is_symlink, ghc::filesystem::directory_entry::operator=.
bool ghc::filesystem::is_symlink(const path &p, std::error_code &ec) noexcept
References is_symlink, symlink_status.
file_time_type ghc::filesystem::last_write_time(const path &p, std::error_code &ec) noexcept
References ghc::filesystem::detail::status_ex.
Referenced by copy_file, ghc::filesystem::directory_entry::last_write_time, ghc::filesystem::directory_entry::operator=.
void ghc::filesystem::last_write_time(const path &p, file_time_type new_time, std::error_code &ec) noexcept
References GHC_INLINE, GHC_NATIVEWP, ghc::filesystem::detail::make_system_error, permissions, ghc::filesystem::detail::systemErrorText, UTIME_OMIT.
void ghc::filesystem::permissions(const path &p, perms prms, std::error_code &ec) noexcept
References permissions, replace.
Referenced by last_write_time, permissions.
void ghc::filesystem::permissions(const path &p, perms prms, perm_options opts, std::error_code &ec) noexcept
References add, ghc::filesystem::path::c_str, GHC_NATIVEWP, ghc::filesystem::detail::invalid_argument, ghc::filesystem::detail::make_error_code, ghc::filesystem::detail::make_system_error, nofollow, owner_read, owner_write, remove, replace, symlink_status, ghc::filesystem::path::wstring.
path ghc::filesystem::proximate(const path &p, std::error_code &ec)
path ghc::filesystem::proximate(const path &p, const path &base, std::error_code &ec)
References ghc::filesystem::path::lexically_proximate, weakly_canonical.
path ghc::filesystem::read_symlink(const path &p, std::error_code &ec)
References ghc::filesystem::detail::invalid_argument, ghc::filesystem::detail::make_error_code, ghc::filesystem::detail::resolveSymlink, symlink, symlink_status.
Referenced by copy_symlink.
path ghc::filesystem::relative(const path &p, std::error_code &ec)
References current_path, relative.
Referenced by relative.
path ghc::filesystem::relative(const path &p, const path &base, std::error_code &ec)
References ghc::filesystem::path::lexically_relative, weakly_canonical.
bool ghc::filesystem::remove(const path &p, std::error_code &ec) noexcept
References ghc::filesystem::detail::make_system_error, remove.
uintmax_t ghc::filesystem::remove_all(const path &p, std::error_code &ec) noexcept
References exists, is_directory, ghc::filesystem::detail::is_not_found_error, ghc::filesystem::detail::make_error_code, ghc::filesystem::detail::not_supported, remove, remove_all, symlink_status.
Referenced by remove_all.
void ghc::filesystem::rename(const path &from, const path &to, std::error_code &ec) noexcept
References GHC_NATIVEWP, ghc::filesystem::detail::make_system_error, rename.
Referenced by rename.
void ghc::filesystem::resize_file(const path &p, uintmax_t size, std::error_code &ec) noexcept
References GHC_NATIVEWP, ghc::filesystem::detail::make_system_error.
space_info ghc::filesystem::space(const path &p, std::error_code &ec) noexcept
References GHC_NATIVEWP, ghc::filesystem::detail::make_system_error.
file_status ghc::filesystem::status(const path &p, std::error_code &ec) noexcept
References ghc::filesystem::detail::status_ex.
Referenced by copy, copy_file, create_directory, exists, is_block_file, is_character_file, is_directory, is_empty, is_fifo, is_other, is_regular_file, is_socket, ghc::filesystem::directory_entry::operator=, ghc::filesystem::directory_entry::status.
bool ghc::filesystem::status_known(file_status s) noexcept
References none.
Referenced by create_directory, exists.
file_status ghc::filesystem::symlink_status(const path &p, std::error_code &ec) noexcept
References ghc::filesystem::detail::symlink_status_ex.
Referenced by copy, is_symlink, ghc::filesystem::directory_entry::is_symlink, ghc::filesystem::directory_entry::operator=, permissions, read_symlink, remove_all, ghc::filesystem::directory_entry::symlink_status.
path ghc::filesystem::temp_directory_path(std::error_code &ec) noexcept
References ghc::filesystem::path::clear, ghc::filesystem::detail::make_system_error.
path ghc::filesystem::weakly_canonical(const path &p, std::error_code &ec) noexcept
References canonical, ghc::filesystem::path::clear, ghc::filesystem::path::empty, exists, ghc::filesystem::path::lexically_normal.
Referenced by proximate, relative.
void ghc::filesystem::create_hard_link(const path &to, const path &new_hard_link, std::error_code &ec) noexcept
References ghc::filesystem::detail::create_hardlink.
Referenced by copy.
uintmax_t ghc::filesystem::hard_link_count(const path &p, std::error_code &ec) noexcept
References GHC_NATIVEWP, ghc::filesystem::detail::make_error_code, ghc::filesystem::detail::make_system_error, not_found, ghc::filesystem::detail::not_found, ghc::filesystem::detail::status_ex.
Referenced by ghc::filesystem::directory_entry::hard_link_count, ghc::filesystem::directory_entry::operator=.
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator&(Enum X, Enum Y)
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator|(Enum X, Enum Y)
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator^(Enum X, Enum Y)
constexpr detail::EnableBitmask< Enum > ghc::filesystem::operator~(Enum X)
detail::EnableBitmask< Enum > & ghc::filesystem::operator&=(Enum &X, Enum Y)
detail::EnableBitmask< Enum > & ghc::filesystem::operator|=(Enum &X, Enum Y)
detail::EnableBitmask< Enum > & ghc::filesystem::operator^=(Enum &X, Enum Y)