CLI::detail
enabler
Simple empty scoped class.
path_type
Classifier
constexpr int CLI::detail::expected_max_vector_size
a constant defining an expected max vector size defined to be a big number that could be multiplied by 4 and not produce overflow for some expected uses
Referenced by CLI::App::_parse_arg, CLI::App::_validate, CLI::Option::expected, CLI::Option::get_items_expected_max, CLI::Formatter::make_option_opts, CLI::Formatter::make_option_usage, CLI::Option::multi_option_policy, CLI::Option::type_size.
constexpr enabler CLI::detail::dummy
An instance to use in EnableIf.
Referenced by sisi4s::BasisSetExtrapolation::fitF12.
return CLI::detail::str
Referenced by add_quotes_if_needed, CLI::Option::add_result, escape_detect, find_and_modify, find_and_replace, get_default_flag_values, is_separator, isalpha, ltrim, CLI::Validator::operator!, CLI::Validator::operator(), nwchem::BasisSetParser::parseFile, ShellParser::parseString, pars::parseVector, remove_quotes, remove_underscore, rtrim, split_up, to_lower, trim, trim_copy, valid_alias_name_string, valid_name_string.
std::vector< std::string > CLI::detail::split(const std::string &s, char delim)
Split a string by a delim.
Referenced by CLI::detail::IPV4Validator::IPV4Validator, generate_parents.
std::string CLI::detail::join(const T &v, std::string delim=",")
Simple function to join a string.
Referenced by CLI::CheckedTransformer::CheckedTransformer, CLI::App::_process_requirements, CLI::ConfigItem::fullname, generate_map, generate_set, CLI::Option::get_name, CLI::Formatter::make_usage, CLI::FailureMessage::simple, sisi4s::LapackMatrix< F >::write.
std::string CLI::detail::join(const T &v, Callable func, std::string delim=",")
Simple function to join a string from processed elements.
std::string CLI::detail::rjoin(const T &v, std::string delim=",")
Join a string in reverse order.
std::string & CLI::detail::ltrim(std::string &str)
Trim whitespace from left of string.
References str.
Referenced by trim.
std::string & CLI::detail::ltrim(std::string &str, const std::string &filter)
Trim anything from left of string.
References str.
Referenced by split_program_name.
std::string & CLI::detail::rtrim(std::string &str)
Trim whitespace from right of string.
References str.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit, trim.
std::string & CLI::detail::rtrim(std::string &str, const std::string &filter)
Trim anything from right of string.
References str.
Referenced by split_program_name.
std::string & CLI::detail::trim(std::string &str)
Trim whitespace from string.
References ltrim, rtrim, str.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit, CLI::ConfigBase::from_config, CLI::App::parse, split_up, trim_copy.
std::string & CLI::detail::trim(std::string &str, const std::string filter)
Trim anything from string.
References ltrim, rtrim, str.
Referenced by split_program_name.
std::string CLI::detail::trim_copy(const std::string &str)
Make a copy of the string and then trim it.
References str, trim.
Referenced by CLI::ConfigBase::from_config.
std::string & CLI::detail::remove_quotes(std::string &str)
remove quotes at the front and back of a string either '"' or '\''
References str.
Referenced by CLI::ConfigBase::from_config, generate_parents.
std::string CLI::detail::fix_newlines(const std::string &leader, std::string input)
Add a leader to the beginning of all new lines (nothing is added at the start of the first line). "; " would be for ini files Can't use Regex, or this would be a subs.
Referenced by format_aliases, CLI::ConfigBase::to_config.
std::string CLI::detail::trim_copy(const std::string &str, const std::string &filter)
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
References str, trim.
Referenced by split_names.
std::ostream & CLI::detail::format_help(std::ostream &out, std::string name, const std::string &description, std::size_t wid)
Print a two part "help" string.
Referenced by CLI::Formatter::make_option, CLI::Formatter::make_subcommand.
std::ostream & CLI::detail::format_aliases(std::ostream &out, const std::vector< std::string > &aliases, std::size_t wid)
Print subcommand aliases.
References fix_newlines.
Referenced by CLI::Formatter::make_expanded.
bool CLI::detail::valid_first_char(T c)
Verify the first character of an option is a trigger character, ! has special meaning and new lines would just be annoying to deal with
Referenced by CLI::App::add_subcommand, get_names, split_long, split_short, split_windows_style, valid_name_string.
bool CLI::detail::valid_later_char(T c)
Verify following characters of an option.
Referenced by CLI::App::add_subcommand, valid_name_string.
bool CLI::detail::valid_name_string(const std::string &str)
Verify an option/subcommand name.
References str, valid_first_char, valid_later_char.
Referenced by CLI::App::add_subcommand, get_names.
bool CLI::detail::valid_alias_name_string(const std::string &str)
Verify an app name.
References str.
Referenced by CLI::App::add_option_group, CLI::App::alias, CLI::OptionBase< CRTP >::group.
bool CLI::detail::is_separator(const std::string &str)
check if a string is a container segment separator (empty or "%%")
References sep, str.
bool CLI::detail::isalpha(const std::string &str)
Verify that str consists of letters only.
References str.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit.
std::string CLI::detail::to_lower(std::string str)
Return a lower case version of a string.
References str.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit, CLI::Option::check_name, CLI::App::check_name, find_member, CLI::ConfigBase::from_config, generate_parents, CLI::ignore_case, CLI::Formatter::make_subcommands, to_flag_value.
std::string CLI::detail::remove_underscore(std::string str)
remove underscores from a string
References str.
Referenced by CLI::Option::check_name, CLI::App::check_name, find_member, CLI::ignore_underscore.
std::string CLI::detail::find_and_replace(std::string str, std::string from, std::string to)
Find and replace a substring with another substring.
References str.
Referenced by CLI::Formatter::make_expanded, split_program_name, split_up.
bool CLI::detail::has_default_flag_values(const std::string &flags)
check if the flag definitions has possible false flags
void CLI::detail::remove_default_flag_values(std::string &flags)
std::ptrdiff_t CLI::detail::find_member(std::string name, const std::vector< std::string > names, bool ignore_case=false, bool ignore_underscore=false)
Check if a string is a member of a list of strings and optionally ignore case or ignore underscores.
References CLI::ignore_case, CLI::ignore_underscore, remove_underscore, to_lower.
Referenced by CLI::Option::check_fname, CLI::Option::check_lname, CLI::Option::check_sname, CLI::Option::get_flag_value.
std::string CLI::detail::find_and_modify(std::string str, std::string trigger, Callable modify)
Find a trigger string and call a modify callable function that takes the current string and starting position of the trigger and returns the position in the string to search for the next trigger string
References str.
Referenced by CLI::App::parse.
std::vector< std::string > CLI::detail::split_up(std::string str, char delimiter='\0')
Split a string '"one two" "three"' into 'one two', 'three' Quote characters can be or "
References find_and_replace, str, trim.
Referenced by CLI::ConfigBase::from_config, CLI::App::parse.
std::size_t CLI::detail::escape_detect(std::string &str, std::size_t offset)
This function detects an equal or colon followed by an escaped quote after an argument then modifies the string to replace the equality with a space. This is needed to allow the split up function to work properly and is intended to be used with the find_and_modify function the return value is the offset+1 which is required by the find_and_modify function.
References str.
Referenced by CLI::App::parse.
std::string & CLI::detail::add_quotes_if_needed(std::string &str)
Add quotes if the string contains spaces.
References str.
bool CLI::detail::from_stream(const std::string &istring, T &obj)
Templated operation to get a value from a stream.
auto CLI::detail::to_string(T &&value) -> decltype(std::forward< T >(value))
Convert an object to a string (directly forward if this can become a string)
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit, CLI::Bound::Bound, CLI::CheckedTransformer::CheckedTransformer, CLI::Option::default_val, generate_map, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::PQRSCoulombIntegralsToVertex::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
std::string CLI::detail::to_string(const T &value)
Construct a string from the object.
std::string CLI::detail::to_string(T &&value)
Convert an object to a string (streaming must be supported for that type)
convert a readable container to a string If conversion is not supported, return an empty string (streaming is not supported for that type)
Referenced by CLI::ArgumentMismatch::AtLeast, CLI::ArgumentMismatch::AtMost, checked_to_string, CLI::Option::get_flag_value, CLI::App::get_subcommand, CLI::App::get_subcommand_ptr, CLI::Formatter::make_description, CLI::RequiredError::Option, CLI::RequiredError::Subcommand, CLI::ArgumentMismatch::TypedAtLeast, value_string.
auto CLI::detail::checked_to_string(T &&value) -> decltype(to_string(std::forward< T >(value)))
special template overload
References to_string.
std::string CLI::detail::checked_to_string(T &&)
special template overload
std::string CLI::detail::value_string(const T &value)
get a string as a convertible value for arithmetic types
get a string as a convertible value for enumerations
References to_string.
Referenced by CLI::CheckedTransformer::CheckedTransformer, CLI::IsMember::IsMember, CLI::Transformer::Transformer.
auto CLI::detail::value_string(const T &value) -> decltype(to_string(value))
for other types just use the regular to_string function
References to_string.
constexpr std::enable_if< I==type_count_base< T >::value, int >::type CLI::detail::tuple_type_size()
0 if the index > tuple size
CLI::detail::if(str.back()==',') str.pop_back()
std::string CLI::detail::type_name()
Print type name for tuples with 2 or more elements.
std::string CLI::detail::type_name()
get the type name for a type that has a value_type member
bool CLI::detail::integral_conversion(const std::string &input, T &output) noexcept
Convert to an unsigned integral.
Convert to a signed integral.
Referenced by lexical_cast.
std::int64_t CLI::detail::to_flag_value(std::string val)
Convert a flag into an integer value typically binary flags.
References to_lower.
Referenced by CLI::Option::get_flag_value.
bool CLI::detail::lexical_cast(const std::string &input, T &output)
Integer conversion.
Non-string parsable by a stream. Non-string convertible from an int. Assignable from double. Assignable from int. Assignable from double or int. wrapper types Enumerations. String and similar constructible and copy assignment. String and similar direct assignment. complex Floats. Boolean values. char values
References integral_conversion.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit, CLI::Bound::Bound, CLI::CheckedTransformer::CheckedTransformer, CLI::detail::IPV4Validator::IPV4Validator, CLI::IsMember::IsMember, CLI::Transformer::Transformer, CLI::TypeValidator< DesiredType >::TypeValidator, CLI::App::add_flag, CLI::App::add_flag_callback, convert_arg_for_ini, lexical_assign.
bool CLI::detail::lexical_assign(const std::string &input, AssignTo &output)
Assign a value through lexical cast operations.
Assign a value from a lexical cast through constructing a value and move assigning it. Assign a value converted from a string in lexical cast to the output value directly. Assign a value through lexical cast operations Strings can be empty so we need to do a little different Assign a value through lexical cast operations for int compatible values mainly for atomic operations on some compilers
References lexical_cast.
bool CLI::detail::split_short(const std::string &current, std::string &name, std::string &rest)
References valid_first_char.
Referenced by CLI::App::_parse_arg, CLI::App::_recognize.
bool CLI::detail::split_long(const std::string &current, std::string &name, std::string &value)
References valid_first_char.
Referenced by CLI::App::_parse_arg, CLI::App::_recognize.
bool CLI::detail::split_windows_style(const std::string &current, std::string &name, std::string &value)
References valid_first_char.
Referenced by CLI::App::_parse_arg, CLI::App::_recognize.
std::vector< std::string > CLI::detail::split_names(std::string current)
References trim_copy.
Referenced by CLI::Option::Option, get_default_flag_values.
std::vector< std::pair< std::string, std::string > > CLI::detail::get_default_flag_values(const std::string &str)
extract default flag values either {def} or starting with a !
References split_names, str.
std::tuple< std::vector< std::string >, std::vector< std::string >, std::string > CLI::detail::get_names(const std::vector< std::string > &input)
Get a vector of short names, one of long names, and a single name.
References CLI::BadNameString::BadLongName, CLI::BadNameString::DashesOnly, CLI::BadNameString::MultiPositionalNames, CLI::BadNameString::OneCharName, valid_first_char, valid_name_string.
Referenced by CLI::Option::Option.
path_type CLI::detail::check_path(const char *file) noexcept
get the type of the path from a file name
References file.
Referenced by CLI::detail::ExistingDirectoryValidator::ExistingDirectoryValidator, CLI::detail::ExistingFileValidator::ExistingFileValidator, CLI::detail::ExistingPathValidator::ExistingPathValidator, CLI::detail::NonexistentPathValidator::NonexistentPathValidator, CLI::App::_process_config_file, split_program_name.
auto CLI::detail::smart_deref(T value) -> decltype(*value)
Referenced by CLI::CheckedTransformer::CheckedTransformer, CLI::IsMember::IsMember, CLI::Transformer::Transformer, generate_map, generate_set, search.
std::remove_reference< T >::type & CLI::detail::smart_deref(T &value)
std::string CLI::detail::generate_set(const T &set)
Generate a string representation of a set.
References CLI::detail::pair_adaptor< T, _ >::first, join, smart_deref.
Referenced by CLI::IsMember::IsMember.
std::string CLI::detail::generate_map(const T &map, bool key_only=false)
Generate a string representation of a map.
References join, smart_deref, to_string.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit, CLI::CheckedTransformer::CheckedTransformer, CLI::Transformer::Transformer.
auto CLI::detail::search(const T &set, const V &val) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function.
A search function that uses the built in find function.
References smart_deref.
Referenced by CLI::CheckedTransformer::CheckedTransformer, CLI::IsMember::IsMember, CLI::Transformer::Transformer.
auto CLI::detail::search(const T &set, const V &val, const std::function< V(V)> &filter_function) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function with a filter function.
References CLI::detail::pair_adaptor< T, _ >::first, search, smart_deref.
Referenced by search.
std::enable_if< std::is_signed< T >::value, T >::type CLI::detail::overflowCheck(const T &a, const T &b)
Do a check for overflow on signed numbers.
References sisi4s::abs.
std::enable_if<!std::is_signed< T >::value, T >::type CLI::detail::overflowCheck(const T &a, const T &b)
Do a check for overflow on unsigned numbers.
Referenced by checked_multiply.
std::enable_if< std::is_integral< T >::value, bool >::type CLI::detail::checked_multiply(T &a, T b)
Performs a *= b; if it doesn't cause integer overflow. Returns false otherwise.
References overflowCheck.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit, CLI::App::_parse_arg, CLI::Option::get_items_expected_max.
std::enable_if< std::is_floating_point< T >::value, bool >::type CLI::detail::checked_multiply(T &a, T b)
Performs a *= b; if it doesn't equal infinity. Returns false otherwise.
std::pair< std::string, std::string > CLI::detail::split_program_name(std::string commandline)
Split a string into a program name and command line arguments the string is assumed to contain a file name followed by other arguments the return value contains is a pair with the first argument containing the program name and the second everything else.
References check_path, find_and_replace, ltrim, rtrim, trim.
Referenced by CLI::App::parse.
std::string CLI::detail::convert_arg_for_ini(const std::string &arg, char stringQuote='"', char characterQuote = '\'')
References lexical_cast.
Referenced by ini_join, CLI::ConfigBase::to_config.
std::string CLI::detail::ini_join(const std::vector< std::string > &args, char sepChar=',', char arrayStart='[', char arrayEnd=']', char stringQuote='"', char characterQuote = '\'')
Comma separated join, adds quotes if needed.
References convert_arg_for_ini.
Referenced by CLI::ConfigBase::to_config.
std::vector< std::string > CLI::detail::generate_parents(const std::string &section, std::string &name, char parentSeparator)
References remove_quotes, split, to_lower.
Referenced by checkParentSegments, CLI::ConfigBase::from_config.
void CLI::detail::checkParentSegments(std::vector< ConfigItem > &output, const std::string &currentSection, char parentSeparator)
assuming non default segments do a check on the close and open of the segments in a configItem structure
References generate_parents.
Referenced by CLI::ConfigBase::from_config.