am
AngularMomentum
std::vector< am::AngularMomentum > am::all()
References D, F, G, H, I, K, P, S.
size_t am::toInt(const AngularMomentum &)
Referenced by findShellIndices, sisi4s::MoReader::run.
am::AngularMomentum am::fromString(const std::string &)
References D, F, G, H, I, K, P, S.
Referenced by nwchem::BasisSetParser::parseBasis, ShellParser::parseString, sisi4s::MoReader::run.