pars
using pars::Str = typedef std::string
Str pars::oneOf(const std::vector< std::string > &v)
References orOf.
std::vector< std::string > pars::parseVector(const std::string &l)
References capture, oneOrMore, pars::Regex::r.
std::vector< double > pars::parseVector< double >(const std::string &l)
Referenced by sisi4s::MoReader::run.
std::vector< int > pars::parseVector< int >(const std::string &l)
Referenced by sisi4s::MoReader::run, sisi4s::TensorSlicer::run.
const Str pars::oneOrMore("+")
Referenced by parseVector.
const Str pars::newline("\\n")
const Str pars::anyChar(".")
const Str pars::tab("\\t")
const Str pars::anyOf("*")
const Str pars::optional("?")
const Str pars::eof("$")
const Str pars::orOf("|")
Referenced by oneOf.
const Str pars::bof("^")
const Str pars::alnum("[[:alnum:]]")
const Str pars::alpha("[[:alpha:]]")
const Str pars::blank("[[:blank:]]")
const Str pars::cntrl("[[:cntrl:]]")
const Str pars::digit("[[:digit:]]")
const Str pars::graph("[[:graph:]]")
const Str pars::lower("[[:lower:]]")
const Str pars::upper("[[:upper:]]")
const Str pars::print("[[:print:]]")
const Str pars::punct("[[:punct:]]")
const Str pars::space("[[:space:]]")
const Str pars::xdigit("[[:xdigit:]]")
const Str pars::realNumber("[-eE+\\d.]+")
const std::function< Str(Str)> pars::capture([](const Str &i) { return "("+i+")";})
Referenced by parseVector.
const std::function< Str(Str)> pars::group([](const Str &i) { return "(?:"+i+")";})
std::vector< F > pars::parseVector(const std::string &)