sisi4s
InputFileFormat
Index
using sisi4s::MatrixColumnMajor = typedef Eigen::Matrix< double , Eigen::Dynamic , Eigen::Dynamic , Eigen::ColMajor >
using sisi4s::ivec = typedef array<int,3>
using sisi4s::dvec = typedef array<double,4>
using sisi4s::Complex = typedef std::complex<Real>
typedef Complex<Float32> sisi4s::Complex32
typedef Complex<Float64> sisi4s::Complex64
typedef Complex<real> sisi4s::complex
typedef FloatTypes<32>::type sisi4s::Float32
typedef FloatTypes<64>::type sisi4s::Float64
using sisi4s::Tensor = typedef CTF::Tensor<F>
using sisi4s::Matrix = typedef CTF::Matrix<F>
Algorithm * sisi4s::createAlgorithm(std::vector< Argument > const &arguments)
template function creating an instance of the given class.
std::string sisi4s::operator*(const std::string &s, const sisi4s::Permutation< N > &pi)
MatrixColumnMajor sisi4s::toEigenMatrix(Tensor< double > &ctf)
Referenced by getFockMatrix, sisi4s::HartreeFockFromCoulombIntegrals::run, sisi4s::HartreeFockFromGaussian::run.
void sisi4s::composeCanonicalPolyadicDecompositionTensors(Tensor< F > &A, Tensor< F > &B, Tensor< F > &C, Tensor< F > &T)
Calculates $T_{ijk}=A_{iR}B_{jR}C_{kR}$ with minimal memory footprint.
References Assert, LOG.
Referenced by sisi4s::ParticleHoleCoulombVertexDecomposition::fit, sisi4s::CoulombVertexDecomposition::getDelta.
void sisi4s::dryComposeCanonicalPolyadicDecompositionTensors(DryTensor< F > &A, DryTensor< F > &B, DryTensor< F > &C, DryTensor< F > &T)
Performs a dry run of the calculation $T_{ijk}=A_{iR}B_{jR}C_{kR}$ with minimal memory footprint.
References Assert, sisi4s::DryTensor< F >::lens, LOG, sisi4s::DryTensor< F >::order.
Referenced by sisi4s::ParticleHoleCoulombVertexDecomposition::dryFit, sisi4s::CoulombVertexDecomposition::dryFit.
void sisi4s::contractWithCanonicalPolyadicDecompositionTensors(Tensor< F > &T, char const *indicesT, Tensor< F > &B, char const idxB, Tensor< F > &C, char const idxC, Tensor< F > &A, char const idxA)
Calculates $A_{iR} = T_{ijk}B^{jR}C^{kR}$ using a contraction order with minimal memory footprint.
T the tensor $T_{ijk}$ indicesT the indices to compose $T$, e.g. "ijk" B the tensor $B_{jR}$ idxB the index letter $B$ has in common with $T$ C the tensor $C_{kR}$ idxC the index letter $C$ has in common with $T$ A the tensor $A_{iR}$ idxA the index letter $A$ has in common with $T$
References Assert, LOG.
Referenced by fitAlternatingLeastSquaresFactor, fitRegularizedAlternatingLeastSquaresFactor.
void sisi4s::dryContractWithCanonicalPolyadicDecompositionTensors(DryTensor< F > &T, char const *indicesT, DryTensor< F > &B, char const idxB, DryTensor< F > &C, char const idxC, DryTensor< F > &A, char const idxA)
Performs a dry run of the calculation $A_{iR} = T_{ijk}B^{jR}C^{kR}$ using a contraction order with minimal memory footprint.
T the tensor $T_{ijk}$ indicesT the indices to compose $T$, e.g. "ijk" B the tensor $B_{jR}$ idxB the index letter $B$ has in common with $T$ C the tensor $C_{kR}$ idxC the index letter $C$ has in common with $T$ A the tensor $A_{iR}$ idxA the index letter $A$ has in common with $T$
References Assert, sisi4s::DryTensor< F >::lens, LOG, sisi4s::DryTensor< F >::order.
Referenced by dryFitRegularizedAlternatingLeastSquaresFactor.
Real sisi4s::absSqr(const Real x)
Referenced by absSqr.
Real sisi4s::absSqr(const Complex< Real > z)
References absSqr.
void sisi4s::fromComplexTensor(Tensor< complex > &c, Tensor< double > &r, Tensor< double > &i)
Decomposes the tensor of complex elements into two tensors containing the real and imaginary parts, respectively.
References AssertCompatibleTensorShapes, fromComplexTensor, am::I, Indices.
Referenced by sisi4s::FiniteSizeCorrection::calculateComplexStructureFactor, sisi4s::CoulombIntegralsFromVertex::calculateRealIntegrals, sisi4s::FiniteSizeCorrection::calculateRealStructureFactor, sisi4s::ParticleHoleCoulombVertexDecomposition::evaluateMp2, sisi4s::BasisSetExtrapolation::evaluateQGG, fromComplexTensor, sisi4s::CcsdEnergyFromCoulombIntegrals::getResiduum, sisi4s::CcsdDiagrammaticDecomposition::run, sisi4s::DoublesAmplitudesFromVertex::run, sisi4s::FromComplexTensor::run, sisi4s::ParenthesisTriples::run, sisi4s::ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors, sisi4s::ClusterSinglesDoublesAlgorithm::sliceCoupledCoulombIntegrals, sisi4s::CcsdPerturbativeTriples::sliceTensors.
void sisi4s::fromComplexTensor(Tensor< double > &c, Tensor< double > &r, Tensor< double > &i)
References AssertCompatibleTensorShapes, am::I, Indices.
void sisi4s::fromComplexTensor(Tensor< complex > &c, Tensor< double > &r)
Discards the real part of a complex tensor.
References AssertCompatibleTensorShape, Indices.
void sisi4s::toComplexTensor(Tensor< double > &r, Tensor< double > &i, Tensor< complex > &c)
Composes a tensor of complex elements containing of the given tensors of real and imaginary parts. Note that in this overload the imaginary part may be redistributed during reading.
References AssertCompatibleTensorShapes, am::I, Indices, toComplexTensor.
Referenced by sisi4s::FiniteSizeCorrection::calculateComplexStructureFactor, sisi4s::ClusterSinglesDoublesAlgorithm::calculateExcitationEnergies, sisi4s::FiniteSizeCorrection::calculateRealStructureFactor, sisi4s::CcsdEquationOfMotionDavidson::run, sisi4s::CcsdtEquationOfMotionDavidson::run, sisi4s::CoulombVertexReader::run, sisi4s::ParticleHoleCoulombVertexReader::run, sisi4s::UCcsdEAEquationOfMotionDavidson::run, sisi4s::UCcsdIPEquationOfMotionDavidson::run, sisi4s::UnrestrictedEquationOfMotionSinglesFromRpa::run, sisi4s::ClusterSinglesDoublesAlgorithm::sliceAmplitudesFromCoupledCoulombFactors, sisi4s::ClusterSinglesDoublesAlgorithm::sliceCoupledCoulombIntegrals, sisi4s::DoublesAmplitudesDecomposition::sliceLargestEigenValues, toComplexTensor.
void sisi4s::toComplexTensor(Tensor< double > &r, Tensor< complex > &c)
References AssertCompatibleTensorShape, Indices.
void sisi4s::toComplexTensor(Tensor< double > &r, Tensor< double > &c)
References AssertCompatibleTensorShape, Indices.
void sisi4s::conjugate(Tensor< double > &c)
Referenced by sisi4s::PseudoInverseHermitianSvd< F >::PseudoInverseHermitianSvd, sisi4s::NaturalTransitionOrbitalsFromRhoAI::buildTransformations, sisi4s::BasisSetExtrapolation::evaluateQGG, sisi4s::IterativePseudoInverse< F >::iterate, sisi4s::ApproximateCoulombVertex::run, sisi4s::CoulombVertexSingularVectors::run, sisi4s::NaturalTransitionOrbitalsFromRhoAI::run, sisi4s::ParticleHoleCoulombVertexSingularVectors::run, sisi4s::SimilarityTransformedHamiltonian< F >::structureFactor.
void sisi4s::conjugate(Tensor< complex > &c)
References conj, Indices.
FockVector< F > sisi4s::operator+(const FockVector< F > &a, const FockVector< F > &b)
Returns the sum of two FockVectors a and b, where neither a nor b are modified.
FockVector< F > && sisi4s::operator+(FockVector< F > &&a, const FockVector< F > &b)
Returns the sum of two FockVectors a and b, where a is movable and will be used for the result.
FockVector< F > && sisi4s::operator+(FockVector< F > &a, const FockVector< F > &&b)
Returns the sum of two FockVectors a and b, where b is movable and will be used for the result.
FockVector< F > sisi4s::operator-(const FockVector< F > &a, const FockVector< F > &b)
Returns the difference between two FockVectors a and b, where neither a nor b are modified.
FockVector< F > && sisi4s::operator-(FockVector< F > &&a, const FockVector< F > &b)
Returns the difference between two FockVectors a and b, where a is movable and will be used for the result.
FockVector< F > && sisi4s::operator-(const FockVector< F > &a, FockVector< F > &&b)
Returns the difference between two FockVectors a and b, where b is movable and will be used for the result.
References am::F.
FockVector< F > sisi4s::operator*(const FockVector< F > &a, const F s)
Returns the scalar multiple of the FockVector a right-multiplied with the scalar s, where a is not modified.
FockVector< F > && sisi4s::operator*(FockVector< F > &&a, const F s)
Returns the scalar multiple of the FockVector a right-multiplied with the scalar s, where a movable and will be used for the result.
FockVector< F > sisi4s::operator*(const F s, const FockVector< F > &a)
Returns the scalar multiple of the FockVector a left-multiplied with the scalar s, where a is not modified.
FockVector< F > && sisi4s::operator*(const F s, FockVector< F > &&a)
Returns the scalar multiple of the FockVector a left-multiplied with the scalar s, where a movable and will be used for the result.
std::ostream & sisi4s::operator<<(std::ostream &stream, const FockVector< F > &a)
Writes the FockVector a to the given stream and returns it for further stream operations.
References sisi4s::FockVector< F >::componentTensors, sisi4s::FockVector< F >::get, sisi4s::FockVector< F >::getIndices.
double sisi4s::integrate(F f, Float a, Float b, int steps, Method m)
constexpr F sisi4s::Pi()
References am::F.
Referenced by sisi4s::CoulombVertexDecomposition::iterateQuadraticFactor, sisi4s::CoulombVertexDecomposition::normalizePi, sisi4s::ParticleHoleCoulombVertexDecomposition::normalizePi, sisi4s::CoulombVertexDecomposition::realizePi, sisi4s::ParticleHoleCoulombVertexDecomposition::realizePi.
constexpr F sisi4s::Tau()
F sisi4s::sqrt(F const x)
References sqrt.
Referenced by sisi4s::BlacsWorld::BlacsWorld, sisi4s::FiniteSizeCorrection::calculateComplexStructureFactor, sisi4s::FiniteSizeCorrection::calculateRealStructureFactor, sisi4s::FiniteSizeCorrection::constructFibonacciGrid, sisi4s::DoublesAmplitudesDecomposition::diagonlizeAmplitudes, sisi4s::UegVertexGenerator::evalMadelung, sisi4s::BasisSetExtrapolation::evaluateQGG, sisi4s::BasisSetExtrapolation::fitF12, frobeniusNorm, getEnergy, sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::IPCcsdPreconditioner< F >::getInitialBasis, sisi4s::EACcsdPreconditioner< F >::getInitialBasis, getNuclearRepulsionEnergy, sisi4s::Vector< F, D >::length, sisi4s::UegVertexGenerator::run, sisi4s::EigenSystemDavidsonMono< H, P, V >::run, sqrt.
F sisi4s::abs(F const x)
References abs.
Referenced by sisi4s::PseudoInverseHermitianSvd< F >::PseudoInverseHermitianSvd, abs, sisi4s::CcsdPreconditioner< F >::getCorrection, sisi4s::IPCcsdPreconditioner< F >::getCorrection, sisi4s::EACcsdPreconditioner< F >::getCorrection, sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::IPCcsdPreconditioner< F >::getInitialBasis, sisi4s::EACcsdPreconditioner< F >::getInitialBasis, sisi4s::Inter1D< F >::getValue, sisi4s::FiniteSizeCorrection::interpolation3D, sisi4s::FiniteSizeCorrection::IsInSmallBZ, sisi4s::IterativePseudoInverse< F >::iterate, sisi4s::IterativePseudoInverse< F >::iterateQuadratically, sisi4s::LapackGeneralEigenSystem< complex >::EigenValueComparator::operator(), sisi4s::LapackGeneralEigenSystem< double >::EigenValueComparator::operator(), EomDiagonalValueComparator< F >::operator(), CLI::detail::overflowCheck, sisi4s::ClusterSinglesDoublesAlgorithm::run, sisi4s::ClusterSinglesDoublesTriplesAlgorithm::run, sisi4s::UegVertexGenerator::run, sisi4s::EigenSystemDavidsonMono< H, P, V >::run, sisi4s::DoublesAmplitudesDecomposition::sliceLargestEigenValues, sisi4s::IterativePseudoInverse< F >::test, CLI::Option::type_size.
F sisi4s::conj(F const x)
References conj.
Referenced by sisi4s::LapackGeneralEigenSystem< complex >::biorthogonalError, conjugate, dot, sisi4s::LapackGeneralEigenSystem< complex >::leftEigenError, logOverlap, logVectorNorms, realDot, sisi4s::LapackGeneralEigenSystem< complex >::rightEigenError, sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
double sisi4s::conj(double const x)
Referenced by conj.
F sisi4s::dot(F const x, F const y)
References conj.
Referenced by sisi4s::DiisMixer< F >::append, sisi4s::Vector< F, D >::dot, sisi4s::FiniteSizeCorrection::interpolation3D, sisi4s::FiniteSizeCorrection::IsInSmallBZ, sisi4s::EigenSystemDavidsonMono< H, P, V >::run.
F sisi4s::realDot(F const x, F const y)
Calculates only the real part of x*conj(y).
References conj.
F sisi4s::divide(F const x, F const y)
F sisi4s::multiply(F const x, F const y)
double sisi4s::frobeniusNorm(Tensor< F > &t)
References sqrt.
Referenced by sisi4s::ParticleHoleCoulombVertexDecomposition::fit, fitRegularizedAlternatingLeastSquaresFactor, sisi4s::CoulombVertexDecomposition::getDelta, sisi4s::ParticleHoleCoulombVertexDecomposition::normalizePi, sisi4s::ComplexTensorNorm::run, sisi4s::TensorNorm::run, sisi4s::DoublesAmplitudesDecomposition::sliceLargestEigenValues.
void sisi4s::symmetrize(std::string indices, std::string permuted, Tensor< F > &t, F prefactor=1)
Apply a permutation operator and antisymmetrize accordingly, e.g. antiSymmetrize(X, "abcd", "abdc") is replaced by -1 X["abcd"] = X["abcd"] + sign(abcd -> abdc) X["abdc"].
void sisi4s::checkAntisymmetry(Tensor< F > &t)
References am::F, LOG.
std::ostream & sisi4s::operator<<(std::ostream &stream, const Map< N > &f)
Permutation< N > sisi4s::operator*(const Permutation< N > &, const Permutation< N > &)
Permutation< N > sisi4s::operator/(const Permutation< N > &, const Permutation< N > &)
Permutation< N > sisi4s::operator/(const int, const Permutation< N > &)
Map< N > sisi4s::operator*(const Map< N > &f, const Permutation< N > &tau)
void sisi4s::setRandom(double &value, Distribution &distribution, RandomEngine &randomEngine)
Referenced by setRandomTensor.
void sisi4s::setRandom(complex &value, Distribution &distribution, RandomEngine &randomEngine)
void sisi4s::setRandomTensor(Tensor< F > &t, Distribution &distribution, RandomEngine &randomEngine)
References am::F, setRandom.
Referenced by sisi4s::CcsdPreconditioner< F >::getInitialBasis, sisi4s::CoulombVertexDecomposition::run, sisi4s::GenerateRandomComplexMatrix::run, sisi4s::GenerateRandomMatrix::run, sisi4s::GenerateRandomTensor::run, sisi4s::ParticleHoleCoulombVertexDecomposition::run, sisi4s::IterativePseudoInverse< F >::test.
void sisi4s::fitAlternatingLeastSquaresFactor(Tensor< F > &T, char const *indicesT, Tensor< F > &B, char const idxB, Tensor< F > &C, char const idxC, Tensor< F > &A, char const idxA)
References contractWithCanonicalPolyadicDecompositionTensors, sisi4s::PseudoInverseSvd< F >::get, LOG.
Referenced by sisi4s::CoulombVertexDecomposition::iterateQuadraticFactor.
void sisi4s::fitRegularizedAlternatingLeastSquaresFactor(Tensor< F > &T, char const *indicesT, Tensor< F > &B, char const idxB, Tensor< F > &C, char const idxC, Tensor< F > &A, char const idxA, AlternatingLeastSquaresRegularizationEstimator *regularizationEstimatorA)
References contractWithCanonicalPolyadicDecompositionTensors, frobeniusNorm, sisi4s::PseudoInverseSvd< F >::get, sisi4s::AlternatingLeastSquaresRegularizationEstimator::getLambda, sisi4s::AlternatingLeastSquaresRegularizationEstimator::getSwampingThreshold, LOG, sisi4s::AlternatingLeastSquaresRegularizationEstimator::update.
Referenced by sisi4s::CoulombVertexDecomposition::fit, sisi4s::ParticleHoleCoulombVertexDecomposition::fit.
void sisi4s::dryFitRegularizedAlternatingLeastSquaresFactor(DryTensor< F > &T, char const *indicesT, DryTensor< F > &B, char const idxB, DryTensor< F > &C, char const idxC, DryTensor< F > &A, char const idxA)
References dryContractWithCanonicalPolyadicDecompositionTensors, sisi4s::DryPseudoInverseSvd< F >::get, sisi4s::DryTensor< F >::lens, LOG.
Referenced by sisi4s::ParticleHoleCoulombVertexDecomposition::dryFit, sisi4s::CoulombVertexDecomposition::dryFit.
Vector< F, D > sisi4s::operator*(const F f, const Vector< F, D > &v)
Vector< F, D > && sisi4s::operator*(const F f, Vector< F, D > &&v)
std::ostream & sisi4s::operator<<(std::ostream &stream, sisi4s::Vector< F, D > const &v)
References sisi4s::Vector< F, D >::coordinate, am::D.
std::shared_ptr< Mixer< F > > sisi4s::createMixer(Algorithm *algorithm)
template function creating an instance of the given class.
References NEW.
A sisi4s::permuteIndices(const A &a, size_t i, size_t j)
Referenced by IntegralParser::IntegralParser, downTr, hSym, IntegralParser::match, upTr, vlSym, vSym.
A sisi4s::vSym(const A &a)
References permuteIndices.
Referenced by sisi4s::IntegralInfo::getAntisymmetrizers.
A sisi4s::hSym(const A &a)
References permuteIndices.
Referenced by sisi4s::IntegralInfo::getAntisymmetrizers.
A sisi4s::vlSym(const A &a)
References permuteIndices.
Referenced by sisi4s::IntegralInfo::getAntisymmetrizers.
A sisi4s::upTr(const A &a)
References permuteIndices.
Referenced by sisi4s::IntegralInfo::getAntisymmetrizers.
A sisi4s::downTr(const A &a)
References permuteIndices.
Referenced by sisi4s::IntegralInfo::getAntisymmetrizers.
LapackMatrix< F > sisi4s::operator*(const LapackMatrix< F > &A, const LapackMatrix< F > &B)
References EXCEPTION, sisi4s::LapackMatrix< F >::getColumns, sisi4s::LapackMatrix< F >::getRows.
std::ostream & sisi4s::operator<<(std::ostream &stream, const RangeParser &parser)
References sisi4s::RangeParser::getRange.
std::ostream & sisi4s::operator<<(std::ostream &stream, SourceLocation const &l)
References sisi4s::SourceLocation::getFile, sisi4s::SourceLocation::getLine.
Time sisi4s::operator+(Time const &t1, Time const &t2)
Time sisi4s::operator-(Time const &t1, Time const &t2)
Time sisi4s::operator*(const Time &difference, const double factor)
References sisi4s::Time::FRACTIONS, sisi4s::Time::getFractionalSeconds.
std::ostream & sisi4s::operator<<(std::ostream &stream, Time const &t)
References sisi4s::Time::FRACTION_DIGITS, sisi4s::Time::getFractions, sisi4s::Time::getSeconds.