ParenthesisTriples.cxx
IrmlerTensor< F > readBinaryTensorSerial(std::string filename, int64_t offset=0, int64_t elements=0, bool talk=true)
References EXCEPTION, sisi4s::BinaryTensorDimensionHeader::length, LOG, sisi4s::BinaryTensorHeaderBase::order.
double getEnergyZero(const int Nv, const double epsijk, const double *epsa, const double *Tabc_, const double *Zabc_)
Referenced by sisi4s::ParenthesisTriples::run.
double getEnergyOne(const int Nv, const double epsijk, const double *epsa, const double *Tabc_, const double *Zabc_)
Referenced by sisi4s::ParenthesisTriples::run.
void permuteAddOne(const int Nv, const double *input, double *output)
Referenced by sisi4s::ParenthesisTriples::doublesContribution.
void permuteMoveOne(const int Nv, const double *input, double *output)
Referenced by sisi4s::ParenthesisTriples::getVpppijkFromVertex.
void permuteMoveTwo(const int Nv, const double *input, double *output)
Referenced by sisi4s::ParenthesisTriples::doublesContribution.
void fullPermutationZero(const int Nv, const double *input, double *output)
void fullPermutationOne(const int Nv, const double *input, double *output)
void fullPermutationTwo(const int Nv, const double *input, double *output)