CoulombIntegralsProvider
Distribution
size_t CoulombIntegralsProvider::maxSize
const size_t CoulombIntegralsProvider::Np
const libint2::BasisSet& CoulombIntegralsProvider::shells
const Operator CoulombIntegralsProvider::op
std::vector<size_t> CoulombIntegralsProvider::mpiShells
std::vector<size_t> CoulombIntegralsProvider::offset
std::vector<std::vector<double> > CoulombIntegralsProvider::Vklmn
std::vector<std::vector<int64_t> > CoulombIntegralsProvider::ctfIndices
const size_t CoulombIntegralsProvider::maxElementsWrite
const size_t CoulombIntegralsProvider::maxShellNbf
const size_t CoulombIntegralsProvider::maxShellElements
const size_t CoulombIntegralsProvider::writesPerShell
CoulombIntegralsProvider::CoulombIntegralsProvider(const libint2::BasisSet &shells_, const Operator op_, const Distribution d, const size_t maxElementsWrite_)
References doRoundRobinDistribution, doSimpleDistribution, LOGGER, SIMPLE, sisi4s::Sisi4s::world.
void CoulombIntegralsProvider::doRoundRobinDistribution()
References sisi4s::Sisi4s::world.
Referenced by CoulombIntegralsProvider.
void CoulombIntegralsProvider::doSimpleDistribution()
References LOGGER, sisi4s::Sisi4s::world.
Referenced by CoulombIntegralsProvider.
void CoulombIntegralsProvider::compute()
References _L, ShellInfo::begin, ShellInfo::end, LOGGER.
Referenced by sisi4s::CoulombIntegralsFromGaussian::run.
void CoulombIntegralsProvider::computeHalfContract(size_t No, Tensor< double > *coeff)
References _L, ShellInfo::begin, ShellInfo::end, LOGGER.
Referenced by sisi4s::CoulombIntegralsFromGaussian::run.
std::vector< IndexRange > CoulombIntegralsProvider::getWriteRangesForShell(size_t i)
Referenced by write.
void CoulombIntegralsProvider::write(Tensor< double > *t)
References getWriteRangesForShell, LOGGER, sisi4s::Sisi4s::world.
Referenced by sisi4s::CoulombIntegralsFromGaussian::run.
void CoulombIntegralsProvider::readHalfContract(Tensor< double > *t)
References sisi4s::Sisi4s::world.
Referenced by sisi4s::CoulombIntegralsFromGaussian::run.