nwchem::BasisSetParser
std::smatch nwchem::BasisSetParser::match
Referenced by matches, parseBasis, parseFile.
bool BasisSetParser::matches(const std::string &t, const Regex &r)
References match, pars::Regex::r.
Referenced by parseBasis, parseFile.
Basis BasisSetParser::parseBasis(std::fstream &f, const std::string name)
References atom, basis_end, am::fromString, match, matches, shell_content, shell_header.
Referenced by parseFile.
BasisSet BasisSetParser::parseFile(const std::string &fileName)
References basis_header, comment, match, matches, no_line, parseBasis.
Referenced by sisi4s::MoReader::run.